Kotlin/dokka

.gitignore, src/Analysis/AnalysisEnvironment.kt, src/Analysis/CommentsAPI.kt, src/Analysis/CompilerAPI.kt, src/Kotlin/ContentBuilder.kt, src/Kotlin/DocumentationBuilder.kt, src/main.kt, test/src/TestAPI.kt
Package org.jetbrains.jet does no longer exist in the compiler
=> Update to the latest Kotlin compiler API

build.xml
fatjar to be used in command-line and to be bundled with maven-plugin
=> fatjar ant target to get complete dokka-fat.jar 

dokka-gradle-plugin/src/main/kotlin/main.kt
For example, if multiple formats should be generated, adding more tasks like
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
outputFormat = 'javadoc'
outputDirectory = "$buildDir/javadoc"
}
is now possible.
Also,  dokka gradle tasks now know when they are up-to-date and don't have to generate anything.
=> Allow multiple dokka tasks for one project, up-to-date check

core/src/main/kotlin/Analysis/AnalysisEnvironment.kt
Set idea.io.use.fallback to "true", to fix idea environment startup warning on windows
=> Warning on windows fix

runners/android-gradle-plugin/build.gradle, runners/android-gradle-plugin/src/main/kotlin/mainAndroid.kt
Support getting variantManager after android
build tools 2.3.0 API changes
Fix for issue #140
=> Fix dokka-android to support new build tools

runners/gradle-plugin/src/main/kotlin/main.kt
Fixes https://github.com/Kotlin/dokka/issues/178
=> Make PackageOptions serializable

README.md, runners/gradle-plugin/src/main/kotlin/main.kt
=> Add global configuration "includeNonPublic"

README.md
Porting over changes from https://github.com/google/dokka/pull/9
=> Add instructions for configuring Dokka in IDEA

README.md
Updated instructions to reflect loading project with IntellJ IDEA
2019.3.
=> Update IDE instructions in README

core/src/main/kotlin/CoreExtensions.kt, core/src/main/kotlin/DokkaGenerator.kt, core/src/main/kotlin/Java/JavadocParser.kt, core/src/main/kotlin/links/DRI.kt, core/src/main/kotlin/model/Documentable.kt, core/src/main/kotlin/pages/PageContentBuilder.kt, core/src/main/kotlin/plugability/DefaultExtensions.kt, core/src/main/kotlin/renderers/HtmlRenderer.kt, core/src/main/kotlin/transformers/psi/DefaultPsiToDocumentationTranslator.kt, core/src/main/kotlin/transformers/psi/PsiToDocumentationTranslator.kt
=> Java parsing

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
Another take at https://github.com/Kotlin/dokka/pull/594
See https://github.com/Kotlin/dokka/commit/00f92bd73bfd8cb1e6da40e0bafe43db3f443e5efor the discussion. 
The retry seems useless now so I removed it altogether. Let me know if you think this deserves more comments.
=> Remove stack overflow error

core/src/main/kotlin/plugability/DefaultExtensions.kt, core/src/main/kotlin/renderers/DefaultRenderer.kt, core/src/main/kotlin/renderers/html/HtmlRenderer.kt, core/src/main/kotlin/renderers/html/NavigationPage.kt, core/src/main/kotlin/renderers/html/htmlPreprocessors.kt, core/src/main/resources/dokka/scripts/navigationLoader.js, core/src/main/resources/dokka/styles/style.css
This pr adds transformable navigation page to default html renderer. It is generated and rendered only once and then it can be dynamically embeded on each page.
=> Transformable navigation

core/src/main/kotlin/renderers/html/htmlPreprocessors.kt
=> missing first

core/src/main/kotlin/CoreExtensions.kt, core/src/main/kotlin/plugability/DefaultExtensions.kt, core/src/main/kotlin/renderers/DefaultRenderer.kt, core/src/main/kotlin/renderers/FileWriter.kt, core/src/main/kotlin/renderers/OutputWriter.kt, core/src/main/kotlin/renderers/html/htmlPreprocessors.kt, core/src/main/kotlin/resolvers/DefaultLocationProvider.kt
=> Cleans up file extension redundancy

core/src/main/kotlin/links/DRI.kt, core/src/test/kotlin/basic/DRITest.kt
=> Fixes infinite recursion in DRI expansion caused by bounds on nullable parameters

testApi/src/main/kotlin/testApi/testRunner/DokkaTestGenerator.kt, testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt
Added test point after rendering. Fixes #601
=> Extended tests

.gitignore, core/src/main/kotlin/model/Documentable.kt, plugins/base/src/main/kotlin/transformers/documentables/DefaultDocumentableMerger.kt, plugins/base/src/main/kotlin/transformers/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/markdown/KDocTest.kt, plugins/base/src/test/kotlin/multiplatform/BasicMultiplatformTest.kt, plugins/mathjax/src/main/kotlin/MathjaxPlugin.kt, settings.gradle.kts
Rewrite of DefaultDescriptorToDocumentableTranslator
=> Descriptor to Documentable rewrite

core/src/main/kotlin/model/Documentable.kt, plugins/base/src/test/kotlin/issues/IssuesTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/CommentTest.kt, plugins/base/src/test/kotlin/model/FunctionsTest.kt, plugins/base/src/test/kotlin/model/JavaTest.kt, plugins/base/src/test/kotlin/model/PackagesTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/kotlin/utils/ModelUtils.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt, testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt
=> Core tests

core/src/main/kotlin/model/Documentable.kt, core/src/main/kotlin/model/aditionalExtras.kt, core/src/main/kotlin/model/properties/properties.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt
Added information regarding keywords and modifiers to Documentables.
=> Added more information to Documentables

core/src/main/kotlin/model/Documentable.kt, plugins/base/src/main/kotlin/transformers/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt
=> Introduce custom visibility

core/src/main/kotlin/CoreExtensions.kt, core/src/main/kotlin/links/DRI.kt, core/src/main/kotlin/model/Documentable.kt, core/src/main/kotlin/model/SignatureProvider.kt, core/src/main/kotlin/pages/ContentNodes.kt, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/providers/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/signatures/SignatureProvider.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultDocumentableToPageTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt, plugins/base/src/test/kotlin/renderers/html/GroupWrappingTest.kt, plugins/base/src/test/kotlin/renderers/html/PlatformDependentHintTest.kt, plugins/base/src/test/kotlin/utils/TestOutputWriter.kt, plugins/base/src/test/resources/expect/test/out/root/fn.html, plugins/base/src/test/resources/expect/test/out/root/index.html, testApi/src/main/kotlin/testApi/context/MockContext.kt
Creates mechanism for signature providers. Also adds wrapping for group contents and hints about platform dependent content.
=> Rewrite of signature providing & other minor changes to content model

core/src/main/kotlin/parsers/HtmlParser.kt, core/src/main/kotlin/parsers/MarkdownParser.kt, core/src/main/kotlin/parsers/factories/DocTagsFromIElementFactory.kt, core/src/main/kotlin/parsers/factories/DocTagsFromStringFactory.kt
Name inconsistency, probably leftover after refactoring model names. It was bugging me for some time :P
=> DocName Factories renamed to DocTag Factories

core/src/main/resources/dokka/scripts/navigationLoader.js, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/NavigationPage.kt
Added IDs to navigation elements, tagged each contentpage with ID. Added js function, which collapses navigation based on opened content
=> Collapsing navigation menu properly to opened page

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
=> Render types for properties

plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/transformers/documentables/InheritorsExtractorTransformer.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/issues/IssuesTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/FunctionsTest.kt, plugins/base/src/test/kotlin/model/InheritorsTest.kt, plugins/base/src/test/kotlin/model/JavaTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/kotlin/utils/ModelUtils.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt
Added information about child types.
=> Inheritors for types

core/src/main/kotlin/DokkaGenerator.kt, core/src/main/kotlin/plugability/DokkaContext.kt, testApi/src/main/kotlin/testApi/context/MockContext.kt
Added warning when unused extension points are detected. Closes #631
=> Unused extension point warning

plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
Extensions for html preprocessors. Fix #630
=> extension for html preprocessors

core/src/main/kotlin/transformers/pages/PageTransformerBuilders.kt, core/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt
Added builders for page transformers. Fixes #633
=> Page transformer builders

core/src/main/kotlin/model/aditionalExtras.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/enums/EnumsTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/FunctionsTest.kt, plugins/base/src/test/kotlin/model/InheritorsTest.kt, plugins/base/src/test/kotlin/model/JavaTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/kotlin/pageMerger/PageNodeMergerTest.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt, plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
Minor bug fixes in annotation processing, key for AdditionalModifiers changed to companion object and additional core tests.
=> Additional modifiers fix and more core tests

core/src/main/kotlin/model/defaultValues.kt, core/src/main/kotlin/model/properties/PropertyContainer.kt, core/src/main/kotlin/transformers/pages/PageTransformerBuilders.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt
Added documenting default values of parameters in extras. Closes #741
=> Add default values for parameters

core/src/main/kotlin/CoreExtensions.kt, core/src/main/kotlin/DokkaGenerator.kt, core/src/main/kotlin/configuration.kt, core/src/main/kotlin/model/documentableUtils.kt, core/src/main/kotlin/transformers/documentation/PreMergeDocumentableTransformer.kt, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/transformers/documentables/DocumentableVisibilityFilter.kt, testApi/src/main/kotlin/testApi/testRunner/DokkaTestGenerator.kt, testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt
=> Adding documentable filtering based on visibility

runners/cli/src/main/kotlin/cli/main.kt, runners/maven-plugin/src/main/kotlin/DokkaMojo.kt
=> Fixed maven and CLI runners stdlib links bug

core/src/main/resources/dokka/styles/style.css, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
Fixed alignment and colors of platform tags. Common tag is always #F4F4F4. Platform tags are now based on target instead of analysis platform
=> Platform tags adjustments

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
Tested on multiplatfrom with jvm, js and linuxX64 actuals. Works fine now
=> Fix missing expect KDoc when all actual implementations don't override KDoc

core/src/main/kotlin/model/Documentable.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/transformers/documentables/DefaultDocumentableMerger.kt, plugins/base/src/main/kotlin/transformers/documentables/DocumentableVisibilityFilter.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/resources/expect/annotatedFunctionWithAnnotationParameters/out/html/root/[jvm root]/-fancy/index.html, plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
=> Receiver for extension property #809

core/src/main/kotlin/model/doc/DocTag.kt, core/src/main/kotlin/pages/ContentNodes.kt, core/src/main/kotlin/pages/utils.kt, core/src/main/resources/dokka/styles/style.css, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/transformers/pages/merger/SameMethodNamePageMergerStrategy.kt, plugins/base/src/main/kotlin/transformers/pages/samples/SamplesTransformer.kt, plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt, plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt, plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt, plugins/gfm/src/main/kotlin/GfmPlugin.kt, test-tools/src/main/kotlin/matchers/content/ContentMatchersDsl.kt
=> Add divergent rendering

plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/gfm/src/main/kotlin/GfmPlugin.kt
Added anchors for:
- headers - headers title lowercased and without whitespaces e.g. "See also" -> "#seealso"
- symbols - symbols DRI
=> Add anchors to pages

plugins/base/search-component/src/main/js/search/app-root.js, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
That was the issue that stopped user from being redirected to a page that was searched
=> Change event listener to propagate events further

core/src/main/kotlin/model/Documentable.kt, core/src/main/kotlin/model/aditionalExtras.kt, core/src/main/kotlin/model/extraModifiers.kt, core/src/main/kotlin/pages/ContentNodes.kt, plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt, plugins/base/src/main/kotlin/signatures/JvmSingatureUtils.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt, plugins/base/src/main/kotlin/signatures/SignatureProvider.kt, plugins/base/src/main/kotlin/transformers/documentables/ModuleAndPackageDocumentationTransformer.kt, plugins/base/src/main/kotlin/transformers/pages/annotations/DeprecatedStrikethroughTransformer.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt, plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt, plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt, plugins/base/src/test/kotlin/content/signatures/ContentForSignaturesTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/FunctionsTest.kt, plugins/base/src/test/kotlin/model/JavaTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt, plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt, plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt, plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureUtils.kt
=> Annotations fix

plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js
=> Initially show only the default chosen tab body

.github/workflows/rebase.yml
This PR is for `master` branch since according to docs workflow has to be registered on `default or master` branch in order to work. Rebases are performed against the branch that PR wants to be merged to. 
In order to rebase type `/rebase` in comments and github action will be triggered.
https://help.github.com/en/actions/reference/events-that-trigger-workflows#issue-comment-event-issue_comment
=> Rebase workflow

core/src/main/kotlin/pages/ContentNodes.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/Tags.kt, plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/resources/dokka/styles/style.css
Something like this:
It would be nice to have an indent when we break arrays but thats an improvement.
=> Stdlib wrapping in signature

core/src/main/kotlin/model/aditionalExtras.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/resources/dokka/styles/style.css, plugins/base/src/test/kotlin/enums/EnumsTest.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt
=> Enum constructor values

plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js
=> Added persistence in window scope for filtering and tabs state.

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt, plugins/base/src/test/kotlin/utils/TestOutputWriter.kt
=> Fixed problem with linking absolute links as relative

core/src/main/kotlin/model/aditionalExtras.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/enums/EnumsTest.kt
=> Make enum entry constructor sourceset dependent

core/src/main/kotlin/pages/ContentNodes.kt, core/src/main/kotlin/pages/PageNodes.kt, plugins/base/frontend/src/main/components/app/index.scss, plugins/base/frontend/src/main/components/app/index.tsx, plugins/base/frontend/src/main/components/search/search.scss, plugins/base/frontend/src/main/components/search/search.tsx, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/base/src/main/resources/dokka/scripts/clipboard.js, plugins/base/src/main/resources/dokka/scripts/navigationLoader.js, plugins/base/src/main/resources/dokka/styles/style.css, plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt, plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt, plugins/base/src/test/kotlin/enums/EnumsTest.kt, plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt, plugins/base/src/test/kotlin/markdown/LinkTest.kt, plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt
fixes #904
fixes #884
And after merging #936 fixes #794
I'd like ask reviewers to look at the rendered output for stdlib / example and check if it looks ok
=> 904 - Improve CSS

core/src/main/kotlin/model/aditionalExtras.kt, core/src/main/kotlin/pages/ContentNodes.kt, core/src/main/kotlin/pages/PageNodes.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/Tags.kt, plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt, plugins/base/src/main/kotlin/transformers/pages/annotations/DeprecatedStrikethroughTransformer.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/main/resources/dokka/styles/style.css, plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt, plugins/base/src/test/kotlin/content/signatures/SkippingParenthesisForConstructorsTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/FunctionsTest.kt, plugins/base/src/test/kotlin/model/JavaTest.kt, plugins/base/src/test/kotlin/model/PropertyTest.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt, plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt, plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt, plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureUtils.kt
Fixes #905 #887 #886 #835 
There is some front-end to be polished
=> Make annotations and keywords platform dependent

.github/workflows/s3-snapshots.yml
Note: this will fail without secrets set up
=> Add documenting of stdlib and publishing to s3 on branch push

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
=> Added typealiases to Types tab 

core/src/main/kotlin/model/extraModifiers.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt
=> KotlinSignatureProvider: Render 'fun interface' into signature

plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt, plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
=> Fixed sources platform tags; tailrec and external modifiers; sorting.

core/src/main/kotlin/pages/ContentNodes.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
=> Change search component items content to distinguish symbols with name clash

plugins/base/src/main/resources/dokka/styles/style.css
=> Fixed css to make links underlined only on hover

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt
=> Added fallbacks for samples, params and see also

plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/resources/dokka/styles/style.css, plugins/gfm/src/main/kotlin/GfmPlugin.kt
=> Platform restriction handling for platform-hinted content

plugins/base/frontend/build.gradle.kts, plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt
Draft until aws pass
EDIT: Passed
=> Repaired frontend gradle module

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/javadoc/src/main/kotlin/javadoc/JavadocPageCreator.kt, plugins/javadoc/src/main/kotlin/javadoc/KorteJavadocRenderer.kt
=> Internal links

plugins/base/frontend/build.gradle.kts
=> Fix npm caching

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
=> Actual typealias fix

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt, plugins/base/src/test/kotlin/content/signatures/ContentForSignaturesTest.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt
=> Show fully qualified name for typealias targeting different package

plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt, plugins/base/src/test/kotlin/transformers/CommentsToContentConverterTest.kt
=> Handling multi-line list items

runners/cli/src/main/kotlin/cli/main.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/configurationImplementations.kt
with ExternalDocumentationLink.Builder
Closes #914
=> Replace direct creation of ExternalDocumentationLink

plugins/base/frontend/src/main/components/search/search.scss, plugins/base/frontend/src/main/components/search/search.tsx, plugins/base/frontend/src/main/components/search/types.ts, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
=> Separated search key and display label in search component

plugins/base/src/main/kotlin/resolvers/local/BaseLocationProvider.kt
The `getExternalLocation` is called on a bunch of different worker threads, causing the `cache` to effectively not be used due to concurrency issues. This causes a downstream issue where `openConnection()` throws a `SocketTimeoutException: connect timed out` regardless of the configured timeout settings, presumably due to the OS being overloaded with connections and immediately rejecting new requests at a certain point.
This CL fixes the issue by locking the network request and subsequent parsing.
=> Fix concurrency issue managing package request cache

plugins/base/src/main/kotlin/parsers/MarkdownParser.kt, plugins/base/src/main/kotlin/transformers/documentables/ModuleAndPackageDocumentationTransformer.kt
=> Bugfix for links in module page

kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/AnalysisEnvironment.kt
The javadoc tag providers weren't registered, leading to crashes like this:
```
Exception in thread "main" java.lang.NullPointerException
at com.intellij.psi.impl.source.javadoc.PsiDocTagValueImpl.getReference(PsiDocTagValueImpl.java:52)
at org.jetbrains.dokka.base.translators.psi.JavadocParser.toDocumentationLink(JavadocParser.kt:186)
at org.jetbrains.dokka.base.translators.psi.JavadocParser.convertInlineDocTag(JavadocParser.kt:196)
at org.jetbrains.dokka.base.translators.psi.JavadocParser.convertJavadocElements(JavadocParser.kt:139)
at org.jetbrains.dokka.base.translators.psi.JavadocParser.getDescription(JavadocParser.kt:127)
at org.jetbrains.dokka.base.translators.psi.JavadocParser.parseDocumentation(JavadocParser.kt:34)
at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentab …
```
=> Fix crash resolving PsiDocTagValue

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt, plugins/base/src/test/kotlin/renderers/html/HtmlRenderingOnlyTestBase.kt
=> Single platform bubbles fix

core/src/main/kotlin/DokkaBootstrap.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/ProxyUtils.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/AutomagicProxyTest.kt
=> DokkaGradlePlugin: Avoid UndeclaredThrowableException

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/resources/dokka/styles/style.css, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt
=> Fix Since Kotlin css view

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
=> Add a link to dokka Github page in footer

plugins/base/src/main/resources/dokka/styles/style.css
=> Samples css

gradle.properties, runners/maven-plugin/build.gradle.kts
=> Update compiler version to 1.4.0-rc-173

plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js
=> Allow anchors to redirect user without refresh

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/test/kotlin/signatures/SignatureTest.kt
=> Remove `actual` keyword from typealiases

.run/it-android-0_dokka.run.xml, integration-tests/gradle/projects/it-android-0/build.gradle.kts, integration-tests/gradle/projects/it-android-0/gradle.properties, integration-tests/gradle/projects/it-android-0/src/main/java/it/android/IntegrationTestActivity.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Android0GradleIntegrationTest.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
=> Add link to androidx documentation by default for Android projects

gradle.properties, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Android0GradleIntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGroovyIntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Collector0IntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multimodule0IntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multiplatform0GradleIntegrationTest.kt
=> Update to Kotlin version 1.4.0-rc

plugins/javadoc/src/main/resources/views/components/base.korte, plugins/javadoc/src/main/resources/views/components/head.korte, plugins/javadoc/src/main/resources/views/components/indexPage.korte, plugins/javadoc/src/main/resources/views/components/pageStart.korte
i don't know if it should go to RC or 1.4.0. Its up to you
=> Remove leftover from javadoc

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/NavigationPage.kt, plugins/base/src/main/kotlin/renderers/html/htmlFormatingUtils.kt, plugins/base/src/main/resources/dokka/styles/style.css
=> Fix truncated text on sidebar with long packages

plugins/base/frontend/package-lock.json, plugins/base/frontend/package.json, plugins/base/frontend/src/main/components/search/searchResultRow.tsx, plugins/base/frontend/src/main/types/@jetbrains/index.d.ts, plugins/base/frontend/tsconfig.json
Related issue:
https://youtrack.jetbrains.com/issue/RG-2108
=> Fix JS markdown component generating lots of files with highlighting

.run/it-basic_dokka.run.xml, core/src/main/kotlin/model/Documentable.kt, core/src/main/kotlin/transformers/documentation/PreMergeDocumentableTransformer.kt, integration-tests/gradle/projects/it-basic/build.gradle.kts, integration-tests/gradle/projects/it-basic/src/main/kotlin/it/internal/InternalClass.kt, integration-tests/gradle/projects/it-basic/src/main/kotlin/it/suppressedByPackage/SuppressedByPackage.kt, integration-tests/gradle/projects/it-basic/src/main/kotlin/it/suppressedByPath/SuppressedByPath.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt, integration-tests/src/main/kotlin/org/jetbrains/dokka/it/AbstractIntegrationTest.kt, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/transformers/documentables/EmptyPackagesFilterTransformer.kt, plugins/base/src/main/kotlin/transformers/documentables/ReportUndocumentedTransformer.kt, plugins/base/src/main/kotlin/transformers/documentables/SuppressedDocumentableFilterTransformer.kt, plugins/base/src/test/kotlin/filter/EmptyPackagesFilterTest.kt, plugins/base/src/test/kotlin/transformers/SuppressedDocumentableFilterTransformerTest.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt, testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt
=> Implement DocumentableFilterSuppressedTransformer

gradle.properties
=> Update kotlin compiler to 1.4.0

core/src/main/kotlin/DokkaGenerator.kt, core/src/main/kotlin/printDokkaMaturityWarning.kt
=> Print maturity warning when running dokka

core/src/main/kotlin/model/Documentable.kt, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/test/kotlin/signatures/SignatureTest.kt
=> Add generic typealiases proper parsing

buildSrc/src/main/kotlin/org/jetbrains/DokkaPublicationChannel.kt, buildSrc/src/main/kotlin/org/jetbrains/ValidatePublications.kt, buildSrc/src/main/kotlin/org/jetbrains/publication.kt, core/build.gradle.kts, gradle.properties, runners/gradle-plugin/build.gradle.kts
=> Add support for space package publishing

integration-tests/gradle/projects/it-multiplatform-0/build.gradle.kts, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt
=> Fix convention for ExternalDocumentationLink#packageListUrl

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/main.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaPluginApplyTest.kt
=> Add task descriptions to all dokka tasks

core/src/main/kotlin/pages/ContentNodes.kt, runners/gradle-plugin/build.gradle.kts, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/checkDependentSourceSets.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/KotlinSourceSetGist.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/AndroidAutoConfigurationTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/CheckSourceSetDependenciesTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/ConfigureWithKotlinSourceSetGistTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaTaskTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/IsMainSourceSetTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/KotlinSourceSetGistTest.kt
=> Fix missing dokka source sets on Android when tasks are configured eagerly

README.md
=> Update dokka README.md to reflect changes for 1.4.0

plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt, plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt, testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt
=> Fix regression #1361: broken source links on windows

core/src/main/kotlin/defaultExternalLinks.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Android0GradleIntegrationTest.kt, plugins/base/src/main/kotlin/resolvers/external/javadoc/AndroidExternalLocationProvider.kt, plugins/base/src/main/kotlin/resolvers/external/javadoc/JavadocExternalLocationProvider.kt, plugins/base/src/main/kotlin/resolvers/external/javadoc/JavadocExternalLocationProviderFactory.kt, plugins/base/src/test/kotlin/locationProvider/AndroidExternalLocationProviderTest.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt
=> Fix external links to Android and Androix documentations

README.md, runners/gradle-plugin/MIGRATION.md
=> Add first version of MIGRATION.md to help users migrating to new dokka

plugins/base/src/main/kotlin/allModulePage/MultimodulePageCreator.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
[dokka.zip](https://github.com/Kotlin/dokka/files/5142209/dokka.zip)
=> Make all modules page look the same as module page #1335

plugins/base/frontend/src/main/components/root.tsx, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
=> Hide navigation pane search on multimodule page

core/src/main/kotlin/DokkaGenerator.kt, plugins/base/src/test/kotlin/basic/AbortGracefullyOnMissingDocumentablesTest.kt
=> Abort Generation gracefully when no documentables found

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt
=> Also add KotlinCompile#classpath to final classpath calculation

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
Closes #1419 
Before: 
____
With PR:
=> Add whitespace in parameters of classlike signature

plugins/base/base-test-utils/src/main/kotlin/renderers/TestPage.kt, plugins/base/src/main/kotlin/parsers/MarkdownParser.kt, plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/resources/dokka/styles/style.css, plugins/base/src/test/kotlin/markdown/ParserTest.kt, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt, plugins/base/src/test/kotlin/renderers/html/GroupWrappingTest.kt, plugins/base/src/test/kotlin/renderers/html/SourceSetDependentHintTest.kt, plugins/gfm/src/main/kotlin/GfmPlugin.kt, plugins/gfm/src/test/kotlin/renderers/gfm/DivergentTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/GroupWrappingTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/SimpleElementsTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/SourceSetDependentHintTest.kt
=> Null pointer on images

core/src/main/kotlin/model/doc/DocTag.kt, plugins/base/src/main/kotlin/parsers/MarkdownParser.kt, plugins/base/src/main/kotlin/parsers/factories/DocTagsFromIElementFactory.kt, plugins/base/src/test/kotlin/markdown/ParserTest.kt
This PR is built on top of [that](https://github.com/Kotlin/dokka/pull/1377). Don't merge it unless previous one is approved and merged
=> Tests for markdown

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/NavigationPage.kt, plugins/base/src/main/kotlin/renderers/html/htmlFormatingUtils.kt, plugins/base/src/main/resources/dokka/styles/style.css
=> Mobile header font size #1475

plugins/base/src/main/kotlin/allModulePage/MultimodulePageCreator.kt
=> Make all modules page look the same as package page

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt, plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt, plugins/base/src/test/kotlin/utils/contentUtils.kt
A redo of #788 since the logic there was quite weird
=> Handle multiple authors

plugins/base/src/main/resources/dokka/styles/style.css
=> Inconsistent direction of pointing arrows in module view

docs/src/doc/docs/developer_guide/data_model.md
an -> a
referring to https://www.quora.com/Which-is-the-correct-grammar-usage-a-unique-or-an-unique
=> fix grammar error

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt, runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaTaskTest.kt
issue was visible on javadoc since we display version there
=> Fix gradle passing 'unspecified' version to dokka configuration

plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationProvider.kt, plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationTest.kt
Issue was reported on slack, here are details: https://kotlinlang.slack.com/archives/C0F4UNJET/p1606804429121300
=> Resolve an issue with cross package linking in javadoc

core/test-api/src/main/kotlin/testApi/testRunner/TestDokkaConfigurationBuilder.kt, core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/MultiModule0IntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/CoroutinesGradleIntegrationTest.kt, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/StdlibGradleIntegrationTest.kt, integration-tests/src/main/kotlin/org/jetbrains/dokka/it/AbstractIntegrationTest.kt, plugins/all-modules-page/build.gradle.kts, plugins/all-modules-page/src/test/kotlin/MultiModuleDokkaTestGenerator.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/AddToNavigationCommandResolutionTest.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/AddToSearchCommandResolutionTest.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/ResolveLinkCommandResolutionTest.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/ResolveLinkGfmCommandResolutionTest.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/SubstitutionCommandResolutionTest.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/assertHtmlEqualsIgnoringWhitespace.kt, plugins/all-modules-page/src/test/kotlin/org/jetbrains/dokka/allModulesPage/templates/mockedPackageListFactory.kt, plugins/base/base-test-utils/src/main/kotlin/testRunner/baseTestApi.kt, plugins/base/src/main/kotlin/resolvers/shared/PackageList.kt, plugins/gfm/gfm-template-processing/src/main/kotlin/org/jetbrains/dokka/gfm/templateProcessing/GfmTemplateProcessingStrategy.kt
please review https://github.com/Kotlin/dokka/pull/1631 before it
=> Multimodule tests

gradle/wrapper/gradle-wrapper.properties
=> Bump Gradle version to 6.7.1

plugins/all-modules-page/src/main/kotlin/MultimodulePageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt, plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt, plugins/gfm/src/test/kotlin/renderers/gfm/SimpleElementsTest.kt
=> Refactor ContentTable builder and fix GFM table rendering

plugins/base/base-test-utils/build.gradle.kts, plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt, plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt, plugins/base/src/test/kotlin/model/annotations/JavaAnnotationsForParametersTest.kt, plugins/base/src/test/kotlin/model/annotations/KotlinAnnotationsForParametersTest.kt, plugins/base/src/test/kotlin/utils/ModelUtils.kt, plugins/base/src/test/kotlin/utils/TestUtils.kt
=> Annotations for parameters

plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt, plugins/kotlin-as-java/src/main/kotlin/jvmSynthetic.kt, plugins/kotlin-as-java/src/test/kotlin/JvmSyntheticTest.kt
This PR handles `JvmSynthetic` on functions, properties, getters and setters by not emitting the associated elements.
=> JvmSynthetic

kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/DRIFactory.kt, kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/DRITargetFactory.kt, plugins/base/src/test/kotlin/markdown/LinkTest.kt
=> Fix links to method parameters from documentation

plugins/base/src/main/kotlin/parsers/moduleAndPackage/parseModuleAndPackageDocumentationFragments.kt
=> Be more explicit about what went wrong in package and module docs

README.md, docs/src/doc/docs/user_guide/gradle/usage.md, docs/src/doc/docs/user_guide/maven/usage.md
https://github.com/Kotlin/kotlinx.html/issues/173#issuecomment-826522662
=> Remove HTML Space Repo after release on MavenCentral

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaLeafTask.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt, runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTaskPartial.kt
Helps with #1867.  I'm not familiar enough with Gradle to write a proper extension to configure things outside of the tasks.
=> Adds a supertype for leaf dokka tasks that defines dokkaSourceSets

plugins/base/frontend/package-lock.json, plugins/base/frontend/package.json
Upgrades sass-loader so buids on Windows work (at least my local ones).
=> Upgrade sass-loader

plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt
Fixes https://github.com/Kotlin/dokka/issues/1941
=> Add all rendering strategies to CommonMark renderer and enforce exhaustive matches

core/api/core.api, core/src/main/kotlin/pages/utils.kt, plugins/gfm/api/gfm.api, plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/GfmPlugin.kt, plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/BriefCommentPreprocessor.kt, plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt, plugins/gfm/src/test/kotlin/renderers/gfm/DivergentTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/GroupWrappingTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/SimpleElementsTest.kt, plugins/gfm/src/test/kotlin/renderers/gfm/SourceSetDependentHintTest.kt, plugins/jekyll/api/jekyll.api, plugins/jekyll/src/main/kotlin/JekyllPlugin.kt
ready for review and merge
Fixes #1853
=> GFM renderer: cleanup paragraphs and tables

docs/src/doc/docs/user_guide/base-specific/frontend.md
=> Changing from intellij to intelliJ

docs/src/doc/docs/user_guide/cli/usage.md
=> plugin configuration changing from fqPluginName=json^^fqPluginName=json.. to `fqPluginName=json...`

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/htmlFormatingUtils.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt, plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
=> Fix overflow in throws tables

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt, plugins/base/src/test/kotlin/signatures/SignatureTest.kt
=> Remove extra `fun` keyword in functional interface signature

core/src/main/kotlin/model/DisplaySourceSet.kt, plugins/base/api/base.api, plugins/base/src/main/kotlin/resolvers/local/DokkaLocationProvider.kt, plugins/base/src/main/kotlin/transformers/pages/merger/SameMethodNamePageMergerStrategy.kt, plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
hacked out untill https://github.com/Kotlin/dokka/issues/1171
=> Fix broken link in kotlinx.serialization

plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt
=> Include parenthesis for merged pages

plugins/base/api/base.api, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/transformers/documentables/DocumentableReplacerTransformer.kt, plugins/base/src/main/kotlin/transformers/documentables/KotlinArrayDocumentableReplacerTransformer.kt, plugins/base/src/test/kotlin/filter/KotlinArrayDocumentableReplacerTest.kt
According to https://github.com/Kotlin/dokka/issues/2041#issuecomment-887444062
=> Replace arrays of primitive types on std arrays

plugins/base/src/main/resources/dokka/styles/jetbrains-mono.css, plugins/base/src/main/resources/dokka/styles/prism.css, plugins/base/src/main/resources/dokka/styles/style.css
=> Fix signatures being bolded, increase spacing in divergent

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/resources/dokka/styles/style.css
This also works on other browsers like edge or safari 😮
=> Fix footer on firefox

plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js
=> Fix js error on pages without tabs

.github/workflows/apiCheck.yml, .github/workflows/dokka-examples.yml, .github/workflows/gh-pages-examples.yml, .github/workflows/gh-pages.yml, .github/workflows/gradle-test.pr.yml, .github/workflows/s3-snapshots.yml
Merge this one to close #2090.
=> Bump setup-java github actions to v2

core/test-api/api/test-api.api, core/test-api/src/main/kotlin/testApi/testRunner/TestDokkaConfigurationBuilder.kt, plugins/base/api/base.api, plugins/base/src/main/kotlin/DokkaBase.kt, plugins/base/src/main/kotlin/renderers/html/SearchbarDataInstaller.kt, plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt, plugins/base/src/main/kotlin/resolvers/local/DokkaLocationProvider.kt, plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt
Or this can be implemented through a new template command.  It might be easier to configure. What's better?
On the other hand, somebody can want to use different stylesheets in submodules
=> Fix adding new custom stylesheets in submodules

plugins/base/src/main/resources/dokka/styles/style.css
http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/serialization/dc54ebd/kotlinx-serialization-core/kotlinx.serialization/-deserialization-strategy/deserialize.html
=> Fix paragraph margin and label highlighting

docs/src/doc/docs/user_guide/base-specific/frontend.md
I fixed the links in the last line and improved the formatting of the important part
=> Fix links in the last line

plugins/base/src/main/kotlin/renderers/FileWriter.kt
`FileWriter.write(...)` can be invoked from different threads simultaneously
=> Fix `FileWriter` concurrency

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
There was wrong order of platform bubbles in the header
=> Fix order of platform bubbles in header

plugins/base/src/main/resources/dokka/styles/prism.css
=> Fix highlighting style

plugins/base/base-test-utils/api/base-test-utils.api, plugins/base/base-test-utils/src/main/kotlin/renderers/JsoupUtils.kt, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt
=> Add space between funs descriptions

examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
=> Fix for repositories not defined issue in versioning multimodule example

gradle.properties
After merging this, I'll update `dokka_version_base` separately for both master and `1.6.20` branch (will create it after this PR)
=> Update Kotlin to 1.6.20-RC

docs/src/doc/docs/community/plugins-list.md
Feel free to tell me if the plugin should handle some quality level before to be added in this list.
I'm currently working on supporting dark mode and be able to configure themes from gradle (not sure how I can do that latter).
EDIT: dark mode and theme configuration are supported now
=> Added Mermaid plugin to the plugins-list.md

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt
=> Fix classpath in HMPP

buildSrc/build.gradle.kts
These plugins are not updated by dependabot automatically.
=> Bump plugins in buildSrc

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
=> Make long property names breakable

CONTRIBUTING.md, README.md, docs/src/doc/docs/community/plugins-list.md, docs/src/doc/docs/user_guide/base-specific/frontend.md, docs/src/doc/docs/user_guide/cli/usage.md, docs/src/doc/docs/user_guide/gradle/usage.md, examples/gradle/dokka-customFormat-example/build.gradle.kts, examples/gradle/dokka-gradle-example/build.gradle.kts, examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts, examples/gradle/dokka-library-publishing-example/build.gradle.kts, examples/gradle/dokka-multimodule-example/settings.gradle.kts, examples/gradle/dokka-multiplatform-example/build.gradle.kts, examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts, examples/gradle/dokka-versioning-multimodule-example/parentProject/build.gradle.kts, examples/maven/pom.xml, gradle.properties, integration-tests/gradle/projects/it-basic/build.gradle.kts, integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
This is specifically for the release branch since there are conflicts with the revised documentation
=> Update references and documentation to Dokka 1.7.10

kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/AnalysisEnvironment.kt, plugins/base/src/test/kotlin/filter/JavaFileFilterTest.kt
See https://github.com/Kotlin/dokka/issues/2590
=> Fixed Java file extension spelling error and add a test

.github/workflows/qodana.yml
[Report link](https://qodana.cloud/organizations/3oDrp/teams/3y2Mp)
=> Update Qodana and add Qodana token for cloud reports

plugins/base/api/base.api, plugins/base/src/main/kotlin/transformers/documentables/DocumentableReplacerTransformer.kt
=> Open `processFunction` function

core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt, plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/JavadocPageCreator.kt, plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt, plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocPackageTemplateMapTest.kt
=> Fix package and module description truncation in javadoc

plugins/base/api/base.api, plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt, plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt, plugins/base/src/main/kotlin/renderers/html/innerTemplating/TemplateModelFactory.kt, plugins/base/src/main/kotlin/renderers/html/shouldRenderSourceSetBubbles.kt
Fixes #2847, see the issue for description
=> Display source set / platform indicators at all times

plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/utils.kt, plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationTest.kt
=> Do not leak implementation details in generated Javadoc links

mkdocs/build.gradle.kts
=> Fix mkdocs documentation leading to non-stable versions

.github/workflows/check.yml, .github/workflows/dokka-examples.yml, .github/workflows/gh-actions-artifacts-snapshots.yml, .github/workflows/gh-pages-examples.yml, .github/workflows/gh-pages.yml, .github/workflows/gradle-test.pr.yml, .github/workflows/s3-snapshots.yml
https://github.com/gradle/gradle-build-action/blob/main/README.md#removing-unused-files-from-gradle-user-home-before-saving-to-cache
=> Enable gradle-home-cache-cleanup

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
Noticed it while replying to #3027
An identical function exists, so I removed the copy-paste and imported the original one
=> Remove a copy-pasted function

plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/model/ObjectTest.kt, plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt
=> Add a test for parsing data objects

build-logic/src/main/kotlin/org/jetbrains/ValidatePublications.kt
The check was likely added because bintray did not perform any checks of its own, but Maven Central should actually check that before the staging repository is closed and all the artifacts are published, so it's not needed locally
It's in the way now because it fails with a false positive: analysis modules shadow all dependencies, and the final `.pom` has nothing in the `dependencies` block. But this local check (because it's quite primitive) does not understand it, and thinks we are trying to publish a project with unpublished dependencies.
=> Remove "project dependencies are published" check

plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt, plugins/base/src/test/kotlin/content/annotations/KotlinDeprecatedTest.kt, plugins/base/src/test/kotlin/filter/KotlinArrayDocumentableReplacerTest.kt, plugins/base/src/test/kotlin/model/ClassesTest.kt, plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt
=> Fix some tests to be compatible with K2

plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocDeprecatedTest.kt, plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocIndexTest.kt
https://github.com/Kotlin/dokka/actions/runs/6658653240
=> Fix javadoc tests for Java >=12

dokka-subprojects/analysis-kotlin-symbols/build.gradle.kts
It was forgotten to be moved over: https://github.com/Kotlin/dokka/pull/3152#discussion_r1386747152
=> Bundle analysis-kotlin-api in symbols analysis

dokka-subprojects/analysis-kotlin-api/build.gradle.kts, dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/jvm/mixed/SampleMixedJvmAnalysisTest.kt, dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/configuration/TestDokkaConfiguration.kt, dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/configuration/TestDokkaConfigurationMapper.kt, dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/java/JavaConfigurationBuilder.kt, dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/kotlin/KotlinJvmConfigurationBuilder.kt, dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/mixed/MixedJvmConfigurationBuilder.kt
* Adds the ability to run analysis-kotlin-api tests with the K2 analysis
=> Run analysis-kotlin-api tests with k2

gradle/libs.versions.toml
Here https://youtrack.jetbrains.com/issue/KT-63126 is fixed
=> Update the version of Kotlin Analysis API to 2.0.0-8561

build-logic/src/main/kotlin/dokkabuild.test-integration.gradle.kts, dokka-integration-tests/gradle/README.md, dokka-integration-tests/gradle/build.gradle.kts, dokka-integration-tests/gradle/projects/it-basic-groovy/build.gradle, dokka-integration-tests/gradle/projects/it-basic-groovy/src/custom/java/it/basic/java/SampleJavaClass.java, dokka-integration-tests/gradle/projects/it-basic-groovy/src/custom/kotlin/it/basic/PublicClass.kt, dokka-integration-tests/gradle/projects/it-sequential-tasks-execution-stress/build.gradle.kts, dokka-integration-tests/gradle/projects/it-sequential-tasks-execution-stress/src/common/java/it/basic/java/SampleJavaClass.java, dokka-integration-tests/gradle/projects/it-sequential-tasks-execution-stress/src/common/kotlin/RootPackageClass.kt, dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/JsIRGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/WasmGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/WasmJsWasiGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/CoroutinesGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/SerializationGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt, dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestEnvironment.kt
Also, it fixes #3239 for integration tests
=> [K2] Run Gradle integration tests

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/KotlinSignatureProvider.kt, dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt
=> fix: empty span for java default visibility in annotations

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/DokkaPsiParser.kt, dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/documentable/KotlinModalityTest.kt, dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/jvm/java/JavaModalityTest.kt, dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/core/api/dokka-core.api, dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/model/Documentable.kt, dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/KotlinSignatureProvider.kt, dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt
=> Support sealed interfaces rendering

build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt, build-logic/src/main/kotlin/dokkabuild/internal/GradleKotlinDslAccessors.kt
Very minor fix for the KDoc of the util accessors
=> fix package in KDoc for DokkaBuildProperties accessors

dokka-subprojects/plugin-base-frontend/package-lock.json
=> chore: updated dependencies (#3372)

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/plugin-base/src/test/kotlin/model/ConstructorsTest.kt, dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt
=> [K2] Fix missing `actual` keyword for constructors

dokka-subprojects/plugin-base/src/test/kotlin/model/ClassesTest.kt
Fixes #3384.
It is based on #3560
=> Add tests for members implemented by delegation

dokka-subprojects/plugin-base/src/main/resources/dokka/scripts/platform-content-handler.js
=> fix: made tabs work when open via iframe (#3323)

dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
based on https://github.com/Kotlin/dokka/pull/3362#discussion_r1406365731
=> Replace `Path.toRealPath` in K1 analysis to improve performance a bit

dokka-subprojects/plugin-base/src/test/kotlin/content/signatures/ConstructorsSignaturesTest.kt
Test for https://github.com/Kotlin/dokka/issues/3381
=> add test for constructor signatures for the `expect` classes

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
=> [K2] Add an import directive

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/SyntheticKDocProvider.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/plugin-base/src/test/kotlin/model/PropertyTest.kt, gradle/libs.versions.toml
Some changes: 
fully [KT-68882](https://youtrack.jetbrains.com/issue/KT-68882/Analysis-API-Refactor-KaSymbols)
=> Update AA to 2.0.20-dev-7572

dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt, dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt
=> Correctly handle case when we have `internal expect` but `public actual` declarations

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/plugin-base/src/test/kotlin/model/InheritorsTest.kt
=> Do not show the `override` modifier for fake overrides

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolExternalDocumentablesProvider.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeReferenceFactory.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeTranslator.kt, gradle/libs.versions.toml
Some changes:
- KT-55124
- KT-67786
=> Update Analysis API to 2.1.0-dev-2515

build-logic/src/main/kotlin/dokkabuild.publish-shadow.gradle.kts, gradle/libs.versions.toml
https://github.com/GradleUp/shadow/releases/tag/8.3.0
=> Migrate to com.gradleup.shadow

dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/sample/SampleAnalysisTest.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KdocMarkdownParser.kt
=> [K2] Fix duplication in logging for unresolved samples

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/translators/documentables/DeprecationSectionCreator.kt, dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/translators/documentables/DescriptionSections.kt, dokka-subprojects/plugin-base/src/test/kotlin/content/annotations/JavaDeprecatedTest.kt, dokka-subprojects/plugin-base/src/test/kotlin/content/params/ContentForParamsTest.kt
Fixes #2668
___
This PR is a follow-up from our pair-programming onboarding session with @berezinant. We've made the fix together, but Anton will re-implement it on his own
=> Display Java's `Deprecated` message

dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaPluginFunctionalTest.kt
Fix a failing test that snuck through into master.
Follow up #3796
=> Fix failing assertion in DokkaPluginFunctionalTest

dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/SourceRootChecker.kt, dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/K1SourceRootIndependentChecker.kt, dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/SourceRootIndependentChecker.kt, dokka-subprojects/plugin-base/src/test/kotlin/content/samples/ContentForSamplesTest.kt
=> Update messages for intersecting source roots and add a check for intersecting samples

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api, dokka-runners/dokka-gradle-plugin/build.gradle.kts, dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt, dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaExtension.kt, dokka-runners/dokka-gradle-plugin/src/test/kotlin/DokkaPluginTest.kt, gradle/libs.versions.toml
=> DGPv2: Add suppressInheritedMembers/suppressObviousFunctions to help with migrating

dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/OverrideJsonConfigTest.kt
Shame on me for not letting the test runs after making [a minor fix](https://github.com/Kotlin/dokka/pull/3915/commits/fe891f8b13f023f8596edebb3a7f70e886bf44b5) in #3915
=> OverrideJsonConfigTest: Fix test assertion

docs/topics/dokka-get-started.md
This PR was approved by @daniCsorbaJB.
=> Update: add information about Dokka 2.0.0 in Getting started

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt, dokka-subprojects/plugin-base/src/test/kotlin/model/InheritorsTest.kt
=> [K2] Fix `override` modifier for generic functions

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt, dokka-subprojects/plugin-base/src/test/kotlin/model/ConstructorsTest.kt
=> Fix param tag for type parameter on implicit primary constructor

dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/utils.kt, dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/v2MigrationUtils.kt, dokka-runners/dokka-gradle-plugin/src/test/kotlin/internal/MigrationHelpersTest.kt, dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaV1TaskDisabledTest.kt
=> Throw error when running V1 migration helper tasks

dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/kotlin/KotlinSourceSetGist.kt, dokka-runners/dokka-gradle-plugin/src/main/kotlin/adapters/KotlinAdapter.kt
Fix https://youtrack.jetbrains.com/issue/KT-71164/Re-evaluate-TODOs-in-DGPv2-code
=> Remove resolved TODO #1215
