README.md
core/src/main/kotlin/Kotlin/ContentBuilder.kt
core/src/main/kotlin/Kotlin/DescriptorDocumentationParser.kt
core/src/test/kotlin/model/LinkTest.kt
core/testdata/links/linkToConstantWithUnderscores.kt
dokka-gradle-plugin/build.gradle
dokka-gradle-plugin/src/main/kotlin/main.kt

@Suppress("NOT_DOCUMENTED"): Sometimes you have classes that you do not want to document without getting swamped by warnings.
Btw, the recent revision of kotlin-for-upsource.jar does not work with kotlin beta 4. Is beta 5 expected soon?

@Suppress("NOT_DOCUMENTED"), fix for linking to targets with underscores, gradle plugin improvements

---

maven-plugin/src/main/kotlin/DokkaMojo.kt

To avoid this stacktrace : 
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.8:javadocJar failed: (skipped)/target/dokkaJavadocJar isn't a directory.
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: (skipped)/target/dokkaJavadocJar isn't a directory.
at org.codehaus.plexus.archiver.AbstractArchiver.addFileSet(AbstractArchiver.java:291)
at org.codehaus.plexus.archiver.AbstractArchiver.addDirectory(AbstractArchiver.java:268)
at org.jetbrains.dokka.maven.DokkaJavadocJarMojo.generateArchive(DokkaMojo.kt:163) …

Maven : Avoid crash when no javadoc generated

---

core/src/main/resources/dokka/styles/style.css

I propose that the default styles.css should be updated so that the documentation generated is more comfortable to view on high resolution displays (above 1080p) at 100% scaling. I am on 1440p and documentation currently looks like this:
Tiny text and text bunched up all the way to the left side of the screen. Adding a max-width to the body and left/right auto-margin to center the body, and using a thicker font (Lato is **really** thin) makes the documentation more pleasant to view on 1440p or above. See below for change.
Of course, this change does not affect lower resolutions:

updated style.css to better fit wide monitor resolutions

---

core/src/main/kotlin/Kotlin/ContentBuilder.kt
core/src/test/kotlin/format/MarkdownFormatTest.kt
core/testdata/format/linksInEmphasis.kt
core/testdata/format/linksInEmphasis.md
core/testdata/format/linksInHeaders.kt
core/testdata/format/linksInHeaders.md
core/testdata/format/linksInStrong.kt
core/testdata/format/linksInStrong.md
core/testdata/format/markdownInLinks.html
core/testdata/format/tokensInEmphasis.kt
core/testdata/format/tokensInEmphasis.md
core/testdata/format/tokensInHeaders.kt
core/testdata/format/tokensInHeaders.md
core/testdata/format/tokensInStrong.kt
core/testdata/format/tokensInStrong.md

When a link or non-text token (e.g. comma) is inside an emphasis, strong, or header node, the whitespace surrounding the link (or following the non-text token) is dropped.
This PR fixes this and adds tests.
Of note - a previous test `markdownInLinks` changed as a result of this.
Was there a reason the spaces surrounding "kas" were being dropped? This seemed like a related bug, thus the expected markdownInLinks.html file was adjusted.

Fix missing whitespace around links and tokens in Markdown formatted text

---

core/src/main/kotlin/Formats/MarkdownFormatService.kt
core/src/main/kotlin/Kotlin/ContentBuilder.kt
core/src/main/kotlin/Markdown/MarkdownProcessor.kt
core/src/test/kotlin/format/MarkdownFormatTest.kt
core/testdata/format/javadocOrderedList.md
core/testdata/format/nestedLists.kt
core/testdata/format/nestedLists.md
core/testdata/format/unorderedLists.kt
core/testdata/format/unorderedLists.md

Fixes generation of Markdown lists;
- Removes erroneous new lines that were being added if nested lists present (completely broke generation)
- Fixes blank lines being stripped between list items (which changes Markdown formatting if omitted)
- Fixes ordered list numbering when when nested lists were present (item number was being reset)
*Note: This PR depends on #152 (branches from it) due to merge conflicts with #152 if branched from master only - will rebase if/when #152 resolved.*

Markdown list fixes

---

core/src/main/kotlin/Formats/PackageListService.kt

If left unsorted, then package list can change each time even though no packages were changed.

Sort package-list output

---

gradle/wrapper/gradle-wrapper.properties
runners/maven-plugin/build.gradle

This declares the inputs and outputs for the maven-plugin
generatePom task, which improves incremental build support and
as of Gradle 4.3 (updated) automatically creates directory paths
for declared outputs.
Issue: #235

Ensure build directory exists before generating POM into it (Fixes #235)

---

core/src/main/kotlin/Kotlin/DocumentationBuilder.kt

When generating JavaDoc, dokka crashes when generating documentation for certain modules. I've seen this, particularly for my Android modules. This fix, suggested by @Gh0u1L5 solves this. Please refer to the original issue for more details
Fixes #287

Fix ClassCastException when generating JavaDoc

---

core/src/main/kotlin/javadoc/dokka-adapters.kt

It looks like if you configure the `outputFormat` to `javadoc` you get a unnecessary log line printed out.
```
$ ./gradlew clean dokka
> Task :dokka 
generation completed successfully
BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
```
When activating Gradle `info` logging it also looks weird (see my `<---` marker)
```
> Task :dokka 
Task ':dokka' is not up-to-date because:
Output property (...) has been removed.
Module: foo.bar
Output: (...)
Analysing sources and libraries... 
package foo.bar: 4 declarations
done in 0 secs
Generating pages... 
generation completed successfully                         <-------
Standard Doclet version 1.8.0_121
Building tree for all the packages and classes...
Generating (..)
Building index for all the packages and classes...
Generating (...) …
```

Avoid unnecessary logging.

---

README.md

`includes` uses `include` for subitems, not `file`

Fix inner tag for "includes" in Maven syntax

---

buildSrc/src/main/groovy/org/jetbrains/CorrectShadowPublishing.groovy

This addresses Gradle 5.0 compatibility and fixes https://github.com/Kotlin/dokka/issues/388

Update pom file to use 'compile' instead of 'runtime'

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/ConfigurationExtractor.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/configurationImplementations.kt

The problem was with generating documentation for multiflavored android project. 
From now it will generate documentation for all stated flavors through dokka task's parameter.
Note it will actually squash JDocs / KDocs of all classes / methods that share same name. For convenient results pass single flavor that you want to generate documentation of.

Resolved problems with android multiflavors documentation shadowing

---

core/src/main/kotlin/Samples/KotlinWebsiteSampleProcessingService.kt

Some of the runnable samples for the Kotlin standard library fail to run on the website, because the `import samples.Sample` leaks through from the Kotlin project onto the website and cannot be found there.
Affected are for example https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-index.html and https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/as-reversed.html .
This pull request fixes that by not only ignoring imports of `samples.*` but also `samples.Sample`.

Ignore samples.Sample import when generating runnable samples

---

README.md
core/src/main/kotlin/Java/JavaPsiDocumentationBuilder.kt
core/src/test/kotlin/model/KotlinAsJavaTest.kt

PsiClass does not include methods which are not present in the text
of the code. So when there are no constructors in a java class this
represents a class that only has a default constructor. The fix is
to create one for documentation.

Implement display of Java default constructors

---

.idea/compiler.xml
core/src/main/kotlin/model/Documentable.kt
core/src/main/kotlin/pages/PageBuilder.kt
core/src/main/kotlin/pages/PageContentBuilder.kt
core/src/main/kotlin/transformers/descriptors/DefaultDescriptorToDocumentationTranslator.kt
core/src/main/kotlin/transformers/documentation/DefaultDocumentationNodeMerger.kt
core/src/main/kotlin/transformers/psi/DefaultPsiToDocumentationTranslator.kt
gradle/wrapper/gradle-wrapper.properties
plugins/kotlin-as-java/build.gradle.kts
plugins/kotlin-as-java/src/main/kotlin/KotlinAsJavaDescriptorToDocumentationTranslator.kt
plugins/kotlin-as-java/src/main/kotlin/KotlinAsJavaPageBuilder.kt
plugins/kotlin-as-java/src/main/kotlin/KotlinAsJavaPageContentBuilder.kt
plugins/kotlin-as-java/src/main/kotlin/KotlinAsJavaPlugin.kt
plugins/kotlin-as-java/src/main/kotlin/KotlinToJVMResolver.kt
plugins/kotlin-as-java/src/main/resources/META-INF/services/org.jetbrains.dokka.plugability.DokkaPlugin
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt
settings.gradle.kts

Plugin for generating documentation that reflects Kotlin code from Java viewpoint. Fix #563, fix #574

kotlin-as-java plugin

---

core/build.gradle.kts
coreDependencies/build.gradle.kts
plugins/build.gradle.kts
plugins/kotlin-as-java/build.gradle.kts
testApi/build.gradle.kts

Fixes #627
This commit removes repackaging `dokka-core` with all its dependencies by creating a publication for those dependencies. Moreover it moves `kotlinx-markdown` dependency to `coreDependencies` as this library is only present in Kotlin Bintray repository. TestAPI now publishes correctly

Update packaging structure, fix testAPI publication, simplify dependencies handling in plugins

---

core/src/main/kotlin/transformers/descriptors/DefaultDescriptorToDocumentationTranslator.kt
core/src/test/kotlin/basic/DRITest.kt

After creating the test reproducing the DRI clash, I found a bug in the `DefaultDescriptorToDocumentationTranslator`, which this commit fixes. The bug was present when running the tests but not when using dokka on an external project. I have no idea how it worked, as debugging showed that the same code from AbstractClassDescriptor runs in both cases and the code contains an assert, which had to (and did) fail. Probably the error messages are being suppressed somehow. `getMemberScope()` requires a list of type substitutions which size is being compared to the type constructor's parameters count. I suppose we don't want to substitute the type parameters and get the unsubstituted member scope instead

Fix descriptor visiting, add test for DRI clash on JS

---

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt

JavaPropertyDescriptor has no accessors, so I've altered descriptorToDocumentableTranslator to work with them.

Stdlib npe fix

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt

This commit fixes this:
to look like this:

Fix nested monospace spans in signature

---

README.md

Without this, you get errors when Gradle tries to compile `build.gradle.kts`. The fully-qualified name isn't obvious, so adding this information will save at least an Internet search for `DokkaTask` to find where it's defined.

Update README.md to specify import statement needed in build.gradle.kts

---

core/src/main/kotlin/DokkaGenerator.kt
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/documentables/ModuleAndPackageDocumentationTransformer.kt
plugins/base/src/main/kotlin/transformers/pages/samples/DefaultSamplesTransformer.kt
plugins/base/src/main/kotlin/transformers/pages/samples/KotlinWebsiteSamplesTransformer.kt
plugins/base/src/main/kotlin/transformers/pages/samples/SamplesTransformer.kt
plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt

Handles configuration inputs: Includes, SourceLinks, Samples.
Please look into the EP for Samples. I don't know if I got it right.
I also think the API for Samples (actually annotations type aliases) should be included in dokka. Right now I have seen them losely attached to stdlib.
#747

Includes, SourceLinks, Samples

---

coreDependencies/build.gradle.kts

Exclude kotlin_metadata and kotlin_builtins from coreDependencies to fix IntelliJ symbol resolution

Exclude kotlin_metadata and kotlin_builtins

---

core/src/main/kotlin/plugability/DokkaContext.kt

Fix incorrect plugins paths when project is on a different filesystem than Gradle

Fix incorrect plugins paths 

---

core/src/main/kotlin/configuration.kt
core/src/main/kotlin/defaultConfiguration.kt
core/src/main/kotlin/plugability/DokkaPlugin.kt
runners/cli/src/main/kotlin/cli/main.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/configurationImplementations.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/main.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt
testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt

#638 
We have to be explicite with:
1. context
2. Dokka Plugin Type
3. Dokka Plugin Container Type
All the configuration for plugin is set up in context. We cannot obtain passed configs without context.
What's more it cannot be implicit in `DokkaPlugin()` because the context is nullable there, and probably will be null at the time of accessing the property, cause it's injected later. Also, we will probably feed configuration to Extensions, not `DokkaPlugin()` itself
It is crucial to distinct plugins. Unfortunatel, delegate's `thisRef` will most of the time be other that parent `DokkaPlugin()`
This is the most tricky part that probably could be skipped, but I spend few hours on research and have not found anything satisfying me. We need this type to know what type we want to project to. I …

Adds possibility to configure plugins

---

core/src/main/kotlin/pages/ContentNodes.kt
core/src/main/resources/dokka/styles/style.css
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt

Comments look like this:
Also some changes are related to the fact, that i wanted dokka to be the same as on figma (so the platform dependant tabs are brought down, and have more horizontal space)
On the 'mobile' or lower resolution screens it looks like this:

Platform dependant comments

---

core/src/main/kotlin/links/DRI.kt
core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/transformers/documentables/DefaultDocumentableMerger.kt
plugins/base/src/main/kotlin/transformers/documentables/DocumentableVisibilityFilter.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/basic/DRITest.kt
plugins/base/src/test/kotlin/markdown/LinkTest.kt
plugins/base/src/test/kotlin/model/ClassesTest.kt
plugins/base/src/test/kotlin/model/JavaTest.kt
plugins/build.gradle.kts
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt

- Added displaying generics on classes
- Added generics to Annotations
- Removed inherited types from inner classes (now there are only types that are declared by the inner class and not inherited from parent), just like it is in code
- Refactored DRI Target to use a sealed class instead of `int?`
- Added a reference to a point of declaration for types. So in case of:
```
class Outer<T> {
inner class Inner<G> {
fun foo(): T = { TODO() }
}
}
```
While user is on Inner class, link on the T return type forwards to Outer class.

Missing generics on class #834

---

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/basic/DRITest.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt
plugins/base/src/test/kotlin/markdown/LinkTest.kt
plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt
plugins/base/src/test/kotlin/renderers/html/SourceSetDependentHintTest.kt

The issue was that given a class without a package:
```
class Sample<S>{
inner class SampleInner {
fun foo(): S = TODO()
}
}
```
We would generate package name from a sourceRoot, but while creating a DRI for `foo`'s return type, the package would be empty. Then the location provider wouldn't be able to give a correct value so we end up with an empty `href` on frontend.

Return types links in inner classes with generic parents

---

plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt

I decided to drop the `SamplesTransformer` `ExternsionPoint` since it is yet another `PageTransformer`, but this way we can control proper plugins ordering, which is crucial for samples to be correctly interpolated,  before PageMerge.

Divergent comments fix

---

core/src/main/kotlin/DokkaException.kt
core/src/main/kotlin/DokkaGenerator.kt
core/src/main/kotlin/configuration.kt
core/src/main/kotlin/defaultConfiguration.kt
plugins/base/src/test/kotlin/basic/FailOnWarningTest.kt
plugins/base/src/test/kotlin/renderers/RenderingOnlyTestBase.kt
runners/cli/src/main/kotlin/cli/main.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/configurationImplementations.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt
testApi/src/main/kotlin/testApi/testRunner/DokkaTestGenerator.kt
testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt

Option to fail on warning

---

plugins/base/src/main/resources/dokka/styles/style.css

I think this was described in https://github.com/Kotlin/dokka/issues/998
Please use AWS to check if delays are fine for you. We can increase delay (even to the same level that is in copy icons == 1.2s), but that would result in multiple icons being rendered at the same time. Imo 0.5s is a decent point

Show anchors icon only on hover

---

plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt
plugins/gfm/src/main/kotlin/GfmPlugin.kt
plugins/gfm/src/test/kotlin/renderers/gfm/DivergentTest.kt
plugins/gfm/src/test/kotlin/renderers/gfm/SourceSetDependentHintTest.kt

What have been fixed:
- headers inside tables are now omitted
- styles are now properly rendered
- signatures in divergent now render only once
- some minor fixes

Minor style fixes for gfm signatures

---

core/src/main/kotlin/links/DRI.kt
core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/transformers/documentables/InheritorsExtractorTransformer.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/model/ClassesTest.kt
plugins/base/src/test/kotlin/model/JavaTest.kt
plugins/javadoc/src/main/kotlin/javadoc/signatures/JavadocSignatureProvider.kt
plugins/javadoc/src/main/resources/views/class.korte
plugins/javadoc/src/test/kotlin/javadoc/location/JavadocLocationTest.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt

Purpose of this PR is to have only first level of inheritance rendered. Also it includes a supertype type to reflect how it is represented in java via `extends/implements`. I took the level-based approach since it can be easily modified to render a inheritance tree in javadoc

Show only first level of inheritance

---

integration-tests/maven/src/integrationTest/kotlin/org/jetbrains/dokka/it/maven/MavenIntegrationTest.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Tested on https://github.com/Kotlin/kotlin-examples/tree/master/maven/dokka-maven-example
Remember to change version of `dokka.version` property to `0.11.0-SNAPSHOT` or whatever version of `0.11.0` you're using. Moreover, add following plugin repositories
```xml
<pluginRepository>
<id>jcenter-dokka</id>
<name>JCenterDokka</name>
<url>https://dl.bintray.com/kotlin/kotlin-dev/</url>
<releases>
<enabled>true</enabled>
</releases>
</pluginRepository>
<pluginRepository>
<id>jcenter-md</id>
<name>JCenterMd</name>
<url>https://dl.bintray.com/jetbrains/markdown/</url>
<releases>
<enabled>true</enabled>
</releases>
</pluginRepository>   
```

Fix javadoc rendering

---

plugins/mathjax/build.gradle.kts
plugins/mathjax/src/main/kotlin/MathjaxPlugin.kt
plugins/mathjax/src/test/kotlin/MathjaxPluginTest.kt

A simple tests that seems to show that MathjaxPlugin does not work. It does not seem insert the additional script resources.

Add a basic mathjax test

---

plugins/javadoc/src/main/kotlin/javadoc/signatures/JavadocSignatureProvider.kt
plugins/javadoc/src/main/resources/static_res/dokka-javadoc-stylesheet.css
plugins/javadoc/src/main/resources/views/class.korte
plugins/javadoc/src/main/resources/views/components/head.korte

This is quite sad since the bug is also present in javadoc (even for Java 14), so using custom styles in the only option here

Wrap superclasses in Javadoc

---

plugins/javadoc/src/main/kotlin/javadoc/location/JavadocLocationProvider.kt
plugins/javadoc/src/test/kotlin/javadoc/location/JavadocLocationTest.kt

The current file path looks like `/androidx.fragment.app/package-summary.html` which is non-standard. This CL changes the path to look like `/androidx/fragment/app/package-summary.html`.

Follow Javadoc file path convention

---

plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt
plugins/base/src/main/resources/dokka/styles/style.css

Small PR for low-hanging fruits like sorting in navigation pane on left and improving performance of CSS. 
I'd CSS to make it to RC.
You can check if samples still work on stdlib: `/kotlin-stdlib/kotlin-stdlib/kotlin.sequences/as-sequence.html`
I havn't found any sample that is in tab so here is a screen for our project:

Navigation pane improvements

---

README.md

Should be also cherry-picked to `1.4.0-rc`.

Remove mentions of kotlin-eap repo

---

core/src/main/kotlin/model/WithChildren.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/basic/FailOnWarningTest.kt
plugins/base/src/test/kotlin/signatures/ObviousTypeSkippingTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
test-tools/src/main/kotlin/matchers/content/ContentMatchersDsl.kt
test-tools/src/main/kotlin/matchers/content/contentMatchers.kt
testApi/src/main/kotlin/testApi/logger/TestLogger.kt
testApi/src/main/kotlin/testApi/testRunner/TestRunner.kt

Closes #1201 
This solves the trivial issue of redundant type information being displayed. Although while testing it I've found some nasty problems with signatures. Fix for those problems was embarrassingly easy, but I spent long hours trying to find a root cause. To prevent that in the future I've added an unreasonable number of tests for such a small fix.
Also, I've added a few utils for easier testing and easier debugging, that I cannot believe we had not had till now.

Remove redundant types

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/Bug1341.kt

Closes #1341
This is just a temporary workaround to mitigate the effect of this bug. A new ticket for the light classes subsystem will be created and tracked afterwards.
Shall track: https://youtrack.jetbrains.com/issue/KT-41234

Mitigate issue `Couldn't get delegate for class`

---

plugins/base/src/main/kotlin/parsers/MarkdownParser.kt

MarkdownParser should also output info about the unresolved link and its location. This however should be done properly when refactoring the parser 
Closes #1345

Make MarkdownParser output text instead of broken links

---

plugins/base/frontend/src/main/components/search/search.scss
plugins/base/src/main/resources/dokka/styles/style.css

This PR sets `cursor` style value to `pointer` for following buttons:
- Navigation drop-downs button
- Copy button
- Search button

Set cursor value to pointer for various buttons

---

runners/cli/src/main/kotlin/cli/main.kt

I don't know why, the previous solution was correctly resolving the file, but during serialization it used to lose sometimes correct location (while debuggin I observed `File` serializes to its path, which in case it was provided as relative path, it is serialized to one, which caused trouble while deserialization)
Of course I could change it to be `File(value).toAbsoulteFile()`, but I have more trust in `Paths` since it cooperates well on different OSes

Relative paths fix

---

core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/parsers/MarkdownParser.kt
plugins/base/src/main/kotlin/renderers/html/SearchbarDataInstaller.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt

Closes #1333
This PR also fixes a bug in `SearchbarDataInstaller` which had a race condition when used asynchronously from `HtmlRenderer`

Fix unstable ordering of methods

---

kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/EnvironmentAndFacade.kt
kotlin-analysis/src/main/kotlin/org/jetbrains/dokka/analysis/KotlinAnalysis.kt
plugins/base/src/main/kotlin/DokkaBase.kt

If someone uses just the dokka-analysis should not be forced into creating a dokka context only to pass configuration, sourcesets and logger

Remove dokka context from creating analysis

---

core/src/main/kotlin/model/defaultValues.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

```kotlin
class Complex(int: Int, string: String)
const val someConstVal = 1
val someValWithPrimitive = true
val someValWithComplexType = Complex(1, "")
fun someFunWithDefaults(int: Int = 1, string: String = "string") = 1
```

Add default values for primitive proprties. Add presenting in signature default values

---

core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt

260 lines are just tests
```kotlin
val n1: Function1<Int, String> = { _ -> "" }
val n2: (Int) -> String = { _ -> "" }
val n3: Boolean.(Int) -> String = { _ -> "" }
val n4: (param: Int) -> String = { _ -> "" }
val n5: suspend (Int) -> String = { _ -> "" }
val n6: suspend Boolean.(Int) -> String = { _ -> "" }
val n7: suspend (param: Int) -> String = { _ -> "" }
val n8: suspend (param1: suspend Boolean.(param2: List<Int>) -> Boolean) -> String = { _ -> "" }
```

Add better handling of functional types in rendered output

---

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/transformers/documentables/DeprecatedDocumentableFilterTransformer.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

By mistake, we forgot to process annotations for `typealiases` completetly.
Also fixes reported bug with not deprecating them.
```kotlin
@MustBeDocumented
@Target(AnnotationTarget.TYPEALIAS)
annotation class SomeAnnotation
@SomeAnnotation
@Deprecated(
message = "Replace with ImageRequest.",
replaceWith = ReplaceWith("ImageRequest", "coil.request.ImageRequest")
)
typealias GetRequest = Int
```

Add processing of annotations to typealiases

---

runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

When getting artifacts via aether for the plugins classpath,
set authentication on the remote repositories.
Without this, dokka fails if remote repositories require authentication.

Set aether authn when getting artifacts

---

integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/resolvers/local/DokkaLocationProvider.kt
plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js

Complete escape of the anchors since they are arbitrary values.
Anchors change from:
```
https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/index.html#kotlinx.serialization.json/JsonBuilder/isLenient/#/PointingToDeclaration/
```
To:
```
http://localhost:63342/kotlinx.serialization/build/dokka/htmlMultiModule/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/index.html#kotlinx.serialization.json%2FJsonBuilder%2FisLenient%2F%23%2FPointingToDeclaration%2F
```

Escape urls in anchors

---

core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/JavadocParser.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Note this descriptions probably can be easily overwriten with traditional dokka `includes`. The merging of these can be guaranteed by merging #1480 which depends on #1473 
```
/**
* Here comes my description for package via package-info
*/
package example;
```

Add parsing of package-info in java sources

---

integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
plugins/base/.gitignore
plugins/base/build.gradle.kts
plugins/base/frontend/package-lock.json
plugins/base/frontend/package.json
plugins/base/frontend/src/main/components/search/search.tsx
plugins/base/frontend/webpack.config.js
plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt

Motivation for that PR was the meeting with scala team, that faced an issue with not being able to override all styles. Also i thought it is weird that in order to override styles you need to modify 2 extension points so i've merged them into categories (styles, scripts and assets).

Render react resources as separate css to allow overriding

---

plugins/gfm/src/main/kotlin/GfmPlugin.kt

Works well while serving `dokka-example` with `markserv`

Add anchors for markdown

---

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

```
fun foo(vararg params: Int) { }
```

Fix vararg signatures

---

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt

```kotlin
open class A {
private val shouldBeHidden: Int = 1
val shouldBeVisible: Int = 2
private fun privateFun(): Int = 3
fun publicFun(): Int = 4
}
open class B : A()
open class C : B()
```

Hide derived members that are not public

---

plugins/base/frontend/src/main/components/navigationPaneSearch/navigationPaneSearch.tsx
plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt
plugins/base/src/test/kotlin/content/signatures/SkippingParenthesisForConstructorsTest.kt
plugins/base/src/test/kotlin/enums/EnumsTest.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt
plugins/base/src/test/kotlin/renderers/html/DivergentTest.kt
plugins/base/src/test/kotlin/signatures/DivergentSignatureTest.kt

Since i am waiting for the designer's answer i'd like to merge this PR and fix create another one with his feedback. 
Notable changes:
- description is below signature
- left navigation filter doesn't eagerly show results for empty input
- full documentation is rendered only on dedicated pages, on other only brief is rendered

Styles feedback

---

plugins/base/src/main/kotlin/translators/psi/JavadocParser.kt
plugins/base/src/test/kotlin/translators/JavadocParserTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/AbstractJavadocTemplateMapTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLinkingTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationTest.kt

I decided to do that in one PR, because fixes implementation depends on same code sections
```
/**
* Here comes some comment
*
* {@link example.SomeClassToLink#someFunc(int, Object) someName(ads,
* dsa)}
*
* longer comment
*/
public class SomeJavaDocExample {
}
```
```
/**
* <pre class="prettyprint">
* class MyFragment extends Fragment {
*   public MyFragment() {
*     super(R.layout.fragment_main);
*   }
* }
* </pre>
*/
```

Fix multiline links in javadoc and wrong linebreaking of <pre> bodies

---

plugins/base/src/main/kotlin/transformers/documentables/ModuleAndPackageDocumentationReader.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt
plugins/base/src/test/resources/linkable/includes/include11.md

This PR will not build until #1473 will be merged into master

Fix merging documentations of modules and packages

---

plugins/all-module-page/src/main/kotlin/templates/DirectiveBasedTemplateProcessing.kt
plugins/all-module-page/src/main/kotlin/templates/PathToRootSubstitutor.kt
plugins/base/src/main/kotlin/templating/Command.kt

Paths changed from absolute to more relative:
```
<a href="../../../kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization/index.html">serializer</a>
```
Also `pathToRoot` is now correct

Escape multimodule paths on windows

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt

There were changes of kind inheritance and tables coming from comments no longer have `ContentKind.Comment`, instead they have specific style `CommentTable` which is not checked in `HtmlRenderer` and due to that, tables in comments are parsed like blocks. This PR should fix that

Fix rendering of comment tables

---

core/src/main/kotlin/DokkaBootstrapImpl.kt
core/src/main/kotlin/configuration.kt
core/src/main/kotlin/defaultConfiguration.kt
core/src/main/kotlin/transformers/documentation/PreMergeDocumentableTransformer.kt
docs/src/doc/docs/user_guide/cli/usage.md
docs/src/doc/docs/user_guide/gradle/usage.md
docs/src/doc/docs/user_guide/maven/usage.md
plugins/base/src/main/kotlin/transformers/documentables/DeprecatedDocumentableFilterTransformer.kt
plugins/base/src/main/kotlin/transformers/documentables/DocumentableVisibilityFilterTransformer.kt
plugins/base/src/main/kotlin/transformers/documentables/ReportUndocumentedTransformer.kt
plugins/base/src/test/kotlin/filter/DeprecationFilterTest.kt
plugins/base/src/test/kotlin/transformers/ReportUndocumentedTransformerTest.kt
plugins/base/src/test/kotlin/transformers/SuppressedDocumentableFilterTransformerTest.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradlePackageOptionsBuilder.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Closes https://github.com/Kotlin/dokka/issues/593
This allows to match a package based on a regex and not only a prefix.
```
perPackageOption {
matchingRegex = ".*\\.internal"
suppress = true
}
```

Add matchingRegex

---

plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocClasslikeTemplateMapTest.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

Exclude top-level const val from generated getters

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css

I just discovered a dokka website in a friends pet project.
At the bottom right I saw this nice `Sponsored and developed by dokka ->` text.
I wanted to press at `dokka` but realized that only the arrow is clickable.
I guess it is a common pattern that "a text" is also linkend in such cases.
Therefore I moved the "dokka" text into the anchor as well. At least I hope so 😁 
I have never used `kotlinx.html` nor found a good documentation :( 
So I basically copied the `span` `text` thingy into the anchor tag. I hope this is working 😁 .
If not, sorry. Please guide me how to do it correctly 😇

Add dokka to GitHub link

---

buildSrc/src/main/kotlin/org/jetbrains/SetupMaven.kt
runners/maven-plugin/build.gradle.kts
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Use maven instead of aether to resolve additional dependencies. Aether is still used, but now indirectly by maven. Using maven directly allows to reuse all the configurations like repositories, mirrors, proxies and the local repository.
This fixes #1625 . A local test showed, that the additional dependencies like dokka-base, javadoc-plugin (and their dependencies) are downloaded correctly. If they are in the local repository already, now download is done again. This probably fixes #1408 as well.
**Note**: I've changed the code to only consider remote plugin repositories for downloading these artifacts, as this seems more correct - dokka-base/javadoc-plugin are in fact plugin dependencies and not project dependencies. This could be easily changed back, see comment.
I then removed the now …

Use maven directly to download additional dependencies

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/test/kotlin/renderers/html/BasicTest.kt
plugins/base/src/test/kotlin/renderers/html/HtmlRenderingOnlyTestBase.kt

Some test methods were dropped intentionally, as using them can lead to subtle bugs. The same methods are available in the base-test-utils module

Fix a bug with inserting template commands instead of link text

---

core/src/main/kotlin/model/Documentable.kt
core/src/main/kotlin/model/additionalExtras.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt
plugins/base/src/test/kotlin/model/annotations/JavaAnnotationsForParametersTest.kt
plugins/base/src/test/kotlin/model/annotations/KotlinAnnotationsForParametersTest.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureUtils.kt

Name `Annotatable` is up to discussion, i am not entirely happy with it

Annotations for parameters

---

runners/gradle-plugin/build.gradle.kts

Make Gradle plugin use `api` instead of `implementation` for core

---

docs/src/doc/docs/user_guide/cli/usage.md
docs/src/doc/docs/user_guide/gradle/usage.md
docs/src/doc/docs/user_guide/maven/usage.md
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/maven/projects/it-maven/pom.xml
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTaskPartial.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

I am wondering whether or not this should be in sourceset configuration. Technically you could have some sourcesets that you would like to show those functions....
@kamildoleglo ?

Fix configuration for suppressing obvious functions

---

docs/src/doc/docs/user_guide/gradle/usage.md

Fixes
- `".*\.internal.*"` -> `""".*\.internal.*"""` in "Configuration options" example (**in regular kotlin strings `\` is not allowed on its own**)
- `sourceRoot.from(...)` -> `sourceRoots.from(...)` in "Configuration options" example (**typo**)
- `url = ...` -> `url.set(...)` in "Configuration options" example (**works in groovy, but not in kotlin**)
- indention in "Kotlin Multiplatform plugin configuration" example (**typo**)

Fix several bugs in configuration examples in gradle user guide

---

docs/src/doc/docs/user_guide/versioning/versioning.md
plugins/versioning/api/versioning.api
plugins/versioning/src/main/kotlin/versioning/VersioningConfiguration.kt
plugins/versioning/src/main/kotlin/versioning/VersioningHandler.kt

Fixes #1889.  I'm not aware of a good Java globbing implementation (the JDK one doesn't use base directories) unless you already have a dependency for one.  If you do I can add a setter method.
The older version directory's subfolders and the older versions list are added together, so either or both can be specified.  I don't love the `olderVersions` name but I couldn't think of a better one.  `additionalOlderVersions` maybe?

Add ability to specify older versions as a list of files

---

plugins/base/src/main/kotlin/parsers/MarkdownParser.kt
plugins/base/src/test/kotlin/parsers/ParseModuleAndPackageDocumentationFragmentsTest.kt
plugins/base/src/test/kotlin/transformers/ContextModuleAndPackageDocumentationReaderTest1.kt

Simple fix for #1884 and #1883, just replaces CRLF line separators with LF before markdown parsing.  Ideally this should be fixed in the parser, but this works for now.
Also adds a test for this.
For GitHub:
Fixes #1883
Fixes #1884

Fix line separator issues

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt

Fix preserving spaces in Javadoc comments

---

plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt
plugins/gfm/src/test/kotlin/renderers/gfm/DivergentTest.kt
plugins/gfm/src/test/kotlin/renderers/gfm/GroupWrappingTest.kt
plugins/gfm/src/test/kotlin/renderers/gfm/SimpleElementsTest.kt
plugins/gfm/src/test/kotlin/renderers/gfm/SourceSetDependentHintTest.kt

Cleanup work for line and paragraph ends in rendered GFM, from current bloody mess to (almost) ideomatic markdown.
If accepted - more cleanups will follow.
Ready for review and merge.

GFM renderer: sanitize line ends

---

plugins/jekyll/src/main/kotlin/JekyllPlugin.kt

Dokka 1.4.32
The use of `dokkaJekyll` task adds a final `dash` to every title in the header like:
```
---
title: Const -
---
```
Remove the extra dash.

[Jekyll Plugin] Remove extra dash

---

core/src/main/kotlin/Formats/KotlinWebsiteHtmlFormatService.kt
core/src/main/kotlin/Formats/StructuredFormatService.kt

* For signatures declared in a single location only `(source)` hyperlink is added.
* For builtins (common, jvm, js take from `kotlin/core/builtins` while k/n has separate implementation) `(Common source) (Native source)` hyperlinks are added.
* For multiplatform declarations with `expect/actual` `(Common source) (JVM source) (JS source) (Native source)` hyperlinks are added.
* For signatures declared in multiple platform, e.g. JVM and Native, `(JVM source) (Native source)` hyperlinks are added.
The hyperlinks follow the signature, thus often make the signature line very long. Maybe adding the hyperlinks in a separate line or even in a separate section might be better. Another approach is to add hyperlinks to signature platform tags.

Implement url to multiple sources

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/gradleConfigurations.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/main.kt

Default dependency to dokka-base in dokkaPluginConfiguration was changed to a regular dependency. Applying client-side plugins overrode the default dokka-base dependency thus changing the version to a (possibly) lower one. This could lead to unpredictable Dokka crashes due to the inconsistency between the Gradle runner and dokka-base versions. Dependencies can still be manually removed from the configuration in specific projects, if needed (not likely)

Fix Gradle plugin application

---

plugins/base/api/base.api
plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/gfm/api/gfm.api
plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt

Minor patch closing GFM cleanup series
Just renames two functions, for consistency and reduce confusion probability.

Minor: rename `buildNewLine`

---

core/api/core.api
core/src/main/kotlin/model/additionalExtras.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt
plugins/base/src/test/kotlin/model/FunctionsTest.kt

I have added new types for ```int```, ```long```, ```float```, ```double``` annotation parameter value. 
I do not know do i need to add  ```boolean``` type or ```null``` value.
The PR is linked to #1950.

Add numeric types of annotation parameter value

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/content/receiver/ContentForReceiverTest.kt

In fact they were not "missing" but just were displayed with parameters. Caveat was that when function had no parameters then the receiver also was not displayed. I've changed it to be present as normal tag since i don't think that presenting it as in the compiled code is the way to go

Missing receiver docs

---

core/api/core.api
core/src/main/kotlin/model/additionalExtras.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/utils/contentUtils.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocClasslikeTemplateMapTest.kt

According to  #2015:
1. omit parentheses if there are no parameters 
2. add quotes for string literals into annotations

Improve annotations rendering

---

plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt

Fixes #2088
After experimenting while looking into #2088, I found what appears to be a solution (at least for my use case), so I figured I'd make a PR just in case this is a reasonable general solution as well. The change is small, we simple do not wrap the value of `{@literal @}` in a code tag, as I believe the semantics of it do not require that (it can itself be wrapped in `pre` or `code`) and among other things, it makes formatting examples of annotations in doc strings difficult.
I've run my simple example from the last test in the PR with a few different versions of Dokka for comparison.

Don't force @literal in javadoc to be surrounded by code tag

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt

the issue was that `SymbolAnchorHint` extra was leaking into the children therefore an anchor was generated in html with broke merging of entries in divergent. 
the difference is visible on stdlib, you can compare it with current master: http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/stdlib/88ff6bd/kotlin-stdlib/kotlin/index.html
Please note that some descriptions won't be collapsed into tabs before they contain sourceset specific link, an example of that is `Any`

Bring back merging of divergent entries

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt

Compare [previous state](https://user-images.githubusercontent.com/15652452/133392491-00d38ea2-7e10-4d79-8fa8-70ca7b4ad876.png) with:
- i've removed the `#` as this is just for sake of referencing a method and should not be displayed
- changed the way it is displayed to match other contents

Make see tag display as other tables

---

plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt

JDK Javadoc replaces breaklines inside `@link` tag on whitespaces.

Fix whitespaces inside `@link` tag

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/functions/ContentForConstructors.kt

http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/stdlib/f7db503/kotlin-stdlib/kotlin.coroutines.intrinsics/index.html
Names of Constructors are not breakable.

Fix css bugs wih link and table row

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css

Fixes [KT-50296](https://youtrack.jetbrains.com/issue/KT-50296)

Add horizontal margin to breadcrumbs delimiter (KT-50296)

---

plugins/base/src/main/resources/dokka/styles/style.css

Before, the indentation for a package element with children came from the button itself (it physically occupied 24px). Now there's real and consistent indentation for all tree elements, regardless of any buttons

Add a level of indentation to childless items in navigation tree (KT-50294)

---

docs/src/doc/docs/user_guide/gradle/usage.md

File#resolve(String) doen't exist in Groovy

Fix wrong Groovy DSL example

---

docs/src/doc/docs/user_guide/gradle/usage.md

Add a note about usage in a precompiled script plugin

---

plugins/base/api/base.api
plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultExternalDocumentablesProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/ExternalClasslikesTranslator.kt
plugins/base/src/main/kotlin/translators/descriptors/ExternalDocumentablesProvider.kt
plugins/base/src/test/kotlin/translators/ExternalDocumentables.kt
plugins/base/src/test/kotlin/translators/ExternalDocumentablesTest.kt

There are some cases when there is a need to process documentables of classlikes that were not defined in the project itself but are supertypes of classlikes defined in the documented project. This pr adds a simple service that can be accessed via
```kotlin
context.plugin<DokkaBase>().querySingle { externalDocumentablesProvider }
```
and then queried with DRI and source set to obtain a documentable.
Currently, it supports obtaining only DClasslikes, as I cannot see any use case for wanting to obtain documentables for external members or packages. Nevertheless, if the need arise one can add a new, more general interface without breaking backward compatibility.

Add external documentable provider

---

core/src/main/kotlin/links/DRI.kt

Accidentally came across this. I don't think it's very performance critical, but it's recommended and usually is reused (common practice)
As per [documentation](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#basics-things-you-should-do-anyway),
> There are some basic ground rules to follow to ensure that Jackson processes things efficiently (close to optimal level). These are things that you should "do anyway", even if you do not have actual performance problems ...
> 1. Reuse heavy-weight objects: ObjectMapper (data-binding) ...
> ...

Reuse `ObjectMapper`

---

core/api/core.api
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/api/base.api
plugins/base/base-test-utils/api/base-test-utils.api
plugins/base/base-test-utils/src/main/kotlin/renderers/JsoupUtils.kt
plugins/base/base-test-utils/src/main/kotlin/renderers/SignatureUtils.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/signatures/SkippingParenthesisForConstructorsTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/utils/contentUtils.kt
plugins/javadoc/api/javadoc.api
plugins/kotlin-as-java/api/kotlin-as-java.api
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

Do tell me if you'd like to see screenshots of before/after

KT-50292 - Implement vertical alignment of parameter

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Fix #2330 by reading annotations on the package statement of the `package-info.java` file which was already parsed for doc comments in `DefaultPsiToDocumentableTransformer.parsePackage`.

Collect annotations from package-info.java

---

plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt

Partially fixes https://github.com/Kotlin/dokka/issues/2262#issuecomment-1030359358

Add support for header tags in Javadoc

---

core/src/main/kotlin/plugability/DokkaContext.kt

A potential fix for a problem that suppressing extensions was breaking the dokka run. I hope I will manage to cover it with some tests.

Fix filtering suppresed extensions

---

core/api/core.api
core/src/main/kotlin/pages/PageNodes.kt
core/src/main/kotlin/pages/Pages.kt
docs/src/doc/docs/user_guide/base-specific/frontend.md
integration-tests/gradle/projects/stdlib/stdlib.diff
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/StdlibGradleIntegrationTest.kt
integration-tests/src/main/kotlin/org/jetbrains/dokka/it/AbstractIntegrationTest.kt
plugins/base/api/base.api
plugins/base/base-test-utils/api/base-test-utils.api
plugins/base/base-test-utils/src/main/kotlin/renderers/TestPage.kt
plugins/base/src/main/kotlin/DokkaBaseConfiguration.kt
plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt
plugins/base/src/main/kotlin/transformers/pages/merger/SameMethodNamePageMergerStrategy.kt
plugins/base/src/main/kotlin/transformers/pages/samples/SamplesTransformer.kt
plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
plugins/base/src/test/kotlin/content/functions/ContentForBriefTest.kt
plugins/base/src/test/kotlin/content/functions/ContentForConstructors.kt
plugins/base/src/test/kotlin/locationProvider/DokkaLocationProviderTest.kt
plugins/base/src/test/kotlin/transformers/MergeImplicitExpectActualDeclarationsTest.kt
plugins/javadoc/api/javadoc.api
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/JavadocPageCreator.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/JavadocPageNodes.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt
plugins/mathjax/src/main/kotlin/MathjaxPlugin.kt

TODO:
1) Source link should be moved in signatures
2) For properties - grouping by description

Add option to merge implicit expect-actual declarations

---

plugins/all-modules-page/api/all-modules-page.api
plugins/all-modules-page/src/main/kotlin/ResolveLinkCommandHandler.kt
plugins/base/api/base.api
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/renderers/html/Tags.kt
plugins/base/src/main/kotlin/renderers/html/command/consumers/ReplaceVersionsConsumer.kt
plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt
plugins/templating/api/templating.api
plugins/templating/src/main/kotlin/templates/AddToNavigationCommandHandler.kt
plugins/templating/src/main/kotlin/templates/CommandHandler.kt
plugins/templating/src/main/kotlin/templates/DirectiveBasedTemplateProcessing.kt
plugins/templating/src/main/kotlin/templates/ReplaceVersionCommandHandler.kt
plugins/templating/src/main/kotlin/templates/SubstitutionCommandHandler.kt
plugins/templating/src/main/kotlin/templates/TemplateProcessor.kt
plugins/templating/src/main/kotlin/templates/TemplatingPlugin.kt
plugins/templating/src/test/kotlin/templates/SubstitutionCommandResolutionTest.kt
plugins/versioning/api/versioning.api
plugins/versioning/src/main/kotlin/versioning/ReplaceVersionsCommand.kt

`Jsoup` can not process custom html tags inside head block so template commands are kept as html comments

Fix HTML head and favicon in multi-module projects

---

.github/workflows/gh-pages.yml
CONTRIBUTING.md
build.gradle.kts
buildSrc/src/main/kotlin/org/jetbrains/DokkaPublicationChannel.kt
buildSrc/src/main/kotlin/org/jetbrains/DokkaVersion.kt
buildSrc/src/main/kotlin/org/jetbrains/DokkaVersionType.kt
buildSrc/src/main/kotlin/org/jetbrains/ValidatePublications.kt
buildSrc/src/main/kotlin/org/jetbrains/publication.kt
gradle.properties

Unable to change dokka's version to RC without these changes, it'll fail build locally then.
* Added `RC` version type
* Removed `MC` version type as it seems to be unused (will revert if it's really needed for something)
* Added `gradle-plugin-portal` as a publication channel (only `RELEASE` and `RC` are allowed)
* Removed `dokka_version_base` in favour of `dokka_version`. Base version seems unused now, as TC passes value directly to `dokka_version` and automatically adding `-SNAPSHOT` is not that big of a deal, it'll be present by default anyway.
* Reverted condition for version check (now off by default, needs to by enabled by setting `ENABLE_VERSION_CHECK` to `true`)
I've also updated TeamCity publish configuration and added `env.ENABLE_VERSION_CHECK = true` and also added an `RC` …

Minor refactoring of dokka versioning and publishing

---

core/api/core.api
core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

Rework AnnotationTarget to be stricter. Now the things that can be annotated are precisely the things which implement AnnotationTarget.
Also adds tests, though they currently don't do anything because of pre-existing bugs
This replaces github.com/Kotlin/dokka/pull/2210. I believe all the commends from that PR are addressed.
This is based on our desire to have PrimitiveJavaObject 
The two things that I think are bugs that limits the effectiveness of the tests:
1. Even after this change, `UnresolvedType` will not be annotable.
To allow that to happen would require a change in `org.jetbrains.kotlin.types.ErrorType` and `.UnresolvedType` to take and use an `annotations` parameter rather than explicitly override the class property it to empty, and then for that parameter to be backpropagated …

Rework AnnotationTarget to be stricter.

---

docs/build.gradle.kts

Currently documentation generation fails, this update fixes https://github.com/xvik/gradle-mkdocs-plugin/issues/29

Update mkdocs gradle plugin to fix documentation generation

---

core/src/main/kotlin/defaultExternalLinks.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt

Fix missing external docs for some AndroidX libraries

---

runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

The default (`true`) works fine for gradle, but fails for maven for some reason.
See https://github.com/Kotlin/dokka/issues/2457

Set `finalizeCoroutines` to false for maven runner

---

CONTRIBUTING.md
README.md
docs/src/doc/docs/community/plugins-list.md
docs/src/doc/docs/user_guide/base-specific/frontend.md
docs/src/doc/docs/user_guide/cli/usage.md
docs/src/doc/docs/user_guide/gradle/usage.md
examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-multimodule-example/settings.gradle.kts
examples/gradle/dokka-multiplatform-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/parentProject/build.gradle.kts
examples/maven/pom.xml
integration-tests/gradle/projects/it-android-0/gradle.properties
integration-tests/gradle/projects/it-basic-groovy/gradle.properties
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/gradle/projects/it-basic/gradle.properties
integration-tests/gradle/projects/it-collector-0/gradle.properties
integration-tests/gradle/projects/it-js-ir-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-1/gradle.properties
integration-tests/gradle/projects/it-multimodule-versioning-0/gradle.properties
integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
integration-tests/maven/projects/it-maven/pom.xml

Might take some time for artifacts to be available for the GH action agents

Update documentation and examples to Dokka 1.6.21

---

plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt
plugins/base/src/main/kotlin/transformers/documentables/DocumentableVisibilityFilterTransformer.kt
plugins/base/src/test/kotlin/enums/EnumsTest.kt

Fixes #2466
Before
* ordered by name in navigation,
* reversed order on the enum page
Now - same order as in source, both for navigation and the enum page
For class
```kotlin
/**
* Selects whether to correct for atmospheric refraction, and if so, how.
*/
enum class Refraction(s: String = "EMPTY") {
EMPTY,
/**
* No atmospheric refraction correction (airless).
*/
None("Hello"),
/**
* Recommended correction for standard atmospheric refraction.
*/
Normal("World"),
/**
* Used only for compatibility testing with JPL Horizons online tool.
*/
JplHor("GitHub"),
}
```

Fix reversed ordering of enum entries

---

core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt
plugins/all-modules-page/src/test/kotlin/templates/MultiModuleDocumentationTest.kt
plugins/all-modules-page/src/test/kotlin/templates/ResolveLinkCommandResolutionTest.kt
plugins/all-modules-page/src/test/kotlin/templates/ResolveLinkGfmCommandResolutionTest.kt
plugins/templating/src/test/kotlin/templates/AddToNavigationCommandResolutionTest.kt
plugins/templating/src/test/kotlin/templates/AddToSearchCommandResolutionTest.kt
plugins/templating/src/test/kotlin/templates/SubstitutionCommandResolutionTest.kt

This annoying file used to appear whenever you ran tests
https://github.com/Kotlin/dokka/pull/2474/files/cf02a243237306930a7f6d149c43126699b33be6#diff-5b3183ca422abbdc8f2db7e6fd54b5b7d18a40d54c543db3e47b714698a9dc26

Fix suddenly appearing all-modules-page/index.md file

---

core/api/core.api
core/src/main/kotlin/model/defaultValues.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/model/FunctionsTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

In StdLib there are many cases when arguments of actual functions have default values.
See https://github.com/JetBrains/kotlin/search?q=ACTUAL_FUNCTION_WITH_DEFAULT_ARGUMENTS

Make a default value dependent on source set

---

plugins/javadoc/api/javadoc.api
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/JavadocPageNodes.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/JavadocContentToTemplateMapTranslator.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocDeprecatedTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocIndexTest.kt

https://youtrack.jetbrains.com/issue/KT-52069

Make javadoc pages generation deterministic

---

plugins/base/api/base.api
plugins/base/src/main/kotlin/transformers/documentables/DeprecatedDocumentableFilterTransformer.kt
plugins/base/src/test/kotlin/filter/DeprecationFilterTest.kt

Fixes #2484 
To avoid copy-paste, changed it to be a `SuppressedByConditionDocumentableFilterTransformer`, it contains the same exact logic that iterates through all of the documentables.
It should also be a bit faster now since it first checks for deprecated annotations and only then fetches package options, whereas before it checked for deprecation as the very last step, doing a lot of useless operations beforehand and not using the results

Skip @Deprecated documentables with HIDDEN level

---

plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/htmlPreprocessors.kt

Leftover review comment from #2479

Refactor to utilize Comparators instead of String keys

---

core/api/core.api
core/src/main/kotlin/pages/ContentNodes.kt
gradle.properties
plugins/base/base-test-utils/api/base-test-utils.api
plugins/base/base-test-utils/src/main/kotlin/renderers/JsoupUtils.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/renderers/html/TextStylesTest.kt
plugins/base/src/test/kotlin/transformers/CommentsToContentConverterTest.kt

This is not 100% done yet, I still want to make some changes to the styling and add some tests (as @IgnatBeresnev requested).
Blockquotes are being rendered though.
(this is my first PR to dokka, so please tell me if i'm doing something wrong without realizing it)
```
/**
* > Matches 0 or 1 of the preceding token, effectively making it optional.
*/ 
```
Closes #2491

Render quotes as blockquotes instead of code blocks.

---

core/api/core.api
core/src/main/kotlin/model/additionalExtras.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/enums/EnumsTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

Enum constructor arguments is mostly internal detail of enums that
isn't supposed to be exposed to clients of some library so let's
don't put it in the generated documentations result.
As https://github.com/Kotlin/dokka/issues/2468#issuecomment-1125162625
Fixes #2468 
Hopefully is in a correct direction, it passes the test suit I can say and even though a test is removed there is another test that practices the new behavior.

Don't expose enum constructor arguments to documentations

---

integration-tests/cli/src/integrationTest/kotlin/org/jetbrains/dokka/it/cli/CliIntegrationTest.kt
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleCachingIntegrationTest.kt

Unfortunately I still don't have a fully working build on Windows, but this does address some of the issues I've seen.

Fix some tests on Windows

---

plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

This PR fixes the problem described [here](https://github.com/Kotlin/dokka/issues/2492). Please take a look at the issue before moving on.
The `DFunction` successfully collected information about the access modifier, but this information was not considered when generating/rendering output.
Additionally, a few of the `kotlin-as-java` plugin tests required modification. These tests failed as they expected no access modifiers for public functions in the output.

Make the `kotlin-as-java` plugin include information about access modifiers for functions

---

core/api/core.api
core/src/main/kotlin/model/Documentable.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt
plugins/base/src/main/kotlin/transformers/documentables/ExtensionExtractorTransformer.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/utils/TestUtils.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/signatures/JavadocSignatureProvider.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaSignatureTest.kt

[definitely non-nullable types](https://github.com/Kotlin/KEEP/blob/c72601cf35c1e95a541bb4b230edb474a6d1d1a8/proposals/definitely-non-nullable-types.md) are enabled since Kotlin 1.7

Support definitely non-nullable types

---

integration-tests/cli/build.gradle.kts
integration-tests/gradle/projects/it-basic/build.gradle.kts
plugins/all-modules-page/build.gradle.kts
plugins/base/build.gradle.kts
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/javadoc/build.gradle.kts
plugins/kotlin-as-java/build.gradle.kts
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaArtifacts.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/gradleConfigurations.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Otherwise we had incompatibility with Kotlin compiler from Gradle in buildscript dependencies.

Make `dokka-analysis` dependency compileOnly in base plugin

---

gradle.properties

Jackson version is out of date and has `CVE-2020-36518` vuln

Bump Jackson version to 2.13

---

gradle.properties

Jackson was bumped to 2.13 in #2525, but support for Kotlin 1.4 is broken in that version (https://github.com/FasterXML/jackson-module-kotlin/issues/556)
Downgraded to [2.12.7](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.7), which should still contain the CVE fix.
Integration tests were not run for the previous PR, will fix it to not hit it again

Downgrade Jackson due to broken 1.4 support

---

plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt
plugins/gfm/src/test/kotlin/renderers/gfm/CodeWrappingTest.kt

Previously it generated trailing slashes for newlines inside code blocks + performed `htmlEscape()` on code text, which resulted in something like this:
___
Completion of an *active* coroutine's body or a call to CompletableJob.complete transitions the job to the *completing* state. It waits in the *completing* state for all its children to complete before transitioning to the *completed* state. Note that *completing* state is purely internal to the job. For an outside observer a *completing* job is still active, while internally it is waiting for its children.
```kotlin
wait children\
+-----+ start  +--------+ complete   +-------------+  finish  +-----------+\
| New | -----&gt; | Active | ---------&gt; | Completing  | -------&gt; | Completed |\
+-----+        +--------+ …
```

Dont escape text inside gfm code blocks

---

core/api/core.api
core/src/main/kotlin/model/documentableProperties.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/InheritedAccessorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/superFields/DescriptorSuperPropertiesTest.kt
plugins/base/src/test/kotlin/superFields/PsiSuperFieldsTest.kt
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Fix incorrectly labeling java properties as val/var

---

runners/gradle-plugin/build.gradle.kts
runners/gradle-plugin/gradle.properties

Because Gradle will put its own Kotlin stdlib in the classpath, it's no use adding it as a transitive dependency. It might even cause compilation errors.
See https://kotlinlang.slack.com/archives/C0F4UNJET/p1655743911527999

Do not expose kotlin stdlib in the Gradle plugin dependencies

---

plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt
plugins/base/src/test/kotlin/enums/EnumsTest.kt
plugins/base/src/test/kotlin/enums/KotlinEnumTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocIndexTest.kt

Previously `values` and `valueOf` enum functions were not present in the documentable model
Even though we skip obvious members for our formats, other plugins might want to use it

Add enum synthetic functions to documentable model

---

core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt
plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt
plugins/base/src/test/kotlin/enums/JavaEnumsTest.kt
plugins/base/src/test/kotlin/enums/KotlinEnumsTest.kt

Do not generate source links for synthetic elements

---

plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/utils/NoopIntellijLogger.kt

If there ever is a developer/debug mode, it should NOT ignore the messages if in this mode so that we can use it during testing and development. I've written it down
Fixes #2559

Ignore messages emitted by the IntelliJ Logger

---

CONTRIBUTING.md
README.md
build.gradle.kts
docs/src/doc/docs/community/plugins-list.md
docs/src/doc/docs/developer_guide/workflow.md
docs/src/doc/docs/user_guide/applying/cli.md
docs/src/doc/docs/user_guide/applying/gradle.md
examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-multimodule-example/settings.gradle.kts
examples/gradle/dokka-multiplatform-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/parentProject/build.gradle.kts
examples/maven/pom.xml
examples/plugin/hide-internal-api/build.gradle.kts
examples/plugin/hide-internal-api/gradle.properties
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt

This is for **master**, and this cannot be cherry picked into the release `1.7.10` branch, so there will be a separate PR for that

Update references and documentation to Dokka 1.7.10

---

runners/gradle-plugin/build.gradle.kts

Follow up from https://github.com/Kotlin/dokka/pull/2543
See also [this kotlinlang slack discussion](https://kotlinlang.slack.com/archives/C19FD9681/p1656593570021959)
Looks like the "com.gradle.plugin-publish" creates its own pom that doesn't find "configuration-level" excludes but requires "dependency-level" exclude. This PR mimics the behaviour from the Kotlin Gradle Plugin. It's hard to test end to end, especially since "com.gradle.plugin-publish" is closed source but I could verify that the file at `dokka/runners/gradle-plugin/build/publish-generated-resources/pom.xml` now contains excludes 🤞

Another take at removing the kotlin-stdlib dependency from the Gradle Plugin

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/utils/contentUtils.kt

Replace package name on cover with "Package-level declarations"

---

plugins/base/src/main/resources/dokka/scripts/navigation-loader.js

See https://github.com/Kotlin/dokka/issues/2576

Add auto-scrolling to selected navigation item on page load

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/InheritedAccessorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/signatures/VarianceSignatureTest.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaSignatureTest.kt

Copy button itself and the script for it are still present for two scenarios:
* Copying anchor links
* Copying contents of code blocks. These are usually usage examples, so I think it could be useful
See https://github.com/Kotlin/dokka/issues/2576

Disable copy button for signatures

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/renderers/html/BreadcrumbsTest.kt

Live demo: https://ignatberesnev.github.io/static/dokka/breadcrumbs/index.html

Make current breadcrumb element not clickable and of default font color

---

core/api/core.api
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/api/base.api
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/enums/JavaEnumsTest.kt
plugins/base/src/test/kotlin/enums/KotlinEnumsTest.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt

Move source links into signature

---

core/api/core.api
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/pages/tags/SinceKotlinTagContentProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt

See https://github.com/Kotlin/dokka/issues/2576
* Now all KDoc tag sections should look the same, including throws/see/parameters
* Decreased space between tag header and values
* Fixed a problem where longer link text had many word breaks:
* See/Throws link text is now just the class name (if DRI is resolved), full path if unresolved; previously always full path
* Increased first column width for See/Throws/Parameters a bit.
* (I have a complete JS script to dynamically adjust the width of the first column based on link width, will discuss it during sync and maybe file it as another PR)

Apply the same style to all KDoc tags, including throws/see/parameters

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/signatures/AbstractRenderingTest.kt
plugins/base/src/test/kotlin/signatures/DivergentSignatureTest.kt
plugins/base/src/test/kotlin/signatures/RawHtmlRenderingTest.kt

Fix spelling error 'depenent'

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/styles/style.css

See #2576
It should now visually look the same as on kotlinlang.org, for instance like on [this page](https://kotlinlang.org/docs/getting-started.html#create-your-powerful-application-with-kotlin)
Changing only platform tabs made it inconsistent with section tabs, so I changed section tabs as well
Live demo: https://ignatberesnev.github.io/static/dokka/kotlinlang-tabs/index.html

Style section and platform tabs like on kotlinlang.org

---

plugins/base/src/main/kotlin/renderers/html/NavigationDataProvider.kt
plugins/base/src/main/kotlin/renderers/html/NavigationPage.kt
plugins/base/src/test/kotlin/renderers/html/NavigationIconTest.kt
plugins/base/src/test/kotlin/renderers/html/NavigationTest.kt
plugins/base/src/test/kotlin/utils/HtmlUtils.kt

Render nested classlikes in navigation

---

core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/api/base.api
plugins/base/src/main/kotlin/renderers/DefaultRenderer.kt
plugins/base/src/main/kotlin/renderers/html/HtmlContent.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/pages/merger/SameMethodNamePageMergerStrategy.kt
plugins/base/src/main/resources/dokka/styles/style.css

By far not the best solution, but I found no other _reliable_ way to add a divider for function overloads especially considering different sourcesets. This adds no new public API, so I think it's not a big deal - will probably have to redesign this down the road anyway. 
See https://github.com/Kotlin/dokka/issues/2576
___

Add a distinct divider between function overloads

---

plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js
plugins/base/src/main/resources/dokka/templates/base.ftl

Closes #2591
I tried to implement what mentioned in the issue:
> I think if you open up Dokka for the first time, it could choose light/dark mode based on OS theme, and then if the person decides to switch it to something else - remember that choice.

Use OS color scheme to init light/dark mode (#2591)

---

core/api/core.api
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/base-test-utils/api/base-test-utils.api
plugins/base/base-test-utils/src/main/kotlin/renderers/JsoupUtils.kt
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt
plugins/base/src/main/kotlin/translators/psi/parsers/JavadocParser.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt
plugins/base/src/test/kotlin/renderers/html/TextStylesTest.kt

Add support for proper rendering `<var>` in Java sources. Not it's rendering as `<var>` HTML tag as for Kotlin.
Fix #2358

Support of var html tag for Javadoc

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Display values of java constants

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

This is regression from https://github.com/Kotlin/dokka/pull/2593. Completely forgot about `Byte`, `Short` and `Char`.
It was also displayed fine (resolved `StringValue` by default), but the returned type was incorrect.

Add missing java primitives to annotation constant params parsing

---

examples/gradle/dokka-customFormat-example/README.md
examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-customFormat-example/logo-styles.css

Seems like it had styles of pre-1.6 Dokka. 
Fixes #2605
Not sure how it looked before, but now it looks like this:

Update dokka-customFormat-example to use up-to-date logo styles

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/model/JavaTest.kt

It caused flaky generation of type links for generic type params  (#2596)

Fix generic types caching

---

core/api/core.api
core/content-matcher-test-utils/api/content-matcher-test-utils.api
core/content-matcher-test-utils/src/main/kotlin/matchers/content/ContentMatchersDsl.kt
core/src/main/kotlin/pages/ContentNodes.kt
plugins/base/api/base.api
plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/renderers/html/NavigationDataProvider.kt
plugins/base/src/main/kotlin/renderers/html/NavigationPage.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt
plugins/base/src/main/kotlin/transformers/documentables/utils.kt
plugins/base/src/main/kotlin/transformers/pages/merger/SameMethodNamePageMergerStrategy.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/translators/documentables/DeprecationSectionCreator.kt
plugins/base/src/main/kotlin/translators/documentables/PageContentBuilder.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/annotations/JavaDeprecatedTest.kt
plugins/base/src/test/kotlin/content/annotations/KotlinDeprecatedTest.kt
plugins/base/src/test/kotlin/content/annotations/SinceKotlinTest.kt
plugins/base/src/test/kotlin/renderers/html/NavigationTest.kt
plugins/base/src/test/kotlin/utils/contentUtils.kt
plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/renderer/CommonmarkRenderer.kt
plugins/javadoc/api/javadoc.api
plugins/kotlin-as-java/api/kotlin-as-java.api
plugins/kotlin-as-java/src/main/kotlin/signatures/JavaSignatureProvider.kt

* Deprecation details on pages, both for Kotlin and Java `Deprecated` annotations
* Strikethrough only declaration names and not for the whole signature as before (so should only be class name, function name, etc)
* Add text strikethrough for navigation pages where all documentables are deprecated (all and in all source sets)
* Integrate `@DeprecatedSinceKotlin` into the block
* Deprecated declarations are always last on the merged pages, but not on package overview page (as it's sorted by name)
Part of #2576

Add deprecation details block to pages and strike such pages in navigation

---

plugins/base/src/main/kotlin/parsers/MarkdownParser.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt

Fix incorrect handling of static members used within `@see` tag

---

plugins/base/frontend/src/main/components/search/dokkaSearchAnchor.tsx
plugins/base/frontend/src/main/components/search/search.scss
plugins/base/frontend/src/main/components/search/search.tsx
plugins/base/frontend/src/main/components/search/types.ts
plugins/base/frontend/src/main/components/utils/hotkey.ts
plugins/base/frontend/src/main/components/utils/os.ts
plugins/base/frontend/src/main/types/@jetbrains/index.d.ts

Add a `Cmd + K`/`Ctrl + K` hotkey for opening the search window.
* Meta key `Cmd`/`Ctrl` depends on OS. For macOS -- `Cmd`, for every other -- `Ctrl`.
* The search button have a tooltip with the name of key combination. The tooltip appears after 500 ms on mouse over.
* The combination prevents default hotkey actions like the kotlinlang.org or github.com behave. E.g. the `Cmd+K` combination is default option to focus on the omnibox in Firefox.
* Tested on Chrome/Filefox/Safary on macOS, on Edge/Firefox on Windows
Fix #2265

Add hotkey for opening search dialog

---

plugins/base/src/main/resources/dokka/styles/style.css

See #2576
Apparently, when adding more styles for code blocks, it was simply forgotten that copy button is used for anchors too

Fix anchor copy button popup

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/content/signatures/ConstructorsSignaturesTest.kt

See #2576
TBD what to do with primary constructors

Do not render constructor pages and blocks and for annotation classes

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Handle `PsiImmediateClassType` as `PsiClassType` to resolve bounds

---

plugins/base/src/main/kotlin/renderers/html/SearchbarDataInstaller.kt

Fix search bar to exclude `(source)`

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt
plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt
plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
plugins/base/src/main/resources/dokka/scripts/symbol-parameters-wrapper_deferred.js
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

Wrap long signatures dynamically based on taken client width

---

plugins/base/src/main/kotlin/parsers/MarkdownParser.kt
plugins/base/src/test/kotlin/markdown/ParserTest.kt
plugins/base/src/test/kotlin/model/CommentTest.kt
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt

By [CommonMark spec](https://spec.commonmark.org/0.30/#indented-code-blocks), we should omit 4 spaces of indentation.
It should be fixed in IDEA as well:

Trim four-spaces inside indented code block

---

integration-tests/gradle/projects/it-multiplatform-0/build.gradle.kts
integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
integration-tests/gradle/projects/it-multiplatform-0/src/desktopMain/kotlin/it/mpp0/CPointerExtension.kt
integration-tests/gradle/projects/it-multiplatform-0/src/desktopMain/kotlin/it/mpp0/ExpectedClass.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt

Extract classpath from `KotlinSharedNativeCompilation` as well

---

examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-multimodule-example/settings.gradle.kts
examples/gradle/dokka-multiplatform-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
examples/maven/pom.xml
examples/plugin/hide-internal-api/build.gradle.kts
gradle.properties
integration-tests/gradle/projects/it-android-0/gradle.properties
integration-tests/gradle/projects/it-basic-groovy/gradle.properties
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/gradle/projects/it-basic/gradle.properties
integration-tests/gradle/projects/it-collector-0/gradle.properties
integration-tests/gradle/projects/it-js-ir-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-1/gradle.properties
integration-tests/gradle/projects/it-multimodule-versioning-0/gradle.properties
integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
integration-tests/maven/projects/it-maven/pom.xml

Current Kotlin plugins version (`213-1.7.20-199-IJ6777.52`) is already the latest. It was built a week before the release, and the only difference between this version and the release version is the changelog, which should not affect us in any way.

Update Kotlin to 1.7.20

---

plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/GfmPlugin.kt
plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/JavadocPlugin.kt
plugins/jekyll/src/main/kotlin/JekyllPlugin.kt
plugins/kotlin-as-java/src/main/kotlin/KotlinAsJavaPlugin.kt

Otherwise it fails the build if `failOnWarning` configuration property is enabled, and there's nothing the user can do
Steps to reproduce:
1. Enable `failOnWarning`
2. Run gfm/javadoc/jekyll/KaJ task
3. Observe failed build
I think printing this message with `info` level is slightly better anyway, since there's nothing the user can do about the warning, there's nothing to fix on their end

Change log level to INFO for messages about alpha plugin versions

---

plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/test/kotlin/content/signatures/ContentForSignaturesTest.kt
plugins/base/src/test/kotlin/utils/contentUtils.kt

As per feedback from the libraries team

Do not render default value for var properties

---

plugins/base/base-test-utils/api/base-test-utils.api
plugins/base/base-test-utils/src/main/kotlin/renderers/SignatureUtils.kt
plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/content/functions/ContentForBriefTest.kt
plugins/base/src/test/kotlin/content/signatures/ConstructorsSignaturesTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt

* switch `fun` keyword to `constructor` for class constructors
* remove a class name from the constructor
* remove rendering of modifiers that are not applied to the constructor
fix #2689
probably, bring something to #1930

Add constructor keyword

---

plugins/kotlin-as-java/src/main/kotlin/converters/KotlinCompanion.kt
plugins/kotlin-as-java/src/main/kotlin/converters/KotlinToJavaConverter.kt
plugins/kotlin-as-java/src/main/kotlin/jvmStatic.kt
plugins/kotlin-as-java/src/test/kotlin/CompanionAsJavaTest.kt
plugins/kotlin-as-java/src/test/kotlin/JvmFieldTest.kt

* hide a companion object if it contains only `const`/`@JvmField`/`lateinit` properties or `@JvmStatic` functions
* lift the declarations to outer class from the companion
* mark lifted declarations as static
* mark `const`/`@JvmField`/`lateinit` properties as static for named objects
* remove getter/setter for `const`/`lateinit` properties in named objects/companions
* add the companion property to the outer class
Fix #200, fix #2086

Suppress useless companion for Kotlin-As-Java

---

plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/pages/utils.kt
plugins/javadoc/src/main/resources/views/class.korte
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLocationTest.kt

Before:
After:
---
Before:
After:

Fixes "The following documentation URLs were checked" message in Android Studio (IntelliJ)

---

core/build.gradle.kts
gradle.properties
plugins/all-modules-page/build.gradle.kts
plugins/base/build.gradle.kts
plugins/gfm/build.gradle.kts
plugins/templating/build.gradle.kts
plugins/versioning/build.gradle.kts

Fixes [CVE-2022-42003](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003) without going to 2.13.X branch.

Introduce jackson-databind constraint for 2.12.7.1

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt

#556
The bug occurs when an old Gradle API without [Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) is used.
New API have a lazy task configuration.

Make `outputDirectory` lazy in Gradle runner

---

.github/workflows/qodana.yml

* Builds started [failing](https://github.com/Kotlin/dokka/actions/runs/3475913847/jobs/5810645460) due to [qodana-clone-finder](https://github.com/JetBrains/qodana-clone-finder-action) being archived. 
* Updated configuration to closer match [examples](https://github.com/jetbrains/qodana-action).

Update Qodana GitHub action

---

gradle.properties
plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt

Bump Jsoup to avoid CVE-2022-36033

---

plugins/base/api/base.api
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/translators/documentables/DescriptionSections.kt
plugins/base/src/main/resources/dokka/styles/style.css
plugins/base/src/test/kotlin/content/exceptions/ContentForExceptions.kt
plugins/base/src/test/kotlin/content/inheritors/ContentForInheritorsTest.kt
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/content/samples/ContentForSamplesTest.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt
plugins/base/src/test/kotlin/utils/contentUtils.kt
plugins/base/src/test/resources/content/samples/samples.kt

Migrate params, seealso, samples, and inheritors to the description
* remove `contentForComments` API, those tags will be handled in the `contentForDescription`
* change API for `contentForScopes`: remove inheritors parameter in the method
* remove inheritors from the package list: I didn't find a way to show them there. mat be something with markdown but I don't see a reason to keep that.
Fix #2688

Move inheritors, params, see also and samples tabs to description for classlikes

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt

It happens when we have more than one class with the same name. (i.e. `mergeImplicitExpectActualDeclarations`).
I decided to write no test since #2764 breaks it.

Deduplicate extensions

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt

A typical approach in some version plugins is using an object which uses internally a `Property<String>`, and the `toString()` method unwraps it.
With `provider { … }` unwrapping it too soon is avoided.

Fix configure version eagerly

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/model/JavaTest.kt
plugins/base/src/test/kotlin/signatures/InheritedAccessorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt
plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/search/JavadocIndexSearchTest.kt
plugins/kotlin-as-java/src/test/kotlin/KotlinAsJavaPluginTest.kt

Fix #2765
If a class doesn't have an explicit constructor (with any visibility), a default synthetic one will be provided.
Affects only `DClass`.

Default Java constructor

---

integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicCachingIntegrationTest.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/GradleRelocatedCachingIntegrationTest.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt

A typical use case in a project with complex source root setup is to set `sourceLink.localDirectory` to the root of the project checkout dir and remoteUrl to the root of the project VCS url respectively.
However, since this property was marked as `InputDirectory`, in that case Gradle snapshotted hashes of all files in this entire project directory before running the Dokka task (including for example .git and .gradle directories). This could be very slow in big projects and also result in various Gradle warnings.
Now `localDirectory` is not an input property, but its relativized path is stored in another read-only input string property. Therefore, it invalidates task outputs when its value changes, but not when any content inside it.

Avoid snapshotting sourceLink.localDirectory input

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/TaskDependencyInternalWithAdditions.kt

An attempt to fix #2796
The `dokkaHtmlMultiModule` started failing after the change in Gradle: https://github.com/gradle/gradle/commit/7d9d6c473a0c29b6ae09b0cff307ae20a698b668#diff-8d6d587bb7323c4c8105f5616986da4d67c575f8f7fb576071e58587e17a6878 where a new constructor appeared.
1. Changed `AbstractTaskDependency` to `DefaultTaskDependency`.
The logic behind this: the message https://github.com/gradle/gradle/blob/ab07117466b9a28de41c1ec85a3fb6f4c61abbcd/subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java#L102 that `AbstactTask` should be replaced with `DefaultTask`. So I apply the same for `AbstractTaskDependency` and `DefaultTaskDependency`. even they are both are in `*internal*` package. But we try to override method `public TaskDependencyInternal …

Fix NoSuchMethodError with Gradle 8.0 RC1

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/CheckSourceSetDependenciesTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationJsonTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationSerializableTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayoutTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/KotlinDslDokkaTaskConfigurationTest.kt

(a new version of https://github.com/Kotlin/dokka/pull/2706)
Part of #2700 
I found these extension functions very confusing. I'm not sure what their purpose is. Do they only rename an existing function? 
It's confusing because 'by' is already a Kotlin keyword for delegation, but these extension functions don't do anything with delegation. I think using the normal `.set()` function makes the code more readable and understandable because `.set()` is a common Gradle function.

Gradle Plugin: Remove 'by' property setter helper function

---

plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

In addition to #2795
The generated default constructor has an empty package name. Meanwhile, the explicit one has the proper package (as the parent).
In the change, we directly replace `parentName` and `classNames` properties in the DRI of the constructor with values from the parent.

Fill `packageName` and `classNames` for constructors from parent

---

core/src/main/kotlin/DokkaBootstrapImpl.kt
core/src/main/kotlin/utilities/DokkaLogging.kt
core/test-api/src/main/kotlin/testApi/logger/TestLogger.kt
runners/maven-plugin/src/main/kotlin/MavenDokkaLogger.kt

It was reported that `TestLogger` sometimes throws `ArrayIndexOutOfBoundsException`. While at it, made sure other implementations are OK as well.

Make implementations of DokkaLogger thread-safe

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt

The creation of source set buttons was moved to the `source_set_selector.ftl` template, but never removed from the code
Found it while trying to find the logic for creating the source set filter buttons. It was very confusing to see and it made me think that it was invoked through reflection or that IDEA wasn't indexing things right.

Remove an unused function

---

integration-tests/build.gradle.kts

Because integration tests are cached by default, it produces no output for showcasing documentation through S3 or GitHub artifacts.
Tried to explain what needs to be done in the comment. I tried, but it takes too much time to implement and test it properly, and I'd like to restore the demo functionality sooner, so proposing to just disable it for now.
Regression from #2711

Disable caching of Dokka's integration tests

---

plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/pageMerger/PageNodeMergerTest.kt

Sort divergent elements deterministically

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaPlugin.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTaskTest.kt

Deprecate usage of custom functions to add dependencies for parent tasks(Multimodule and Collector).
It is still possible to use them but better to get rid of them. In the future, by implementing project isolation, they will be removed.
Relevant PR: #2835

Deprecate methods for adding/removing task dependencies

---

plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt
plugins/base/src/main/resources/dokka/templates/includes/source_set_selector.ftl

Regression from #2848
Dokka was rendering an empty `filter-section` div on the all-modules page, which made the JS script think that everything was filtered out.

Do not render filter-section for empty source sets

---

plugins/base/src/main/kotlin/renderers/html/NavigationDataProvider.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/main/kotlin/utils/alphabeticalOrder.kt
plugins/base/src/test/kotlin/pageMerger/PageNodeMergerTest.kt
plugins/base/src/test/kotlin/renderers/html/NavigationTest.kt

Currently, sorting groups just by name leads to the following order:
- `getElementNS`
- `getElementName`
which is inconsistent with the sorting order in the navigation bar.
After this change, the order will be:
- `getElementName`
- `getElementNS`
but if we add `getElementNs` to that, it would be strictly after `getElementNS`

Sort groups of divergent elements by their key first ignoring case, then preserving it

---

core/src/main/kotlin/utilities/DokkaLogging.kt
plugins/all-modules-page/src/test/kotlin/MultiModuleDokkaTestGenerator.kt
plugins/base/base-test-utils/src/main/kotlin/renderers/TestPage.kt
plugins/base/src/test/kotlin/basic/FailOnWarningTest.kt
plugins/base/src/test/kotlin/transformers/ContextModuleAndPackageDocumentationReaderTest1.kt
plugins/base/src/test/kotlin/transformers/ContextModuleAndPackageDocumentationReaderTest3.kt
plugins/base/src/test/kotlin/transformers/InvalidContentModuleAndPackageDocumentationReaderTest.kt
plugins/templating/src/test/kotlin/org/jetbrains/dokka/templates/TemplatingDokkaTestGenerator.kt
runners/cli/src/main/kotlin/org/jetbrains/dokka/GlobalArguments.kt

This is a prerequisite / enabler for https://github.com/Kotlin/dokka/issues/2873
* Changed the default logging level of the CLI runner configuration (DEBUG -> PROGRESS)
* Changed the default logging level of `DokkaConsoleLogger` (DEBUG -> PROGRESS)
* Preserved the `DEBUG` level in public test API declarations
* Changed our tests that created `DokkaConsoleLogger` to create it with the `DEBUG` level as before, in case it was important
I don't think `DEBUG` is a reasonable default value for any logger. It can leak sensitive and excessive information. Luckily, this is easily configurable, so it should not cause migration problems if it affects any users/plugins. 
Dokka itself emits only one log message with the debug level:
https://github.com/Kotlin/dokka/blob/73f78dc34bbcb683f345192629bdbc631 …

Change default logging level of console apps

---

core/api/core.api
core/src/main/kotlin/ConfigurationJsonUtils.kt
core/src/main/kotlin/configuration.kt
core/src/main/kotlin/utilities/json.kt
core/src/test/kotlin/utilities/DokkaConfigurationJsonTest.kt
core/src/test/kotlin/utilities/JsonKtTest.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationJsonTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationSerializableTest.kt

This is a prerequisite / enabler for https://github.com/Kotlin/dokka/issues/2873
* Extracted JSON and configuration related utility functions into a separate file for readability
* Added internal API for json pretty print + tests
* Added new public API to pretty print `DokkaConfiguration` and `ConfigurationBlock`.
* Deprecated the old API in favour of the new with a drop-in replacement.
* Changed deprecated usages within the project

Add the ability to pretty print DokkaConfiguration

---

plugins/templating/src/main/kotlin/templates/TemplateProcessor.kt

Replace `mkdir()` with `mkdirs()`, so that `relativePathToOutputDirectory` can be set as a nested. This improves the handling of aggregating modules, as they can be placed into distinct directories.
I am not sure how to test this...
Part of #2866

TemplateProcessor: replace `mkdir()` with `mkdirs()`

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaLeafTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaParentTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaCollectorTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaMultiModuleTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaTaskPartial.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaMultiModuleTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaTaskTest.kt

part of #2700 
depends on 
* #2701 
* #2702 
This helps organise the package to make it a little more understandable. All the Gradle tasks are stored in one package.

Move Gradle tasks into task package

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayout.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaSourceSetMapper.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradlePackageOptionsBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/checkDependentSourceSets.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaLeafTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaCollectorTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaMultiModuleTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaTask.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaTaskPartial.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/AndroidAutoConfigurationTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTaskTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayoutTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/KotlinDslDokkaTaskConfigurationTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/KotlinSourceSetGistTest.kt
runners/gradle-plugin/src/test/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaMultiModuleTaskTest.kt

Part of #2700 
This PR removes some of the custom Gradle utility functions that are now provided by the Gradle Kotlin DSL. 
* `getSafe()` ➡️ `get()`, or `orNull`
* `safeProperty()` ➡️ `org.gradle.kotlin.dsl.property()`
* `safeConvention()` ➡️ `convention()`
The benefit is closer alignment with the Gradle API, and more idiomatic code that helps with working with the Gradle plugin, as the code can be understood without needing to know about the custom utilities specific to Dokka.
This PR is similar to #2706.
Depends on 
* #2702
* #2705 
* #2706

Gradle Plugin: update custom Gradle utils to use Gradle Kotlin DSL

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt

Regression from https://github.com/Kotlin/dokka/commit/0a09318eae5b21194507708af51a4469ec5d57aa#diff-127cb17801c64a32309502eaee33392ad749494ba8022bef47e8002359ea1b8eL17
Before, it was loading a specific java class, so it failed with `NoClassDefFoundError` that was caught, and we returned null.
With Kotlin DSL, `findByType()` is trying to load `reified T` through `Class#getGenericSuperclass`, which throws `TypeNotPresentException`.
We don't expect that `TypeNotPresentException` will be thrown, so it's not caught and the user project is failing with
```
Caused by: java.lang.TypeNotPresentException: Type org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension not present
at org.gradle.api.reflect.TypeOf.captureTypeArgument(TypeOf.java:301)
at …
```

Fix `TypeNotPresentException` in projects without KGP

---

.github/workflows/gradle-test.pr.yml

This version is unsupported so there's little value in testing with it.

Stop testing on Java 15

---

core/src/main/kotlin/model/DisplaySourceSet.kt
plugins/base/src/main/kotlin/resolvers/local/DokkaLocationProvider.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt

Also, it fixed a weird link to `Enum.name` in stdlib since there are a lot of anchors to `Enum.name`.

Fix unresolved link to declaration from another source set

---

plugins/base/frontend/package-lock.json

Non-breaking updates
* Bumps loader-utils from 1.4.0 to 1.4.2
* Bumps json5 from 1.0.1 to 1.0.2
* Bumps qs from 6.7.0 to 6.11.0
* Bumps express from 4.17.1 to 4.18.2
* Bumps minimatch from 3.0.4 to 3.1.2
* Bumps terser from 5.10.0 to 5.14.2
* Bumps angular
___
Combnes changes from PRs:
* https://github.com/Kotlin/dokka/pull/2750
* https://github.com/Kotlin/dokka/pull/2800
* https://github.com/Kotlin/dokka/pull/2767
* https://github.com/Kotlin/dokka/pull/2773
* https://github.com/Kotlin/dokka/pull/2574

Bump npm dependencies with vulnerabilities

---

.gitignore
plugins/.gitignore

* Removed unnecessary ignores for
* Maven
* Android
* `.idea/` subdirectories (`.idea/` is already ignored)
* old Gradle files (there's no Gradle UI any more, or task-cache file)
* Removed ignores for project files that don't exist any more

tidy up .gitignore files

---

runners/gradle-plugin/build.gradle.kts
runners/maven-plugin/build.gradle.kts

This PR removes some defined, but unused, Gradle tasks
These custom `sourceJar` tasks are not used. A `sourcesJar` is auto-created using `withSourcesJar()`
https://github.com/Kotlin/dokka/blob/6b46d95bf31a15952c07e8072bc134bbbf02ca5f/buildSrc/src/main/kotlin/org/jetbrains/conventions/base-java.gradle.kts#L20-L22

Remove unused Gradle tasks

---

examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts

remove unnecessary brackets from Dokka plugin version, so the Gradle examples are more idiomatic.

nitpick: Gradle examples tidy up

---

build.gradle.kts
core/api/core.api
core/build.gradle.kts
core/src/main/kotlin/InternalDokkaApi.kt
core/src/main/kotlin/utilities/SelfRepresentingSingletonSet.kt

Rationale:
dokka-core has a long history of bloating its API shape with utilities that were never intended to be public and that may expose unwanted implementation details, as well as unwanted compatibility burden.
Eventually, we would like to get rid of them (i.e. by making them internal), but first it would be nice to provide users with an explicit message about it

Introduce InternalDokkaApi annotation

---

plugins/base/frontend/build.gradle.kts
settings.gradle.kts

Both unit and integration tests became extremely flaky because they are unable to find the node dependency, even though it can be downloaded manually.
```
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.nodejs:node:16.13.0.
Searched in the following locations:
- https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.gz
Required by:
project :plugins:base:frontend
```

Fix flaky nodejs dependency

---

build-logic/src/main/kotlin/org/jetbrains/conventions/base.gradle.kts

https://github.com/Kotlin/dokka/labels/infrastructure
This PR adds [reproducible archive build config](https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives)
This helps Gradle caching and improves build speed.
I tested this by 
1. update `dokka_version` to be `1.8.20` (just so long as it's not a SNAPSHOT - otherwise the comparison below is impossible)
1. publishing to MavenProjectLocal
`./gradlew publishAllPublicationsToMavenProjectLocalRepository`
2. rename `$rootDir/build/maven-project-local` to `$rootDir/build/maven-project-local-tmp`
4. re-run 
`./gradlew publishAllPublicationsToMavenProjectLocalRepository`
5. comparing ([with IntelliJ](https://www.jetbrains.com/help/idea/comparing-files-and-folders.html#comparing_folders)) …

add reproducible archive build config

---

build-logic/src/main/kotlin/org/jetbrains/conventions/maven-publish.gradle.kts
build-logic/src/main/kotlin/org/jetbrains/publication.kt
runners/gradle-plugin/build.gradle.kts

https://github.com/Kotlin/dokka/labels/infrastructure
Continue migrating the build logic to use convention plugins #2703 
It is a small part of simplifying the logic in `build-logic/src/main/kotlin/org/jetbrains/publication.kt`
This change has only one change: I removed the `afterEvaluate {}` logic for configuring the Dokka Gradle Plugin POM. The result is that the POM is now different. 
(the PR is on the left, master is on the right)
I'd like to be able to avoid this, but I think that improving the build logic is better than trying to edit a POM that most people won't realise even exists!
I have tested this by 
1. update `dokka_version` to be `1.8.20` (just so long as it's not a SNAPSHOT - otherwise the comparison below is impossible)
1. publishing to MavenProjectLocal
`./gradlew …

move POM config to maven-publish convention plugin

---

.github/workflows/check.yml
.github/workflows/dokka-examples.yml
.github/workflows/gh-actions-artifacts-snapshots.yml
.github/workflows/gh-pages-examples.yml
.github/workflows/gh-pages.yml
.github/workflows/gradle-test.pr.yml
.github/workflows/s3-snapshots.yml
build-logic/src/main/kotlin/org/jetbrains/conventions/base-java.gradle.kts
build-logic/src/main/kotlin/org/jetbrains/conventions/base.gradle.kts
build-logic/src/main/kotlin/org/jetbrains/conventions/kotlin-jvm.gradle.kts

Stick with Java 17 on CI

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
plugins/base/src/test/kotlin/renderers/html/TabbedContentTest.kt
plugins/base/src/test/kotlin/signatures/InheritedAccessorsSignatureTest.kt

* It is more consistent with the declaration order described in our [coding conventions](https://kotlinlang.org/docs/coding-conventions.html#class-layout)
* There are usually less properties than functions, so it should help with not having to scroll as much to get to them
Current (that is, before this change) behaviour could be seen here: [kotlinx-datetime#Instant](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/)

Move the Properties block to be above Functions

---

build-logic/src/main/kotlin/org/jetbrains/conventions/maven-publish.gradle.kts

Fixes the issue described in https://github.com/Kotlin/dokka/pull/2704#issuecomment-1499517930
To test this I ran `./gradlew publishAllPublicationsToMavenProjectLocalRepository` and searched for `shadowRuntimeElements` in the directory `$rootDir/build/maven-project-local`
On master branch there was a match. On the PR branch, there was no match.

disable publication of shadowRuntimeElements variant

---

CONTRIBUTING.md

Continuation of the discussion in https://github.com/Kotlin/dokka/pull/2938#issuecomment-1488196317, some useful / non obvious information for contributors
Can be merged once #2951 is merged as this PR references files from it.

Add more infrastructure information to CONTRIBUTING.md

---

examples/gradle/dokka-multimodule-example/parentProject/build.gradle.kts

The configuration of source links in multimodule projects has been asked about multiple times, and we don't seem to have an example for it.
A community member asked about it yesterday in the Kotlin Community Slack, so I decided to add an example both to check that it works and to point people to it for configuration tips

Add source links to the dokka-multimodule-example project

---

build-logic/src/main/kotlin/org/jetbrains/conventions/maven-cli-setup.gradle.kts
build.gradle.kts
core/build.gradle.kts
gradle/libs.versions.toml
kotlin-analysis/intellij-dependency/build.gradle.kts
plugins/versioning/build.gradle.kts
runners/maven-plugin/build.gradle.kts

Needed to update the Kotlin version, and got kinda lost in the toml
It's best to just check out the branch locally and see if it's convenient from the maintenance perspective. If some things are confusing or you know in advance that you will struggle with it - do suggest an alternative
___
* Reordered dependency versions and redid the grouping so that it's (subjectively) more convenient to update:
* The most important and frequently updated ones are at the top (KGP, AGP, analysis, etc)
* Analysis is grouped together and decoupled, so we can update KGP and the compiler versions independently. This should be pretty useful when migrating to K2, and should be useful in general when migrating to new/dev versions of Kotlin, and especially useful for troubleshooting.
* Renamed a few properties …

Reorder dependency versions for update convenience

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaPlugin.kt

This is a fix for https://github.com/Kotlin/dokka/labels/runner%3A%20Gradle%20plugin
By using `set()` this can override any configuration done in user scripts, but _before_ the `configureEach{}` block is evaluated. `convention()` means that even if `configureEach{}` runs later, it won't override any previous `set()`.
Unfortunately there's no clean way to set the convention of a DirectoryProperty https://github.com/gradle/gradle/issues/23708, hence the weird syntax.

DGP: set cacheRoot using convention(), not set()

---

plugins/base/src/main/kotlin/parsers/moduleAndPackage/parseModuleAndPackageDocumentationFragments.kt
plugins/base/src/test/kotlin/transformers/InvalidContentModuleAndPackageDocumentationReaderTest.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/DokkaMultiModuleTask.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Multiple places throughout the repository link the [Module documentation](https://kotlinlang.org/docs/dokka-module-and-package-docs.html). The link contains an additional `/reference` in the path and therefore produce a `404`.
Old link:
```
https://kotlinlang.org/docs/reference/dokka-module-and-package-docs.html
```
New link:
```
https://kotlinlang.org/docs/dokka-module-and-package-docs.html
```
Should this be a temporary error on the kotlinlang website feel free to just close the PR.

Replace invalid documentation links

---

docs/topics/dokka-module-and-package-docs.md
docs/topics/dokka-plugins.md
docs/topics/formats/dokka-javadoc.md
docs/topics/formats/dokka-markdown.md
docs/topics/runners/dokka-cli.md
docs/topics/runners/dokka-gradle.md
docs/topics/runners/dokka-maven.md

minor fix for documents: typo, code style

minor fix for document

---

docs/topics/runners/dokka-cli.md

The change of markdown header in dokka-cli.md from "External documentation configuration" to "External documentation links configuration" created some dead links in the page. This PR should fix them and prevent TeamCity builds failing for the Kotlin docs website.

Fix dead links for CLI external links configuration

---

runners/gradle-plugin/api/gradle-plugin.api
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/internal/AbstractDokkaTaskExtensions.kt

A proposal for an intermediate solution for #2873, which should help with debugging configuration and compatibility issues.
cc @aSemy

Add the ability to get serialized configuration of a task

---

plugins/base/src/main/resources/dokka/styles/style.css

> Also, if it's not too much to ask, can you disable showing this "copy anchor" popup if JS is disabled? It's not going to work if it's pressed. Hover over any function/property name from the left column
Request from original PR: https://github.com/Kotlin/dokka/pull/2836

disable showing this "copy anchor" popup if JS is disabled

---

plugins/base/src/main/resources/dokka/styles/style.css

<details>
<summary>Bug screenshot</summary>
</details>
<details>
<summary>Fixed screenshot</summary>
</details>

KTL-982; redundant spacing for tabs

---

plugins/base/src/main/resources/dokka/styles/style.css

https://youtrack.jetbrains.com/issue/KTL-1028
The first click on a method in the mobile version, the copy icon appears.

Incorrectly handles a click on a method and other elements in the mobile version

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js
plugins/base/src/test/kotlin/renderers/html/SourceSetFilterTest.kt
runners/cli/src/main/kotlin/org/jetbrains/dokka/SourceSetArgumentsParser.kt
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

Fixes #3011 
Read my comment to understand what exactly the problem was: https://github.com/Kotlin/dokka/issues/3011#issuecomment-1568620493
There are better ways to resolve this problem, but this is the only solution that I could think of that wouldn't lead to a lot of other regressions and problems (including for Gradle users), because the value of `scopeId` is used in other parts of the code as well, such as sorting and anchor links, so changing it would lead to regression in behaviour.
One could argue that module names should not contain spaces - I would agree, but the `moduleName` property is used as the parent project name, so the desire to change it to something human-readable is quite understandable, and if we fix it know it's likely going to lead to bug reports. It really needs …

Fix invisible packages for module names with space

---

plugins/base/src/main/kotlin/translators/psi/PsiAccessorConventionUtil.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt

Fixes #2992
Haven't tested it extensively, but I'm pretty sure that's where the problem is

Multi-param methods should not qualify for a setter

---

build.gradle.kts

This seems to be a regression from #2912. It was blocking the release, but I [commited this fix](https://github.com/Kotlin/dokka/commit/46c10ac2b169a007aefdad3c9720031a8e05d784) directly into the release branch, so no rush now.
Without this change, running `./gradlew publishPlugins` results in:
```
> Task :publishPlugins FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':publishPlugins'.
> No plugins defined. Please declare at least one plugin in a pluginBundle plugins block
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
```
With this change, the artifacts are built and published as expected (well, time will tell).
As far as I …

Fix publishing to Gradle Plugin Portal

---

plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt
plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt
plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt

Do not leak unknown asset paths into HTML

---

.github/workflows/tests-smoke.yml
.github/workflows/tests-thorough.yml
build-logic/src/main/kotlin/org/jetbrains/DokkaBuildProperties.kt
build-logic/src/main/kotlin/org/jetbrains/conventions/base-java.gradle.kts

The `mainCompiler` version was updated to `11` in https://github.com/Kotlin/dokka/pull/3062/commits/80fc13b5906c9d500605bb414d0529f9141ff03f, which should've caused the [thorough tests](https://github.com/Kotlin/dokka/actions/runs/5483737953) to fail when run under Java 8, but all tests passed successfully.
Had a look at why and noticed that the property name was a bit off, so it should hopefully fix it.

Set the correct testLauncher property in workflows

---

core/src/main/kotlin/utilities/json.kt
core/src/test/kotlin/utilities/JsonKtTest.kt

* for markdown files for multi module description

DokkaConfiguration: Use LinkedHashSet instead of Set to preserve order for includes when deserialize (#2999)

---

plugins/base/src/main/resources/dokka/docs/kdoc/EnumEntries.kt.template
plugins/base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/SyntheticDescriptorDocumentationProvider.kt

Hardcode documentation for the synthetic Enum.entries property

---

plugins/base/src/test/kotlin/model/JavaTest.kt
subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/DokkaPsiParser.kt

Previously, because `PsiWildcardType`s have an implicit bound of `extends Object`, a wildcard type with a `super` bound was being turned into a `Covariance` instead of a `Contravariance`.
Fixes #3091

Fix handling of Java contravariance

---

plugins/base/src/main/resources/dokka/styles/style.css

This is @krutilov patch for mobile view tables

feat(ktl-984); add scroll for mobile tables

---

examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-multimodule-example/gradle.properties
examples/gradle/dokka-multiplatform-example/build.gradle.kts
examples/gradle/dokka-multiplatform-example/src/linuxMain/kotlin/org/kotlintestmpp/CInterop.kt
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
examples/maven/pom.xml
examples/plugin/hide-internal-api/build.gradle.kts
integration-tests/gradle/projects/it-basic-groovy/gradle.properties
integration-tests/gradle/projects/it-basic/gradle.properties
integration-tests/gradle/projects/it-collector-0/gradle.properties
integration-tests/gradle/projects/it-configuration/gradle.properties
integration-tests/gradle/projects/it-js-ir-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-0/gradle.properties
integration-tests/gradle/projects/it-multimodule-1/gradle.properties
integration-tests/gradle/projects/it-multimodule-versioning-0/gradle.properties
integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
integration-tests/gradle/projects/it-sequential-tasks-execution-stress/gradle.properties
integration-tests/gradle/projects/it-wasm-basic/gradle.properties
integration-tests/maven/projects/it-maven/pom.xml

A sanity check that we can build our own examples and tests with Kotlin 1.9.0, in case they uncover some unknown problems.

Update examples and tests to use Kotlin 1.9.0

---

plugins/base/api/base.api
plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/deprecated/AnalysisApiDeprecatedError.kt
plugins/base/src/main/kotlin/deprecated/KotlinAnalysisDeprecatedApi.kt
plugins/base/src/main/kotlin/deprecated/ParsersDeprecatedAPI.kt
plugins/base/src/main/kotlin/deprecated/ParsersFactoriesDeprecatedAPI.kt
plugins/base/src/main/kotlin/deprecated/TranslatorDescriptorsDeprecatedAPI.kt
plugins/base/src/main/kotlin/deprecated/TranslatorPsiDeprecatedAPI.kt

As discussed in #3034, some removed analysis APIs have been reintroduced with a deprecation message leading to #3099

Reintroduce removed analysis APIs with a deprecation message

---

integration-tests/gradle/projects/it-wasm-basic/build.gradle.kts
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/WasmGradleIntegrationTest.kt
runners/gradle-plugin/api/gradle-plugin.api
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt
runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt

This **transitively** fixes the support for single-target multiplatform projects.
During some refactoring in KGP, a bug was noticed that led to the creation of a redundant commonMain compilation in single-target multiplatform projects. This bug was fixed in KGP 1.9, so single-target multi-platform projects do not have this accidental compilation anymore.
Dokka had [an additional check](https://github.com/Kotlin/dokka/blob/master/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt#L26) that filtered out the compatibility / legacy `main` compilation.
This led to the situation where single-target multiplatform projects using Kotlin 1.9.0 had no viable compilations **from Dokka's perspective** (because one was removed by KGP, and another one …

Make the compatibility metadata variant check more specific

---

examples/plugin/hide-internal-api/build.gradle.kts
integration-tests/gradle/projects/template.root.gradle.kts
integration-tests/gradle/projects/template.settings.gradle.kts
integration-tests/maven/projects/biojava/biojava.diff
integration-tests/maven/projects/it-maven/pom.xml

Otherwise, our integration tests try to resolve these repositories on failures

Get rid of bintray and jcenter mentions in our buildscript

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt

attempt to fix #3068 which is blocking building documentation for https://github.com/whyoleg/cryptography-kotlin/tree/dev (`dev` branch, KGP 1.9.0)
for recent changes consult: https://github.com/Kotlin/dokka/pull/3081#issuecomment-1666818036

potential fix for compatibility with KGP 1.9

---

plugins/base/src/main/kotlin/DokkaBase.kt
plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt
plugins/base/src/main/kotlin/transformers/pages/DefaultSamplesTransformer.kt
plugins/base/src/test/kotlin/content/samples/ContentForSamplesTest.kt
subprojects/analysis-kotlin-api/api/analysis-kotlin-api.api
subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/internal/InternalKotlinAnalysisPlugin.kt
subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/internal/SampleProvider.kt
subprojects/analysis-kotlin-descriptors/compiler/api/compiler.api
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/CompilerDescriptorAnalysisPlugin.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/impl/KotlinSampleProvider.kt

Also, the PR has some refactoring. I am not sure that the page transformer (`SampleTransformer`) should be in the analysis plugin.

Fix and refactor Sample Transformer

---

subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/impl/DescriptorFullClassHierarchyBuilder.kt

After [#3053 ](https://github.com/Kotlin/dokka/blob/cbd9733d3dd2f52992e98e7cebd072091a572529/plugins/base/src/main/kotlin/transformers/documentables/ActualTypealiasAdder.kt#L81) we have a cast error in StdLib

Fix cast error to `ClassDescriptor`

---

subprojects/analysis-kotlin-descriptors/compiler/api/compiler.api
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/CompilerDescriptorAnalysisPlugin.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/AnalysisContext.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/KotlinAnalysis.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/impl/KotlinSampleProvider.kt

Instead of the [system property](https://github.com/Kotlin/dokka/commit/900fbccf3da483946227d99ce52b71afe0e62007) the configuration has been introduced since a system property does not have the possibility to run tasks with different options.

Introduce configuration for K1 analysis plugin

---

README.md

Adds a link to the Gradle docs, generated with Dokka.
I thought it would be nice to add a link to a large library that most developers will have heard of.

add Gradle to Dokka users in README

---

runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaTask.kt

Since, as for now, Dokka is not compatible with the Gradle configuration cache (see [#1217](https://github.com/Kotlin/dokka/issues/1217)), using it in a project that has it enabled will fail the build. 
Marking the tasks as incompatible avoids these fails.

Mark tasks as not compatible with the Gradle configuration cache

---

CONTRIBUTING.md
README.md
docs-developer/src/doc/docs/developer_guide/workflow.md
docs/v.list
examples/gradle/dokka-customFormat-example/build.gradle.kts
examples/gradle/dokka-gradle-example/build.gradle.kts
examples/gradle/dokka-kotlinAsJava-example/build.gradle.kts
examples/gradle/dokka-library-publishing-example/build.gradle.kts
examples/gradle/dokka-multimodule-example/gradle.properties
examples/gradle/dokka-multiplatform-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts
examples/gradle/dokka-versioning-multimodule-example/parentProject/build.gradle.kts
examples/maven/pom.xml
examples/plugin/hide-internal-api/README.md
examples/plugin/hide-internal-api/build.gradle.kts
examples/plugin/hide-internal-api/gradle.properties
gradle/libs.versions.toml
integration-tests/gradle/projects/it-basic/build.gradle.kts
integration-tests/gradle/projects/it-configuration/build.gradle.kts
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/BasicGradleIntegrationTest.kt
plugins/kotlin-as-java/README.md
plugins/mathjax/README.md
plugins/versioning/README.md

Updates referenced Dokka versions to 1.9.0

Update Dokka's references to 1.9.0

---

.github/workflows/gh-pages-deploy-dev-docs.yml

The `dokka_version` property was set to `1.9.0-SNAPSHOT` in the release branch when I published the release on GitHub, so it published the developer guides under [kotlin.github.io/dokka/1.9.0-SNAPSHOT](https://kotlin.github.io/dokka/1.9.0-SNAPSHOT/).
I've [fixed the version](https://github.com/Kotlin/dokka/commit/83eaebecf088939a36be6591c9e1ee9c5eba8876), but there's no way to redeploy the docs.
Adding `workflow_dispatch` allows one to manually trigger a workflow on a branch, which will allow me to publish the developer guides under the correct version

Allow manual deployment of the developer guides

---

plugins/base/src/test/kotlin/translators/ExternalDocumentablesTest.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/java/KotlinDocCommentParser.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/moduledocs/ModuleAndPackageDocumentationParsingContext.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/AnnotationTranslator.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeTranslator.kt

For example
`typealias CompletionHandler = (cause: Throwable?) -> Unit` has a functional type with no type arguments in K2. In K1 we have a usual generic type

[K2] Fix functional type and improve logging for unresolved link

---

plugins/base/src/main/resources/dokka/scripts/symbol-parameters-wrapper_deferred.js

symbol wrapper script in dokka has Infinity cycling code based on [observe](https://github.com/Kotlin/dokka/blob/879d4f2652d528f20c95d5bb17899d6cb10c5e85/plugins/base/src/main/resources/dokka/scripts/symbol-parameters-wrapper_deferred.js#L29)/[unobserve](https://github.com/Kotlin/dokka/blob/879d4f2652d528f20c95d5bb17899d6cb10c5e85/plugins/base/src/main/resources/dokka/scripts/symbol-parameters-wrapper_deferred.js#L8) inside resize handler.
MRE:
```javascript
const observer = new ResizeObserver(entries => entries.forEach({ target } => {
observer.unobserve(target);
observer.observe(target); // fire re-call this ResizeObserver handler
}));
document.querySelectorAll('...').forEach(item => observer.observe(item));
```

fix(KTL-1177): Resize Observer has indefinite loop

---

subprojects/analysis-kotlin-descriptors/compiler/api/compiler.api
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/JvmDependenciesIndexImpl.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/KotlinCliJavaFileManagerImpl.kt

Restore fix #1599

---

subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/JvmDependenciesIndexImpl.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/KotlinCliJavaFileManagerImpl.kt

#3143 wasn't based on latest master, so the checks were green, but then the compilation failed due to explicit API mode

Fix compilation errors due to explicit api mode

---

plugins/base/src/test/kotlin/content/HighlightingTest.kt
plugins/base/src/test/kotlin/content/annotations/KotlinDeprecatedTest.kt
plugins/base/src/test/kotlin/content/annotations/SinceKotlinTest.kt
plugins/base/src/test/kotlin/content/exceptions/ContentForExceptions.kt
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt
plugins/base/src/test/kotlin/content/typealiases/TypealiasTest.kt
plugins/base/src/test/kotlin/enums/KotlinEnumsTest.kt
plugins/base/src/test/kotlin/filter/DeprecationFilterTest.kt
plugins/base/src/test/kotlin/filter/VisibilityFilterTest.kt
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt

Due to the recent changes in how Analysis API handles builtins, the update to the fresh version of Analysis API requires registering Kotlin stdlib in every testsuite.
Also, it mutes some unit tests for K2 since the new Analysis API broke them.

Register Kotlin stdlib classpath in every unit test and mute some tests for K2

---

subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/SymbolsAnalysisPlugin.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolFullClassHierarchyBuilder.kt

Otherwise, `Caused by: org.jetbrains.kotlin.utils.exceptions.KotlinIllegalArgumentExceptionWithAttachments: Unexpected class org.jetbrains.kotlin.analysis.project.structure.KtBuiltinsModule
at org.jetbrains.kotlin.analysis.low.level.api.fir.util.ExceptionUtilsKt.errorWithFirSpecificEntries(exceptionUtils.kt:50)`

[K2] Avoid calling `analyze` on built-ins psi

---

gradle/libs.versions.toml
subprojects/analysis-kotlin-symbols/build.gradle.kts
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/AnalysisContext.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt

It is a duplicate of https://github.com/Kotlin/dokka/pull/3150 but with the updated version of Analysis API artifacts.
---
Context: https://youtrack.jetbrains.com/issue/KT-60884
This PR requires the [rr/darthorimar/status-resolve-contract branch](https://github.com/JetBrains/kotlin/tree/rr/darthorimar/status-resolve-contract) to the Kotlin repository
[Link to the corresponding MR](https://jetbrains.team/p/kt/reviews/11979) (Internal JetBrains link)
Also, due to the recent changes in how we handle builtins in Analysis API, the update to the fresh version of Analysis API requires registering Kotlin stdlib in every testsuite.

[K2] Migrate to new standalone API

---

gradle/libs.versions.toml

Bumps all dependencies that do not require any changes in Dokka's code, so hopefully there's no regression and it won't backfire :)
Ran the tests locally — looks good. Haven't seen the HTML output yet though, will do once GitHub generates it.

Bump dependencies without visible API changes

---

plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js
plugins/base/src/test/kotlin/renderers/html/TabbedContentTest.kt

Fix active-tab selection for different page contexts

---

docs/topics/runners/dokka-maven.md
runners/maven-plugin/src/main/kotlin/DokkaMojo.kt

This PR transforms source links path into canonical paths, as the paths being checked when getting source links are absolute
This fixes sources not being linked when using relative paths in Maven projects, that was caused by `SourceLinksTransformer#resolveSources` comparing absolute paths to relative paths, when Maven was used.

Fix sources not being linked when using Maven

---

plugins/base/src/main/kotlin/generation/SingleModuleGeneration.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt

It was marked experimental in a new version of coroutines https://github.com/Kotlin/kotlinx.coroutines/commit/042720589c6f438f77d84254bd2dceb569f0184, after 5a6fab535b68916a28d922d5d7a294fa432b7d6b

Opt-in `ExperimentalCoroutinesApi` for `newSingleThreadContext`

---

build-logic/src/main/kotlin/org/jetbrains/conventions/base-unit-test.gradle.kts
plugins/base/src/test/kotlin/content/annotations/ContentForAnnotationsTest.kt
plugins/base/src/test/kotlin/content/annotations/JavaDeprecatedTest.kt
plugins/base/src/test/kotlin/content/params/ContentForParamsTest.kt
plugins/base/src/test/kotlin/filter/JavaVisibilityFilterTest.kt
plugins/base/src/test/kotlin/markdown/LinkTest.kt
plugins/base/src/test/kotlin/model/ClassesTest.kt
plugins/base/src/test/kotlin/model/ExtensionsTest.kt
plugins/base/src/test/kotlin/model/JavaTest.kt
plugins/base/src/test/kotlin/model/MultiLanguageInheritanceTest.kt
plugins/base/src/test/kotlin/model/annotations/JavaAnnotationsForParametersTest.kt
plugins/base/src/test/kotlin/model/annotations/JavaAnnotationsTest.kt
plugins/base/src/test/kotlin/parsers/JavadocParserTest.kt
plugins/base/src/test/kotlin/renderers/html/NavigationIconTest.kt
plugins/base/src/test/kotlin/signatures/FunctionalTypeConstructorsSignatureTest.kt
plugins/base/src/test/kotlin/signatures/InheritedAccessorsSignatureTest.kt
plugins/base/src/test/kotlin/superFields/DescriptorSuperPropertiesTest.kt
plugins/base/src/test/kotlin/superFields/PsiSuperFieldsTest.kt
plugins/base/src/test/kotlin/transformers/ObviousAndInheritedFunctionsDocumentableFilterTest.kt
plugins/base/src/test/kotlin/transformers/isExceptionTest.kt
plugins/base/src/test/kotlin/translators/Bug1341.kt
plugins/base/src/test/kotlin/translators/DefaultPsiToDocumentableTranslatorTest.kt
plugins/base/src/test/kotlin/translators/ExternalDocumentablesTest.kt
plugins/base/src/test/kotlin/translators/JavadocInheritDocsTest.kt
plugins/base/src/test/kotlin/translators/JavadocInheritedDocTagsTest.kt
plugins/base/src/test/kotlin/translators/JavadocParserTest.kt
plugins/base/src/test/kotlin/utils/TagsAnnotations.kt

It is based on #3202. Otherwise, we will have the flaky tests.
Is is tested by https://github.com/Kotlin/dokka/actions/runs/6486414842

[K2] Enable Java tests for symbols

---

gradle/libs.versions.toml
plugins/base/src/test/kotlin/content/annotations/SinceKotlinTest.kt
plugins/base/src/test/kotlin/content/exceptions/ContentForExceptions.kt
plugins/base/src/test/kotlin/content/seealso/ContentForSeeAlsoTest.kt
plugins/base/src/test/kotlin/linkableContent/LinkableContentTest.kt
plugins/base/src/test/kotlin/model/InheritorsTest.kt
plugins/base/src/test/kotlin/signatures/DivergentSignatureTest.kt
plugins/base/src/test/kotlin/signatures/SignatureTest.kt
plugins/base/src/test/kotlin/transformers/ModuleAndPackageDocumentationTransformerFunctionalTest.kt
plugins/base/src/test/kotlin/transformers/SourceLinkTransformerTest.kt
subprojects/analysis-kotlin-symbols/build.gradle.kts
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/java/KotlinDocCommentParser.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/moduledocs/ModuleAndPackageDocumentationParsingContext.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/moduledocs/ModuleAndPackageDocumentationReader.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/AnalysisContext.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/KotlinAnalysisProjectProvider.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/KotlinSampleProvider.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolExternalDocumentablesProvider.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolFullClassHierarchyBuilder.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt
subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt

We map [Dokka's source set ](https://kotlinlang.org/docs/dokka-gradle.html#source-set-configuration) directly to [a source module ](https://github.com/JetBrains/kotlin/blob/500de9f9bba5baad7e0f2c9260c298bb21cd5de7/analysis/project-structure/src/org/jetbrains/kotlin/analysis/project/structure/KtModule.kt#L25C27-L25C27) of Analysis API inside one [Analysis Standalone session](https://github.com/JetBrains/kotlin/blob/141333bdcd22c9d257d88dbce50fa8499206a0f8/analysis/analysis-api-standalone/src/org/jetbrains/kotlin/analysis/api/standalone/StandaloneAnalysisAPISession.kt#L18).
Analysis API session is created in `src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt` (see  `fun createAnalysisSession`)
Before the PR, one Dokka's source set corresponded to one …

[K2] Reorganize project model for MPP

---

gradle/libs.versions.toml
plugins/base/src/test/kotlin/markdown/ParserTest.kt
subprojects/analysis-markdown-jb/src/main/kotlin/org/jetbrains/dokka/analysis/markdown/jb/MarkdownParser.kt

I've checked some trivial cases, and we have some test coverage (direct and indirect), so it should be relatively safe
I'll try to find the team who oversees this library and ask them if there were any significant changes or cases worth checking just in case.

Update org.jetbrains.markdown from 0.3.1 to 0.5.2

---

core/test-api/src/main/kotlin/testApi/testRunner/TestRunner.kt
gradle/libs.versions.toml
integration-tests/gradle/projects/it-multiplatform-0/build.gradle.kts
integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
integration-tests/gradle/projects/it-wasm-basic/build.gradle.kts
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/Multiplatform0GradleIntegrationTest.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/WasmGradleIntegrationTest.kt
integration-tests/maven/projects/it-maven/pom.xml
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/resolve/DokkaJsResolverForModuleFactory.kt
subprojects/analysis-kotlin-descriptors/compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/resolve/DokkaKlibMetadataCommonDependencyContainer.kt

The current changes are related to https://github.com/JetBrains/kotlin/commit/d797505f06d640b666829bbfb4b7d7c67f812026

Update Kotlin compiler and KGP to 1.9.20-RC2

---

docs/topics/dokka-module-and-package-docs.md
docs/topics/dokka-plugins.md
docs/topics/formats/dokka-html.md
docs/topics/formats/dokka-javadoc.md
docs/topics/runners/dokka-gradle.md

This PR removes non-versioned code links pointing to master from the user-facing documentation.
There are two primary reasons for that:
1. After #3174, some links pointing to master have become outdated.
2. The readers that followed the link might see something in `master` which is not yet available in the latest release, so it would lead to confusion.
The links themselves will be updated to point to the new locations once 1.9.20 is out
___
This is intentionally done as a separate PR and not as part of #3174, because if the internal TeamCity build that publishes documentation fails, it will be easier to find the reason.

Use versioned code links in user-facing documentation

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/KotlinSignatureProvider.kt
dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt

For testing K2 migration, I'm using the approach of comparing Dokka output with K1. There are a lot of places where the difference is not user-visible but just an empty block `<span class="token keyword"></span>` in signatures. This makes it challenging to analyze the results. The PR should help to omit such `span`s.

Remove modifier rendering if it empty

---

.idea/vcs.xml

Allows to click on issue/PR numbers in VCS history and be redirected to GitHub
Example:
Here on screenshot we can see Git window and 3 highlighted links: `#3333` and `#3327` in the left panel + `#3333` in the right panel. All of them are clickable and will redirect to `https://github.com/Kotlin/dokka/pull/3333` or `https://github.com/Kotlin/dokka/pull/3327`.
This simplifies a lot following Git Blame, and so understanding of context on why one or another change were implemented (via PR comments or issue description).
In last couple of days, while investigating behaviour of CodeBlocks I've done a lot of copy-pasting of issue number to GitHub and I was tired of this :) So I've configured this for local development.
Later I've found, that it's possible to share this config via Git, like in …

Add GitHub issues navigation for IDEA

---

dokka-subprojects/plugin-base/api/plugin-base.api
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/DokkaBase.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/HtmlCodeBlockRenderer.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/HtmlRenderer.kt
dokka-subprojects/plugin-base/src/test/kotlin/renderers/html/CodeBlocksTest.kt

Fixes #3244
Notes:
* multiple custom renderers can be installed to support different languages independently
* if no custom renderers is applicable for rendering code blocks, default (original) code will be used
* as was discussed internally, in extension, only `language` and `code` properties are provided instead of full `ContentCodeBlock` type
Example of usage in mermaid plugin: https://github.com/whyoleg/dokka-mermaid/commit/0c0cd231514ff6a508526ecff715fe4fc00fda93

Implement custom code block renderers support

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/SyntheticKDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/java/KotlinDocCommentParser.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/moduledocs/ModuleAndPackageDocumentationParsingContext.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolSampleAnalysisEnvironment.kt

Continuation of https://github.com/Kotlin/dokka/pull/3195#pullrequestreview-1740723020

Address review comments for Sample API

---

dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/TagsAnnotations.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/documentable/ObviousFunctionsTest.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/transformers/ObviousAndInheritedFunctionsDocumentableFilterTest.kt

Fixes #2863
This is draft because of 2 questions:
1. To allow Analysis API to analyse `kotlin` package, we need to provide flag `AnalysisFlags.allowKotlinPackage` - should we hide it under a flag at our side? And if so, what is the best way provide it to analysis? Or we can just set it `true` - Descriptor based analysis doesn't need any additional configuration
2. There is a test failing for `Enum`. During getting functions of class for `Enum` from test it fetches also methods from `Enum.java`: `clone`, `finalize`, `getDeclaringClass`. Somewhere later first 2 are filtered, but the last one is not, and so present in the documentation in the end. I was failed "to find why" and "what to do next" during debugging for 2 hours of FIR compiler internals... So asking for some help here :)

Don't suppress obvious members in kotlin.Enum and kotlin.Any

---

.github/workflows/tests-thorough.yml
dokka-integration-tests/settings.gradle.kts
dokka-runners/runner-cli/settings.gradle.kts
dokka-runners/runner-gradle-plugin-classic/settings.gradle.kts
dokka-runners/runner-maven-plugin/settings.gradle.kts
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/documentable/ObviousFunctionsTest.kt
settings.gradle.kts

After merging PR #3349 to master, enum test failed on JDK 17: https://github.com/Kotlin/dokka/actions/runs/6983352619/job/19004323879#step:6:362
Cause: in JDK 12 one new method was added to Enum class - https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Enum.html#describeConstable()
Also checked on JDK 21 - one more failure, now because of deprecation for removal of finalize in JDK 18 - https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Enum.html#finalize()
Added running tests for JDK 21 on CI + gradle toolchain auto-resolve - https://docs.gradle.org/current/userguide/toolchains.html#sub:download_repositories - it's hard to extract it into version catalog as it's applied in settings.gradle.kts....

Fix enum test, add toolchains and running on JDK 21

---

dokka-integration-tests/cli/src/integrationTest/kotlin/org/jetbrains/dokka/it/cli/CliIntegrationTest.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/content/inheritors/ContentForInheritorsTest.kt

Fixes #2571
Note, that only integration test was added, as it's not easily possible to test it via unit test:
1. because we need to materialise files somewhere and to use relative paths of them, we need to materialise them somewhere in project directory - which is not good
2. all our test-apis convert all paths to absolute before providing them to configuration
I think, that for this case, integration test will be enough, as supporting testing relative paths will cause a lot of refactoring for sole of this specific use-case.
I have also checked code around other files provided via configuration, and looks like only sourceRoots are now affected. But may be we need to add more tests for relative paths for other properties (classpath, samples, includes, etc).
One more additional note for …

Support for providing sourceRoots as relative paths

---

dokka-subprojects/analysis-java-psi/api/analysis-java-psi.api
dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/JavadocTag.kt
dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/doccomment/JavaDocComment.kt
dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/JavaDocCommentParser.kt
dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/doctag/InheritDocTagResolver.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/jvm/java/JavadocAnalysisTest.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/jvm/java/JavadocParamAnalysisTest.kt

Support parsing javadoc `@param` for classes

---

dokka-integration-tests/gradle/projects/it-basic/src/main/kotlin/RootPackageClass.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/documentable/SpecialCharacterTest.kt
dokka-subprojects/analysis-kotlin-descriptors/build.gradle.kts
dokka-subprojects/analysis-kotlin-symbols/build.gradle.kts
gradle/libs.versions.toml

fixes #3329 
I've added description of the issue directly in code (same for both K1 and K2 modules). Will duplicate/expand on it here:
Related KT issue: https://youtrack.jetbrains.com/issue/KT-47150
What is the issue: `kotlin-compiler` artifact includes unshaded (not-relocated) STRIPPED `fastutil` dependency, STRIPPED here means, that it doesn't provide full `fastutil` classpath, but only a part of it which is used and so when shadowJar task is executed it takes classes from `fastutil` from `kotlin-compiler` and adds it to shadow-jar then adds all other classes from `fastutil` coming from `markdown-jb`, but because `fastutil` from `kotlin-compiler` is STRIPPED, some classes (like `IntStack`) lacks some methods and so such classes are not replaced afterward by `shadowJar` task - it visits …

Overcome fastutil issue

---

dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/model/documentableUtils.kt
dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/pages/contentNodeProperties.kt
dokka-subprojects/plugin-base/api/plugin-base.api
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/translators/documentables/DefaultPageCreator.kt
dokka-subprojects/plugin-base/src/test/kotlin/content/ExtensionsTest.kt

Fixes #3187 
**Context**
During building Classlike page, separate tabs for `members` and `members+extensions` are configured inside `divergentBlock`. Functions/Properties are divided in members and extensions by calling `Documentable.isExtension` (returns if function/property is extension or not based on existence of receiver).
**Problem**
Kotlin also has member extensions, which should be shown on `members` page, but `Documentable.isExtension` for them returns `true` because, you know, they are extensions.
To better illustrate the problem, here is a sample code:
```kotlin
interface Receiver {
// 1. just ordinary member function
// receiver = null
fun memberFunction()
// 2. member extension function
// receiver = Int
fun Int.intExtensionFunction()
// 3. member extension function (yes it's …
```

Render member extensions correctly

---

dokka-subprojects/plugin-base/src/main/resources/dokka/styles/style.css

fixes #3228 
By the way, I was able to reproduce it both in Firefox and Chrome. And now it'll be fixed in both browsers

fix: aligned inline code vertically #3228

---

dokka-subprojects/plugin-base-frontend/src/main/components/search/search.scss

fix: made empty search notification visible in both themes

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/NavigationPage.kt
dokka-subprojects/plugin-base/src/main/resources/dokka/styles/style.css

fix: proper strikethrough in navigation for Fifefox #3156

---

README.md

Fix minor typo, `LICENSE` -> `LICENSE.txt`
[Rendered preview](https://github.com/Kotlin/dokka/blob/fix/readme-license-link/README.md)

fix link to license in readme badge

---

build-logic/src/main/kotlin/dokkabuild.base.gradle.kts
build-logic/src/main/kotlin/dokkabuild.test-integration.gradle.kts
build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt
dokka-integration-tests/gradle.properties
dokka-integration-tests/gradle/README.md
dokka-integration-tests/gradle/build.gradle.kts

Updates a couple of integration test properties to use the DokkaBuildProperties class. 
* ~#3419~
* #3418

KT-64377 - Update Dokka build properties

---

dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/BuildVersions.kt
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestEnvironment.kt
dokka-integration-tests/utilities/build.gradle.kts
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/AbstractIntegrationTest.kt
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/TestOutputCopier.kt
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/gitSubmoduleUtils.kt
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/processUtils.kt

These utilities aren't published, so strict API checking isn't necessary.
Removing explicit API mode allows for more concise code. It also helps with verifying that code is actually required.
For example - `fun AbstractIntegrationTest.copyGitDiffFileToParent()` and `AbstractIntegrationTest.applyGitDiffFromFile()` could be private, but IJ because explicit API mode was enabled it didn't suggest they could be private.

KT-64377 disable explicit api in test utils

---

dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationJsonTest.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/DokkaConfigurationSerializableTest.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt

The idea is at least to not suggest usage of deprecated in JDK 20 API. While it's not full direct replacement (as far as I understand by reading deprecation note on URL class), this should be fine for how we use it in Gradle plugin.
I've also investigated this migration in all code base here - https://github.com/Kotlin/dokka/commit/521d9e5f743915f38c92c007c40688b1b194ee8a
Though, I've decided not to do this, because of some questionable changes there. In the end it will be fixed in https://github.com/Kotlin/dokka/issues/2993. I will add this link there to be aware of the scope of the changes.

Replace usages of deprecated in JDK 20 `java.net.URL` constructor in Gradle runner

---

dokka-integration-tests/gradle/src/integrationTest/kotlin/org/jetbrains/dokka/it/gradle/kotlin/SerializationGradleIntegrationTest.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt
dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt

[K2] Support `[this]` link for extensions

---

CONTRIBUTING.md
build-settings-logic/build.gradle.kts
build-settings-logic/settings.gradle.kts
build-settings-logic/src/main/kotlin/DokkaBuildSettingsProperties.kt
build-settings-logic/src/main/kotlin/dokkasettings.build-cache.settings.gradle.kts
build-settings-logic/src/main/kotlin/dokkasettings.gradle-enterprise.settings.gradle.kts
dokka-integration-tests/settings.gradle.kts
dokka-runners/runner-cli/settings.gradle.kts
dokka-runners/runner-gradle-plugin-classic/settings.gradle.kts
dokka-runners/runner-maven-plugin/settings.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

Use JetBrains Gradle Enterprise for builds.
This should improve the build speeds both for local development and on CI.
* Introduces a new `build-settings-logic` project for settings conventions.
It's named so that it's next to the existing `build-logic`.
* Convention plugins for Build Cache and Gradle Enterprise copied from https://github.com/JetBrains/kotlin/
* https://github.com/JetBrains/kotlin/blob/2675531624d42851af502a993bbefd65ee3e38ef/repo/gradle-settings-conventions/build-cache/src/main/kotlin/build-cache.settings.gradle.kts
* https://github.com/JetBrains/kotlin/blob/19073b96a7ed53dbda61337465ca898c1482e090/repo/gradle-settings-conventions/gradle-enterprise/src/main/kotlin/gradle-enterprise.settings.gradle.kts

Configure JetBrains Gradle Enterprise & Build Cache

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt
dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt

[K2] Fix order of KDoc link candidates

---

dokka-integration-tests/cli/build.gradle.kts
dokka-integration-tests/cli/projects/it-cli/src/main/kotlin/RootPackageClass.kt
dokka-subprojects/analysis-kotlin-descriptors/build.gradle.kts
dokka-subprojects/analysis-kotlin-symbols/build.gradle.kts

Fixes: https://github.com/Kotlin/dokka/issues/3329#issuecomment-1906072161
I've updated the description of the fix in files, where the workaround is applied.
Also there are two changes in CLI integration tests:
1. set `isTransitive = false` when building `shadowJar` which is used as `pluginsClasspath` in CLI - this way we can better control/understand which dependencies are provided to CLI. This will help to find issues with missing dependencies in future.
2. support for running tests with K2 with property - this was done to correctly test, that the the current fix works.
If needed, I can split CLI integration tests changes to separate PR.

Fix fastutil shadowing

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/transformers/pages/DefaultSamplesTransformer.kt
dokka-subprojects/plugin-javadoc/api/plugin-javadoc.api
dokka-subprojects/plugin-javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/JavadocPlugin.kt
dokka-subprojects/plugin-javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocClasslikeTemplateMapTest.kt

This is a laconic solution to avoid an error message (#3466) for Kotlin samples in unstable Javadoc format. There are 2 problems.
1. Javadoc's content model does not contain samples links at all. It should contain something like `samplesSectionContent` in the base plugin.
2. Sample Transformer from the base plugin knows nothing about Javadoc's content model. see  `DefaultSamplesTransformer.dfs`, e.g. `JavadocContentGroup` is unavailable from the base plugin.

[Javadoc] Ignore Kotlin samples

---

dokka-subprojects/plugin-base-frontend/build.gradle.kts
dokka-subprojects/plugin-base/build.gradle.kts
gradle/libs.versions.toml

- bump Gradle Node Plugin version
- fix npmInstall caching
- amend Gradle Node Plugin settings to allow npm (not Gradle) to manage `node_modules/` caching
- add path-sensitivity to task inputs, so cache can be re-used across machines
- add property names to task inputs (easier debugging/reporting)
This should improve build performance, and avoid an issue where npmInstall could not be up-to-date.
https://ge.jetbrains.com/s/rumw2jkk7scia/timeline?details=xhxfjcjtknpfe

improve NPM Gradle task caching

---

.github/workflows/preview-publish-ga.yml
.github/workflows/preview-publish-web-s3.yml
.gitmodules
.idea/vcs.xml
build-logic/build.gradle.kts
build-logic/src/main/kotlin/dokkabuild/tasks/GitCheckoutTask.kt
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/gradle/projects/coroutines/.gitignore
dokka-integration-tests/gradle/projects/serialization/.gitignore
dokka-integration-tests/maven/build.gradle.kts
dokka-integration-tests/maven/projects/biojava/.gitignore

This improves the experience when running Dokka integration tests. 
* Automatically checking out the external projects used for integration tests means that anyone can checkout and run all tests without needed to setup and configure git submodules.
* Because the commitId is defined in code it's easier to see what version the external projects are used.
I have made the minimal number of changes in this PR to make it small and focused. I plan to replace the git-diff files with a less fragile alternative in a later PR.
I thought there were some instructions on how to checkout and setup the Git submodules, but I couldn't find any. Do any docs need to be updated?

Replace git submodules for test projects with custom GitCheckoutTask

---

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/DefaultPsiToDocumentableTranslator.kt

I presume that `parallelMapNotNull { it }` does nothing.
Alternatively: is it supposed to do something, but it doesn't?

Remove no-op `parallelMapNotNull { it }`

---

dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt

Limit Gradle Workers:
- decreases the memory pressure 
- prevents daemons from previously failed build lingering on TeamCity agents, which then sabotage future builds by preventing directories from being deleted.
The aim is improved CI test consistency, which might increase overall test execution duration. I expect that the increased duration will be mitigated by other measures (aiming for enabling configuration-cache to allow for parallel test execution, and build-cache compliance allowing for avoiding re-running tests where possible).

Gradle TestKit: reduce daemon timeouts

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/model/ConstructorsTest.kt

#3452 
#3379 (the tests in #3500)

[K2] Fix missing `@constructor` documentation for primary constructors

---

dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/SourceRootChecker.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/TagsAnnotations.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/CompilerDescriptorAnalysisPlugin.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/K1SourceRootIndependentChecker.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/SourceRootIndependentChecker.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/SymbolsAnalysisPlugin.kt

The pre-generation check throws `DokkaException` [here](https://github.com/Kotlin/dokka/blob/8e5c63d035ef44a269b8c43430f43f5c8eebfb63/dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/generation/SingleModuleGeneration.kt#L105). Probably it could be  a logging error messages instead of an exception. Need to discuss.

[K2] Add a check that source roots do not intersect

---

dokka-runners/runner-maven-plugin/build.gradle.kts
dokka-subprojects/core/build.gradle.kts
dokka-subprojects/core/src/main/resources/META-INF/dokka/dokka-version.properties

Preparing Dokka build-logic (not Dokka Gradle Plugin!) for Configuration Cache
Replace [usages of Project during task execution](https://docs.gradle.org/8.6/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution) with a Provider.
Also, replace custom text find/replace with Gradle `expand()` util (matches existing usage in runner-maven-plugin project).

remove usages of Project during task-execution

---

dokka-subprojects/plugin-base/api/plugin-base.api
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/JvmSignatureUtils.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/KotlinSignatureProvider.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/signatures/KotlinSignatureUtils.kt
dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt
dokka-subprojects/plugin-javadoc/api/plugin-javadoc.api
dokka-subprojects/plugin-kotlin-as-java/api/plugin-kotlin-as-java.api
dokka-subprojects/plugin-kotlin-as-java/src/main/kotlin/org/jetbrains/dokka/kotlinAsJava/signatures/JavaSignatureUtils.kt

Fixes #3426
There are 2 cases when annotation is not rendered and so no `constructor` keyword should be rendered:
1. when annotation is not annotated with `MustBeDocumented`
2. when annotation is ignored (and so handled in some other way, like `Deprecated`)
Note: PR has small API/ABI changes (no breaking changes), that's because ignored annotations are ignored later in pipeline, only during rendering. We can't ignore annotations in `JvmSignatureUtils`, as we need all annotations in other places to make a special handling of those ignored annotations (like `Deprecated`).
Also, we can introduce something like `Annotation.shouldBeRendered` instead of `Annotation.isIgnored` inside `JvmSignatureUtils`, but to use it under the hood in `annotationsInline`/`annotationsBlock` we will need to break …

Fix checking for annotations when rendering constructor keyword

---

build-logic/src/main/kotlin/dokkabuild/tasks/MvnExec.kt
dokka-runners/runner-maven-plugin/build.gradle.kts

Update tasks for building the Dokka Maven plugin, so that Build Cache works across machines.
(Alternative title: TIL that the compileKotlin task output includes caches)
- Update MvnExec task:
- separate classes/resources inputs
- filter and annotate classes input:
1. only include `.class` files (the compileKotlin file includes caches)
2. annotate with `@Classpath` so Gradle will be able to normalize the files
- Update `generatePom` task to manually register the version inputs, to ensure Gradle will re-run the task if they change.
- Update `helpMojoResources` to exclude `maven-plugin-help.properties`, because it contains a property with an absolute file path, meaning that Build Cache cannot be shared between CI and local machines.

Improve Build Caching of Maven plugin tasks

---

build-logic/build.gradle.kts
build-settings-logic/build.gradle.kts

`build-settings-logic/build.gradle.kts` is missing a JVM toolchain, which means in some cases builds are not reproducible. This may be causing Build Cache misses.
Also, update the syntax to use the new, shorter util function.

set jvmToolchain 11 for build-settings-logic

---

dokka-subprojects/analysis-kotlin-api/api/analysis-kotlin-api.api
dokka-subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/KotlinAnalysisPlugin.kt
dokka-subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/sample/SampleRewriter.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/sample/SampleRewriterTest.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/TestProject.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/analysis/TestProjectAnalyzer.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/java/JavaTestProject.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/kotlin/KotlinJvmTestProject.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/jvm/mixed/MixedJvmTestProject.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/impl/DescriptorSampleAnalysisEnvironment.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolSampleAnalysisEnvironment.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/transformers/pages/DefaultSamplesTransformer.kt

#3108 
Finally I have decided to use `SampleRewriter` as an extension point.
In case of using it as an argument of `resolveSample`:
- I am not sure `SampleTransformer` will not changed in the future. It also changes pages resources. Maybe it even makes sense to get rid of it or transform it to `RunnableSampleTransformer`
- With overriding of some `SampleTransformer` 's functions we can have the same situation like with `HtmlRender`
- Using an extension point is more obvious for users to rewrite samples

Introduce API to rewrite samples

---

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/util/PsiUtil.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/DRIFactory.kt
dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt
dokka-subprojects/plugin-base/src/test/kotlin/model/JavaTest.kt

Fixes  #3004
The PR is based on @nea89o's solution #3371.
KDoc links to a package is a question of KDoc specification #3455.
They are already fixed in K2, bot not in K1.

[K1] Fix KDoc and Javadoc link to a package

---

docs/topics/dokka-plugins.md
docs/topics/formats/dokka-markdown.md
docs/topics/runners/dokka-maven.md

fix for broken link, typo, and sample code

fix for broken link, typo, and sample code

---

dokka-subprojects/plugin-base/api/plugin-base.api
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt
dokka-subprojects/plugin-base/src/test/kotlin/renderers/html/FormattingUtilsTest.kt

This PR makes underscore separated names breakable after each underscore similar to how names separated by dots are rendered.
Resolves #3093.

Fix overflow of long underscore separated names in HTML

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/AnalysisContext.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
gradle/libs.versions.toml

**Fixed**(_Blocked by https://youtrack.jetbrains.com/issue/KT-65561/Analysis-API-dummy.kt-is-not-a-physical-file_)
**Changes:**
https://github.com/JetBrains/kotlin/commit/bba5447b12ff227c3b159159d9b952d07dfd0116 : `applicationDisposable` parameter is removed from `buildStandaloneAnalysisAPISession` because:
- It wasn’t used as the actual disposable for the shared application under the hood. In fact, logically it was just a second project disposable.
- The client should not need to care about application disposal, as signaling that the project is no longer used via the projectDisposable is sufficient.

Update Analysis API to 2.0.20-dev-7

---

build-logic/src/main/kotlin/dokkabuild.base.gradle.kts
build-logic/src/main/kotlin/dokkabuild.publish-base.gradle.kts
build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt
build-settings-logic/src/main/kotlin/dokkasettings.gradle-enterprise.settings.gradle.kts
dokka-runners/runner-maven-plugin/build.gradle.kts
dokka-subprojects/core/build.gradle.kts
gradle.properties

Enables [Configuration Cache](https://docs.gradle.org/8.7/userguide/configuration_cache.html) for Dokka's build configuration.
- Enabled CC.
- Set CC error level to 'warn'. (Future build script or plugin changes might cause CC issues. Although such problems should be fixed, I'd rather that developers aren't blocked with CC errors.)
- Updated some build script config to avoid CC issues
- update usages of project version, to avoid `Task.getProject()`
- move variables into `gradleEnterprise {}` block, to avoid references to the build script context
- Disabled CC for remote Maven publishing tasks. Remote Maven Repos (particularly Maven Central) struggle to cope with parallel uploads, and artifacts may be lost, or split. To prevent issues, CC is manually disabled for all publishing tasks.
- …

Enable Configuration Cache for Dokka Build

---

dokka-subprojects/plugin-javadoc/src/main/resources/views/class.korte

The rendered signature already contains the correct link, but was accidentally wrapped in another `<a>` with a placeholder `href` link. This PR removes that dummy `<a>` wrapper.

Remove `<a href="TODO">` in enum constant summary

---

.github/workflows/check-api.yml
.github/workflows/check-gradle.yml
.github/workflows/examples-build.yml
.github/workflows/gh-pages-deploy-dev-docs.yml
.github/workflows/gh-pages-deploy-examples.yml
.github/workflows/preview-cleanup-web-s3.yml
.github/workflows/preview-publish-ga.yml
.github/workflows/preview-publish-web-s3.yml
.github/workflows/qodana.yml
.github/workflows/tests-smoke.yml
.github/workflows/tests-thorough.yml

this will remove warnings like this and so future errors
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, gradle/gradle-build-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Update GitHub workflows to use latest versions of actions

---

dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/documentable/ObviousFunctionsTest.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/enums/KotlinEnumsTest.kt
dokka-subprojects/plugin-base/src/test/kotlin/model/InheritorsTest.kt
dokka-subprojects/plugin-base/src/test/kotlin/transformers/ObviousAndInheritedFunctionsDocumentableFilterTest.kt

Due to KT-63741 https://github.com/JetBrains/kotlin/commit/7056ad5325324bb8162db4cef2b5bcf02b3c5483

[K2] Fix DRI for override symbols

---

dokka-subprojects/plugin-base/src/main/resources/dokka/styles/style.css

Wrap links and code blocks to prevent two-dimensional scrollbar from appearing on small screens.
Solves violation number 5 in this issue: https://github.com/Kotlin/dokka/issues/3414

Accessibility: Wrap links and code blocks

---

dokka-subprojects/plugin-base/src/main/resources/dokka/styles/style.css

Adds an outline to section-tabs when they are focused. The color matches the underline color when they are hovered over. 
Solves violation number 4 in this issue: https://github.com/Kotlin/dokka/issues/3414

Accessibility: add outline when section-tab is focused

---

.gitignore
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/gradle/projects/it-android-0/gradle.properties
dokka-integration-tests/gradle/projects/it-basic-groovy/gradle.properties
dokka-integration-tests/gradle/projects/it-basic/gradle.properties
dokka-integration-tests/gradle/projects/it-collector-0/gradle.properties
dokka-integration-tests/gradle/projects/it-configuration/gradle.properties
dokka-integration-tests/gradle/projects/it-js-ir-0/gradle.properties
dokka-integration-tests/gradle/projects/it-multimodule-0/gradle.properties
dokka-integration-tests/gradle/projects/it-multimodule-1/gradle.properties
dokka-integration-tests/gradle/projects/it-multimodule-versioning-0/gradle.properties
dokka-integration-tests/gradle/projects/it-multiplatform-0/gradle.properties
dokka-integration-tests/gradle/projects/it-sequential-tasks-execution-stress/gradle.properties
dokka-integration-tests/gradle/projects/it-wasm-js-wasi-basic/gradle.properties
dokka-integration-tests/gradle/projects/template.settings.gradle.kts
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
dokka-integration-tests/gradle/src/testTemplateProjectTasksExecutionStress/kotlin/SequentialTasksExecutionStressTest.kt
dokka-integration-tests/maven/projects/it-maven/pom.xml
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/KotlinNativeDistributionAccessor.kt
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinClasspathUtils.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/AndroidAutoConfigurationTest.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilderTest.kt
dokka-runners/runner-gradle-plugin-classic/src/test/kotlin/org/jetbrains/dokka/gradle/utils/AgpUtils.kt
dokka-subprojects/analysis-kotlin-descriptors-ide/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/ide/DokkaResolutionFacade.kt
gradle/libs.versions.toml

* Bumps KGP to 2.0.0-RC1
* Bumps kotlin-compiler to 2.0.0-RC1 (only K1)

Bump Kotlin versions to 2.0.0-RC1

---

build-logic/src/main/kotlin/dokkabuild.publish-base.gradle.kts

Due to Gradle running publishing tasks in parallel, multiple staging repositories can be created within a couple of seconds with all artifact files scattered throughout them. Even though the publishing in done on the same build agent.
Interestingly enough, setting `-Dorg.gradle.parallel=false` didn't help, I believe it's due to us using included builds, but I'm not sure.
Setting `--max-workers=1` additionally did help, but significant time was spent to find and test this solution.
Given it's easy to forget to set these params (especially when adding new build steps in TC), I think it's much easier to just allow to publish to a predefined staging repo, which will be created before the publishing build is run (as a prerequisite).

Allow publishing to a pre-defined staging repository

---

build-logic/src/main/kotlin/dokkabuild.publish-base.gradle.kts

(continuation from https://github.com/Kotlin/dokka/pull/3562#issuecomment-2049268041)
This PR drops the workaround for disabling configuration cache during publishing. There were proposals to replace it with `MavenPublishLimiter`, but it looks like it's not needed _for now_? We'll be publishing to Maven Central with `DOKKA_MVN_CENTRAL_REPOSITORY_ID`, and Gradle Plugin Portal and Space seem to handle parallelization well
___
I'm definitely missing some lazy verifications around publishing in Gradle :) It'd be nice to check that `DOKKA_MVN_CENTRAL_REPOSITORY_ID` is set and not blank when publishing to Maven Central, then we would be able to drop `https://oss.sonatype.org/service/local/staging/deploy/maven2/` completely. But since the configuration is resolved during build time, it doesn't …

Remove a publishing-related config-cache disabler

---

build-logic/src/main/kotlin/dokkabuild.publish-base.gradle.kts

Currently, the requirement for signing is set as
```kotlin
setRequired(provider { !project.version.toString().endsWith("-SNAPSHOT") })
```
which works fine when it comes to day-to-day stuff, but I found it to be insufficient when preparing the 1.9.20 release.
In release branches, the `version` property doesn't have any suffixes, example here: https://github.com/Kotlin/dokka/blob/1.9.20/gradle.properties#L7
It is needed because there are cases when this version is also used for publishing of other things that are not related to artifacts, such as publishing [developer docs](https://github.com/Kotlin/dokka/blob/5d4dc7148adf6abc9b579eb2948cca6d5fb2c4e8/docs-developer/build.gradle.kts#L13) (updating the documentation in the release branch should lead to the docs being deployed under the …

Do not require signing artifacts when publishing locally

---

dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/translators/DefaultDescriptorToDocumentableTranslatorTest.kt

Updated the `DefaultDescriptorToDocumentableTranslator` to avoid throwing an exception when encountering recursive type aliases. The changes ensure that the `defaultType` is safely accessed. Also, added a new test for this scenario to avoid regression in the future.

[K1] Handle exception for recursive type aliases

---

dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt

Two new tests have been added in `LinkTest.kt`. One is to verify that a KDoc link correctly points to Java annotation methods, and the second test is for Java synthetic properties.

Add unit tests for KDoc links to Java

---

dokka-subprojects/analysis-kotlin-symbols/README.md

#3559
The README file for the 'dokka-subprojects/analysis-kotlin-symbols' subproject has been updated. This includes an explanation of the project's entry point, instructions on how to run tests with a custom version of Analysis API, and guidelines on how to build and publish the project locally.

Update README in `analysis-kotlin-symbols`

---

.github/workflows/preview-publish-web-s3.yml

Adds a GitHub Actions workflow that publishes the preview of the docs generated for the `ui-showcase` project to S3, similarly to how it's done for coroutines and serialization

Publish previews for the ui-showcase test project

---

dokka-subprojects/analysis-kotlin-api/api/analysis-kotlin-api.api
dokka-subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/sample/SampleAnalysisEnvironment.kt
dokka-subprojects/analysis-kotlin-api/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/sample/SampleAnalysisEnvironmentCreator.kt
dokka-subprojects/analysis-kotlin-api/src/test/kotlin/org/jetbrains/dokka/analysis/test/sample/SampleAnalysisTest.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/impl/DescriptorSampleAnalysisEnvironment.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolSampleAnalysisEnvironment.kt
dokka-subprojects/core/api/dokka-core.api
dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/DelicateDokkaApi.kt

Fixes #3573
minor changes applied to original branch.
Note: `DelicateDokkaApi` description was taken from coroutines with minimal changes - it's description matches perfectly for our use cases.
Note: I haven't implemented mine suggestion from https://github.com/Kotlin/dokka/issues/3573#issuecomment-2074718683, as may be `Delicate` annotation is enough and we don't need to do additional tracking for niche use-case

Provide a way to manually create SampleAnalysisEnvironment

---

build-logic/src/main/kotlin/dokkabuild.test-cli-dependencies.gradle.kts
build.gradle.kts
dokka-integration-tests/cli/build.gradle.kts
dokka-integration-tests/cli/src/integrationTest/kotlin/org/jetbrains/dokka/it/cli/CliIntegrationTest.kt
dokka-integration-tests/cli/src/main/kotlin/org/jetbrains/dokka/it/cli/AbstractCliIntegrationTest.kt
dokka-integration-tests/cli/src/main/kotlin/org/jetbrains/dokka/it/cli/jsonBuilder.kt
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/settings.gradle.kts
dokka-integration-tests/utilities/build.gradle.kts
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/processUtils.kt
dokka-integration-tests/utilities/src/main/kotlin/org/jetbrains/dokka/it/systemProperties.kt
dokka-runners/runner-cli/src/test/kotlin/org/jetbrains/dokka/CliTest.kt
dokka-subprojects/plugin-base/build.gradle.kts

Part of KT-64200
- Migrate the CLI integration tests away from the custom integration test convention (which is not build-cache compatible) to use JVM Test Suites.
- Remove shadowing, replace with passing in the JARs via system properties. (a custom CommandLineArgumentProvider is confusing and overly complicated, but it's required to satisfy Gradle input normalization, so that the build-cache can be re-used.)
- Simplify `processUtils.kt` - the coroutines logic isn't necessary since the entrypoint just used `runBlocking {}`.
- move `jsonBuilder.kt` test-util into `src/main`, since it's not a test
- Rename `CliIntegrationTest` to `CliTest` (it wasn't an integration test, and the name was confusing compared to the actual `CliIntegrationTest`)
- The JSON config tests a `.json` in the …

Update CLI Integration Tests to use JVM Test Suites

---

dokka-subprojects/plugin-base/src/main/resources/dokka/scripts/platform-content-handler.js

fixes the problem with runnable code snippets detected in #3535 and described in https://github.com/Kotlin/dokka/pull/3553

fix: made code samples runnable (#3535)

---

CONTRIBUTING.md
build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/gradle/projects/coroutines/coroutines.diff
dokka-integration-tests/gradle/projects/serialization/serialization.diff
dokka-integration-tests/gradle/projects/template.settings.gradle.kts
dokka-integration-tests/gradle/projects/ui-showcase/README.md
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt

An addition for https://github.com/Kotlin/dokka/pull/3583.
For UI showcase project, after PR is merged, it will be possible to run it like this:
```bash
./gradlew :dokka-integration-tests:gradle:testUiShowcaseProject -Porg.jetbrains.dokka.integration_test.dokkaVersionOverride=2.0.0-dev-329
```
It's also possible to add `org.jetbrains.dokka.integration_test.dokkaVersionOverride=2.0.0-dev-329` to `dokka-integration-tests/gradle.properties` (but, it's less recommended, as it could be unnoticed and affect tests behaviour)
Note: PR is based on master and not `ui-test-project` branch, so `testUiShowcaseProject` will be not available.
Note regarding implementation:
* it's easier to allow overriding version for all integration tests and not just for single `ui-showcase` project. Additionally it …

Allow overriding a Dokka version in integration tests

---

dokka-subprojects/analysis-java-psi/build.gradle.kts
dokka-subprojects/analysis-kotlin-descriptors/build.gradle.kts
dokka-subprojects/analysis-kotlin-symbols/build.gradle.kts
gradle/libs.versions.toml

Fixes #3508
Checked `shadowJar` contents before and after this change: the only difference is in the absence of `log4j` classes.
Note: we still include 2 classes from `log4j` - `Level` and `Priority` - they are coming from `kotlin-compiler` and don't trigger any dependency vulnerability checks.
We can drop those classes, and tests are working fine without them, but I've decided not to do this, as if they are used somehow in some situation, it will cause `No class found` exception.
Additionally, I've updated some comments and removed confusing dependencies which are not needed in `analysis-kotlin-symbols`, as they are coming from `analysis-java-psi` and `kotlin-compiler` anyway - no changes to those classes in final `shadowJar` have happened.

Remove log4j coming from intellij dependencies

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/AnnotationTranslator.kt
gradle/libs.versions.toml

After https://youtrack.jetbrains.com/issue/KT-61775/

Update Analysis API to 2.0.20-dev-3206

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt

After https://youtrack.jetbrains.com/issue/KT-60483/Analysis-API-add-isTailrec-property-to-KtFunctionSymbol

[K2] Replace workaround for `tailrec` modifier

---

dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/translator/DefaultDescriptorToDocumentableTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt

fixes #3360
After short investigation I found out that the issue is on our side - we had our own extension properties for `expect/actual` handling which were using just PSI information.
Accessors via Analysis API were added in https://youtrack.jetbrains.com/issue/KT-54846 (Fix in builds: 1.9.20-dev-7565).
There were no issues with functions, because `isExpect/isActual` were used there after update to Analysis API 1.9.20-* (because they were introduced as member properties and so they come before our extension properties during overload resolution). With properties the story is a bit different, because there is no `isExpect/isActual` for `KtPropertySymbol` which is used in our code, the exists only on `KtKotlinPropertySymbol`
So looks like upstream issue can be closed

Get information about expect/actual for properties in K2 via Analysis API and not via PSI

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/SyntheticKDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolFullClassHierarchyBuilder.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolSampleAnalysisEnvironment.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/AnnotationTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TranslatorError.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeReferenceFactory.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeTranslator.kt
gradle/libs.versions.toml

More details are in [the breaking changes document](https://docs.google.com/document/d/1xy2Fwtns32SVWR8uUuh_cA92OcbLHHkz_cy8lJ8k0aU/edit#heading=h.utji327bt6bm). 
The change broke [our scheduled tests K2 ](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_Dokka_ScheduledDokkaTestsK2?mode=builds#all-projects)

[K2] Update Analysis API to 2.0.20-dev-4579 and replace the `Kt` prefix with `Ka`

---

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/DokkaPsiParser.kt
dokka-subprojects/analysis-kotlin-descriptors-compiler/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/descriptors/compiler/configuration/AnalysisEnvironment.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
gradle/libs.versions.toml

The latest AA built with the newer version of IntelliJ Platform so we need to update it. This transitively requires updating a kotlin-compiler version used for kotlin K1 analysis because we share java analysis between K1 and K2 kotlin analyses.

Migrate to the latest AA (2.0.20-dev-5135) and IntelliJ Platform (233.13135.103)

---

dokka-subprojects/analysis-kotlin-symbols/build.gradle.kts
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/SyntheticKDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/moduledocs/ModuleAndPackageDocumentationParsingContext.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/AnalysisContext.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolExternalDocumentablesProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/services/SymbolFullClassHierarchyBuilder.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/AnnotationTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeReferenceFactory.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/TypeTranslator.kt
gradle/libs.versions.toml

List of changes:
- KT-68462
- partially KT-68884 and others

Update Analysis API to 2.0.20-dev-6911

---

dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
dokka-integration-tests/maven/projects/it-maven/pom.xml
gradle/libs.versions.toml

Note: `kotlin-compiler` version wasn't updated, as Beta1 doesn't contain IntelliJ platform update and so it should be updated when Beta2 will be released.

Kotlin 2.0.20-Beta1

---

.github/workflows/preview-publish-ga.yml

Update the GitHub Action to use the new specific Gradle task for testing BioJava introduced in #3581.

Fix publishing BioJava preview

---

dokka-integration-tests/gradle/projects/ui-showcase/kmp/build.gradle.kts
dokka-integration-tests/gradle/projects/ui-showcase/kmp/src/macosMain/kotlin/org/jetbrains/dokka/uitest/kmp/CInterop.kt
dokka-integration-tests/gradle/src/testUiShowcaseProject/kotlin/UiShowcaseIntegrationTest.kt

TL;DR;
This is needed because of the issue with rendering expect/actual. I would propose for now to just add `macosArm64` target and resolve underlying issue during implementation of https://github.com/Kotlin/dokka/issues/3386 for Dokka K2. We will anyway need to do something with such sourceSets.
In https://github.com/Kotlin/dokka/pull/3662 test started to fail on `ui-showcase` module because of `ERROR CLASS`.
Checking the page where the fail happened, I found that for some reason `ui-showcase` currently (on `master`) doesn't contain an actual declaration for `macos` sourceSet:
`asyncWithDelay` doesn't have `macos` tab, but `actual` declaration exists in sourceSet.
If we run the same test with the changes from https://github.com/Kotlin/dokka/pull/3662, `macos` tab is now appeared but …

Use both macos targets in ui-showcase

---

dokka-integration-tests/gradle/projects/it-multimodule-versioning-0/build.gradle
dokka-integration-tests/gradle/src/testTemplateProjectMultimoduleVersioning/kotlin/Versioning0IntegrationTest.kt
dokka-subprojects/plugin-versioning/README.md
dokka-subprojects/plugin-versioning/api/plugin-versioning.api
dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/DefaultPreviousDocumentationCopyPostAction.kt
dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/VersioningConfiguration.kt
dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/VersioningStorage.kt

Fixes #3692 
* Introduce a new parameter `olderVersionsDirName` in `VersioningConfiguration` to customize the directory name for older versions HTMLs
* Add integration test with different folder names

Support specifying custom folder name for older versions for versioning plugin

---

.github/workflows/preview-publish-ga.yml
.github/workflows/preview-publish-web-s3.yml
dokka-integration-tests/gradle/src/testUiShowcaseProject/kotlin/UiShowcaseIntegrationTest.kt

In https://github.com/Kotlin/dokka/pull/3662 test started to fail on ui-showcase module because of `ERROR CLASS`.
This was fixed in https://github.com/Kotlin/dokka/pull/3663 and everything was fine locally.
But on CI we were building `ui-showcase` on Linux - and so before #3662 there were no `macOS` specific declarations there.
So we need to build it on macOS.
Looks like we need to do the same on TC. @adam-enko could you help here? Is it possible to run only `UiShowcaseIntegrationTest` on TC on macOS? Other tests should work fine with linux runner.

use `macos-latest` for `ui-showcase` build on CI

---

gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

This will help reduce the GitHub Action cache pressure ([see discussion here](https://www.linen.dev/s/gradle-community/t/22739806/i-ve-successfully-configured-a-remote-build-cache-node-for-k#76ae482e-978e-48a9-a27a-93c943cd9c0c))

Update Gradle to v8.9

---

build-logic/src/main/kotlin/dokkabuild/tasks/GitCheckoutTask.kt

Currently, GitCheckoutTask might not re-run if the checked-out repository is dirty. This can cause invalid test results.
So, update GitCheckoutTask to re-run if the repo does not exist, is invalid, or contains any modifications.

Update GitCheckoutTask, so it re-runs if the repo is dirty

---

dokka-subprojects/plugin-base-frontend/README.md
dokka-subprojects/plugin-base-frontend/create-component.mjs
dokka-subprojects/plugin-base-frontend/package-lock.json
dokka-subprojects/plugin-base-frontend/package.json
dokka-subprojects/plugin-base-frontend/postcss.config.js
dokka-subprojects/plugin-base-frontend/stylelint.config.js
dokka-subprojects/plugin-base-frontend/webpack.config-ui-kit.js

This allows to run `npm run start:ui-kit` in terminal and see ui-showcase's version of Dokka in browser right away and then develop ui kit components as usual frontend component enjoing live-reload feature 
Also this allows to quickly create templates for new ui-kit components
Example of usage

build: added dev server for ui kit development

---

dokka-subprojects/plugin-javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/JavadocContentToTemplateMapTranslator.kt

On one of our JavaDoc pages ([THEOplayerConfig.html](https://www.theoplayer.com/docs/theoplayer/v7/api-reference/android/com/theoplayer/android/api/THEOplayerConfig.html)), we noticed a broken link in the Nested Class Summary.
The Java source looks like this:
```java
package com.theoplayer.android.api;
/**
* The THEOplayer Configuration API.
*/
public interface THEOplayerConfig {
/**
* The builder for {@link THEOplayerConfig}.
*/
class Builder { }
}
```
The rendered HTML for the Nested Class Summary looks like this:
```html
<h3>Nested Class Summary</h3>
<div class="memberSummary">
<table>
<caption><span>Nested Classes</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colSecond" scope="col">Class</th>
<th …
```

Fix links in nested class summary not resolved correctly

---

docs-developer/docs/developer_guide/architecture/data_model/documentable_model.md
docs-developer/docs/developer_guide/architecture/extension_points/core_extension_points.md

Add a reference to `DefaultSymbolToDocumentableTranslator` in the documentation where `DefaultDescriptorToDocumentableTranslator` is mentioned.

Add DefaultSymbolToDocumentableTranslator references in docs-developer

---

dokka-integration-tests/gradle/build.gradle.kts

Currently, if someone tries to run any Gradle Integration Test and they don't have ANDROID_HOME configured, then the Gradle build breaks because the SDK dir eagerly tries to fetch the value.
This change fixes this by only setting ANDROID_HOME in tests if possible. This allows running the integration tests, although the Android one will fail!

Fix 'provider has no value' error when running DGP integration tests without ANDROID_HOME

---

build-logic/src/main/kotlin/dokkabuild.setup-maven-cli.gradle.kts
build-logic/src/main/kotlin/dokkabuild/tasks/MvnExec.kt
dokka-runners/runner-maven-plugin/settings.xml

Currently the Dokka Maven Plugin does not use the JetBrains cache-redirector for builds. This PR adds a `settings.xml` that is used in all MvnExec tasks.
Part of [KT-64200](https://youtrack.jetbrains.com/issue/KT-64200), follow up to #3650.
(For external readers: the JetBrains cache-redirector is intended to improve TeamCity performance, and is not intended for external use.)

Use cache-redirector for Maven plugin build

---

dokka-integration-tests/gradle/src/testTemplateProjectTasksExecutionStress/kotlin/SequentialTasksExecutionStressTest.kt

This is a quick-fix to help improve the execution speed of the stress test (it currently takes ~15 minutes).
I've tried a few methods of introducing memory leaks, and all of them were caught after ~30 iterations, so 50 seems like a good number.
#3723

Reduce SequentialTasksExecutionStressTest iterations from 100 to 50

---

.github/workflows/tests-smoke.yml
.github/workflows/tests-thorough.yml

Let's upload the build reports, since the Build Scans aren't capturing issues with flaky tests.

GHA: Upload build reports on test failures

---

dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt

The cache dir is set incorrectly, leading to this warning:
> Read-only cache is configured but the directory layout isn't expected. You must have a pre-populated modules-2 directory at ~/.gradle/caches/modules-2/modules-2 . Please follow the instructions at https://docs.gradle.org/7.6.2/userguide/dependency_resolution.html#sub:shared-readonly-cache
(Note the directory ends with `/modules-2/modules-2`. So `GRADLE_RO_DEP_CACHE` should be set to `$GRADLE_USER_HOME/caches`, not `$GRADLE_USER_HOME/caches/modules-2`)

Fix read-only cache dir in DGP integration tests

---

dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/AbstractGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testExternalProjectKotlinxCoroutines/kotlin/CoroutinesGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testExternalProjectKotlinxSerialization/kotlin/SerializationGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectAndroid/kotlin/Android0GradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectBasic/kotlin/BasicCachingIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectBasic/kotlin/BasicGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectBasic/kotlin/GradleRelocatedCachingIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectBasicGroovy/kotlin/BasicGroovyIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectCollector/kotlin/Collector0IntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectConfiguration/kotlin/ConfigurationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectJsIr/kotlin/JsIRGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectMultimodule0/kotlin/MultiModule0IntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectMultimodule1/kotlin/MultiModule1IntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectMultimoduleInterModuleLinks/kotlin/MultiModuleInterModuleLinksIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectMultimoduleVersioning/kotlin/Versioning0IntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectMultiplatform/kotlin/Multiplatform0GradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectTasksExecutionStress/kotlin/SequentialTasksExecutionStressTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectWasmBasic/kotlin/WasmGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testTemplateProjectWasmJsWasiBasic/kotlin/WasmJsWasiGradleIntegrationTest.kt
dokka-integration-tests/gradle/src/testUiShowcaseProject/kotlin/UiShowcaseIntegrationTest.kt
dokka-runners/runner-gradle-plugin-classic/src/main/kotlin/org/jetbrains/dokka/gradle/tasks/AbstractDokkaTask.kt

Too many logs when using Gradle TestKit causes the tests to run slower. This is mainly because Gradle TestKit stores logs in-memory (see https://github.com/gradle/gradle/issues/23965).
Reducing the amount of logging would be beneficial for two reasons:
- The tests can run faster.
- The logs are not cluttered with unimportant messages from other Gradle tasks. We can focus on the Dokka Generator logs.
However, reducing the log level to 'lifecycle' would mean that the Dokka Generator logs would not be reported. To work around this, I added an internal flag that can override the default log level of Dokka Generator.
The result is that the tests run faster, and test results are easier to read and verify.
- Reduce the log-level of Gradle tests to 'lifecycle' by default (this can be overridden …

Reduce log level of test Gradle projects

---

.github/workflows/preview-publish-web-s3.yml
dokka-integration-tests/aws_sync.sh

After #3687 publication to S3, previews were broken because of wrong publication paths.
Bash script was logging `The user-provided path ../coroutines does not exist.` but finished successfully, so the error was unnoticed.
Both issues should be fixed now.

Fix S3 publication paths

---

docs/topics/runners/dokka-gradle.md
dokka-subprojects/plugin-versioning/README.md

Minor docs formatting update, so that the file trees look better. E.g. use `└` for the last file in a list instead of `├`.
I know these docs are probably going to be outdated soon, but the file trees not being pretty bugs me a little.
I used https://tree.nathanfriend.io/ to update the trees.

Prettify file trees in docs

---

dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/DokkaArtifacts.kt
dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/DokkaClassicPlugin.kt
dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/gradleConfigurations.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaFormatPlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/GradleTestKitUtils.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/projects/MultiModuleProject.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/MigrationMessagesTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/TryK2MessagesTest.kt

- Support toggling between K1 and K2 analysis when DGP is in V2 mode.
- Update DGPv1 to use PluginFeaturesService to query the `tryK2` flag.
- Add `org.jetbrains.dokka.experimental.tryK2.noWarn=true` to permit suppressing the K2 Analysis warning.
Depends on #3736
Fixes #3699
Fixes [KT-70659](https://youtrack.jetbrains.com/issue/KT-70659/)

Support K2 Analysis in DGPv2

---

dokka-subprojects/plugin-base/api/plugin-base.api
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/DokkaBase.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/transformers/documentables/JvmMappedMethodsDocumentableFilterTransformer.kt
dokka-subprojects/plugin-base/src/test/kotlin/transformers/JvmMappedMethodsFilterTest.kt
dokka-subprojects/plugin-kotlin-as-java/api/plugin-kotlin-as-java.api
dokka-subprojects/plugin-kotlin-as-java/src/main/kotlin/org/jetbrains/dokka/kotlinAsJava/KotlinAsJavaPlugin.kt

This is a short-term solution for #3542 
The good news is that the generated documentation does not depend on a version of the JDK anymore

Filter out JVM mapped methods

---

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/dokka/DokkaPublication.kt

- `delayTemplateSubstitution` is no longer used, it is configured automatically internally.
- `DokkaPublication` is not used as a task input, and so it does not need the Gradle task annotations. It also doesn't need the workarounds like `cacheRootPath` and `outputDirPath`.

DGPv2: Tidy configurable options

---

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/dokka/DokkaPublication.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaFormatPlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaFormatTasks.kt

- Rename `outputDir` to `outputDirectory` for consistency.
- Set the publication/module output dirs on a DokkaPublication, so that they are defined in a single place. This also makes it easier for users to configure the publication output, if desired.
Improves [KT-70880](https://youtrack.jetbrains.com/issue/KT-70880/DGP-v2-puts-output-in-the-html-subfolder-for-a-customized-output-directory)

Simplify configuration of DokkaPublication output directories

---

dokka-runners/dokka-gradle-plugin/build.gradle.kts

DGPv1 requires that `dokka-core` is exposed as an API dependency.
^[KT-70997](https://youtrack.jetbrains.com/issue/KT-70997/Dokka-Gradle-Plugin-configuration-via-convention-plugin-is-broken-after-dokkatoo-merge)

Expose `dokka-core` as an API dependency

---

build.gradle.kts

Mark directories as excluded so that they don't appear in IntelliJ's global search. This is particularly annoying for the KotlinDslAccessorsTest files.

Update IntelliJ excluded directories

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaHtmlPlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/LogHtmlPublicationLinkTask.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/GradleTestKitUtils.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/projects/MultiModuleProject.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaPluginFunctionalTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/HtmlAggregationWarningTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/KotlinMultiplatformFunctionalTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/MultiModuleFunctionalTest.kt

When Dokka HTML is generated and IntelliJ has the project open then DGPv2 logs a clickable link.
In some cases the link wasn't correct.
This fix is using the root project name as the base path, not the root directory name.
Given a project named `MyProject` in directory `/Users/rachel/projects/my-project/`.
- `http://localhost:63342/MyProject/docs/build/dokka/html/index.html` - correct
- `http://localhost:63342/my-project/docs/build/dokka/html/index.html` - wrong
fixes KT-71254
I also fixed a typo in the 'all-modules-page-plugin' warning message, and changed the logging task to be completely untracked.

Fix HTML link log when project name doesn't match directory name

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaHtmlPlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/gradleUtils.kt

Fetch the root project name in project-isolation compatible way, if possible.
Following up from https://github.com/Kotlin/dokka/pull/3788#discussion_r1750425419

Update `LogHtmlPublicationLinkTask` configuration to support Project Isolation

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/FileWriter.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/HtmlRenderer.kt
dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt

Overall the main idea of the changes is to reduce usage of `createHTML` which by default create `StringBuilder` of 32KB size and in most cases it needs much less, specifically in source-set-dependent content and during resource links embedding.
Those optimisations were found during investigation of stdlib docs build ([internal discussion](https://jetbrains.slack.com/archives/C02H0GSH474/p1726159162133729))

HTML rendering memory allocations optimisation

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaPackageOptionsSpec.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaSourceSetSpec.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/DokkaPluginTest.kt

Set `DokkaPackageOptionsSpec.documentedVisibilities` convention value to `Public`. 
This matches the existing behaviour in DGPv1 
https://github.com/Kotlin/dokka/blob/a3d5d43fa383141fae41bb88a1900e94e68c3fd7/dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/GradlePackageOptionsBuilder.kt#L68-L71
Fix [KT-70872](https://youtrack.jetbrains.com/issue/KT-70872)

Configure default documentedVisibilities for perPackageOptions

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/v2MigrationUtils.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/KotlinDslAccessorsTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/root-project-v2-migration-helpers.txt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/root-project.txt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/subproject-goodbye-v2-migration-helpers.txt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/subproject-goodbye.txt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/subproject-hello-v2-migration-helpers.txt
dokka-runners/dokka-gradle-plugin/src/testFunctional/resources/KotlinDslAccessorsTest/subproject-hello.txt

Adjust the DGPv2 migration helpers to better support migration.
- Create `dokka${Format}${Subtype}Plugin` (e.g. `dokkaHtmlMultiModulePlugin`) Configurations.
- Now that DGP has HTML and Javadoc plugins, adjust the deprecated `dokkaRuntime` Configuration to redirect to the 'base' `dokkaGeneratorRuntime` Configuration instead of the HTML-specific `dokkaHtmlGeneratorRuntime`.

Fix DGPv2 migration helpers

---

.github/workflows/tests-thorough.yml

extracted from https://github.com/Kotlin/dokka/pull/3808
The reason for this, that GA don't allow to create artefacts with the same name

Fix build-reports for thorough workflow

---

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaSourceSetSpec.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/engine/parameters/DokkaSourceSetSpecTest.kt

Add noJdkLink/noStdlibLink/noAndroidSdkLink properties to help with migrating from DGPv1 to v2.
#2515
[KT-71758](https://youtrack.jetbrains.com/issue/KT-71758)

DGPv2: Add noJdkLink/noStdlibLink/noAndroidSdkLink to help with migrating

---

dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/DokkaGenerator.kt

- Replace `map { }.maxOrNull()` with `maxOfOrNull {}`
- remove blank line log `report("")`
- consolidate dump into a single log message, so it's not split up across multiple lines.
Related to https://youtrack.jetbrains.com/issue/KT-71719/DGP-v2-Show-logging-from-Dokka-engine-in-task-output

Tidy logging in DokkaGenerator

---

dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/TestProject.kt
dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/analysis/TestProjectAnalyzer.kt

For the last month builds on `master` were RED because tests on macOS + JDK 8 failed with OOM when running `analysis-kotlin-api:testSymbols`.
After some investigation I found out that we don't dispose `KotlinAnalysis` session in test API there. When running Dokka in an ordinary way we do dispose them via post-actions.
This PR fixes this and now we run those post-actions also in test API.
Note: the same issue existed for both K2 and K1 tests, but K2 analysis (specifically standalone AA) just needs much more memory to do the same work as K1 and so OOM is not reproduced with K1
To compare, at the end of running tests with 512MB memory limit for problematic module:
* K2 analysis uses 99% of memory and runs for more than a minute
* K1 analysis uses 50% of memory and runs for 6 seconds
With …

Fix OOM error caused by not cleaning AA sessions in tests

---

.github/workflows/tests-smoke.yml
.github/workflows/tests-thorough.yml
build-logic/src/main/kotlin/dokkabuild.test-integration.gradle.kts
build-logic/src/main/kotlin/dokkabuild.test-k2.gradle.kts
build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt
dokka-integration-tests/gradle.properties
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaPluginFunctionalTest.kt

fixes https://github.com/Kotlin/dokka/issues/3805
Introduce a Gradle property to skip integration tests, which could be set on CI/locally to be able to run `check` task without running all integration tests.
If we will enable running integration tests unconditionally we will increase GA tests time from 10-15 minutes to more than an hour ([example](https://github.com/Kotlin/dokka/actions/runs/10918956278)).
Note: all tests are red in the above example because most of them failed with OOM or "not enough space" when downloading K/N toolchain for different version of Kotlin.
So enabling integration tests unconditionally on GA is not an option also for reasons other than "slow tests".
Note: running `check` on CI exposed issue with Windows and DGPv2 function tests. This should be fixed before …

Run `check` task on CI

---

build-settings-logic/settings.gradle.kts
build-settings-logic/src/main/kotlin/dokkasettings.settings.gradle.kts

Now the Develocity credentials are set on GitHub CI we can enable pushing Build Cache. This will improve build performance.

Enable Build Cache Push on GitHub CI

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaSourceSetSpec.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/DokkaPluginTest.kt

Prevent the default value of `true` from overriding the specific values provided from the top level Dokka DSL.
[KT-70908](https://youtrack.jetbrains.com/issue/KT-70908/DGP-v2-passed-Android-package-lists-to-non-Android-projects)

Fix external documentation link default values

---

.idea/vcs.xml

Tell IJ to make `KT-1234` clickable.

IJ: Add YouTrack issue links for KT-# issues

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/dokkabuild.base.gradle.kts

Enabling test retry will allow Develocity to identify flaky tests in a single build and across multiple builds.
https://docs.gradle.com/develocity/flaky-test-detection/

Enable Develocity test retry on CI

---

docs/dokka.tree

Now that DGPv2 has a beta release, we can display the migration guide.

Unhide DGPv2 migration guide

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/uriUtils.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/internal/UriUtilsTest.kt

`URI#resolve(newPath)` doesn't escape spaces
Not escaping the space breaks logging the HTML URL logging task when the IntelliJ project name has a space.

Fix appending URI Path

---

dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt
dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt

Fixes #3798
This bug appeared due to https://github.com/Kotlin/dokka/pull/3662
The merging order depends on the order of source sets. 
E.g. if we have the following order of source sets:` (expect, actual1, actual2)`. `DefaultDocumentableMerger` has a pairwise merger. So a declaration will be merged as follows:` (expect, actual1)`, then` (expect, actual1, actual2)`.
In the case of the original issue: the order of source sets `(actual1, actual2, expect)`.
Before https://github.com/Kotlin/dokka/pull/3662, it does not allow to merge actuals without an expect source set.
After that, we have a state when there is `(actual1, actual2)` that leads to an exception #3798.

Fix merging expect-actual declarations

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/gradleUtils.kt

These two utilities are no longer used. They can be removed to simplify the code.

Remove unused DGP utils

---

docs/topics/dokka-migration.md
dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaExtension.kt

Rename the property for clarity.
- `basePublicationsDirectory` controls the base output directory for all publications.
[Internal discussion](https://jetbrains.slack.com/archives/C02H0GSH474/p1728395235950729)

Rename `dokkaPublicationDirectory` to `basePublicationsDirectory`

---

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaGeneratorParametersSpec.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/formats/DokkaPublication.kt

[KT-72288](https://youtrack.jetbrains.com/issue/KT-72288)

Add an opt-in requirement for `DokkaPublication#finalizeCoroutines`

---

dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/fileTree.kt

`fileTree.kt` contains a utility for logging pretty file trees, which is useful in providing human-readable context for test failures.
This PR updates the utility to only use NIO Path, rather than the older `java.io.File`.
This change was split off from #3814 to make the PR smaller

Update fileTree test util to only use NIO Path

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/DokkaBasePlugin.kt

[KT-73024](https://youtrack.jetbrains.com/issue/KT-73024/Increase-default-memory-of-DGP-worker-to-2G)

Increase default max heap of Worker to 2G

---

docs/topics/dokka-migration.md

This PR adds a troubleshooting section in the Dokka V2 Migration guide

Update: troubleshooting section in migration guide

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/DokkaGenerateTask.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/OverrideJsonConfigTest.kt

Being able to make minor manual modifications to the Dokka configuration is exceptionally useful for local debugging.
This should not be used in production, and it is protected by an opt-in API.

Add debug utility for manually overriding the Dokka configuration JSON

---

dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt

Add new tests for KDoc links

---

dokka-integration-tests/gradle/projects/it-multiplatform-0/src/commonMain/kotlin/it/mpp0/ExpectedClass.kt
dokka-integration-tests/gradle/projects/it-multiplatform-0/src/desktopMain/kotlin/it/mpp0/ExpectedClass.kt
dokka-integration-tests/gradle/projects/it-multiplatform-0/src/desktopMain/kotlin/it/mpp0/ExpectedClass2.kt
dokka-integration-tests/gradle/projects/it-multiplatform-0/src/jsMain/kotlin/it/mpp0/ExpectedClass.kt
dokka-integration-tests/gradle/projects/it-multiplatform-0/src/jvmMain/kotlin/it/mpp0/ExpectedClass.kt
dokka-integration-tests/gradle/projects/it-multiplatform-0/src/linuxMain/kotlin/it/mpp0/CPointerExtension.kt
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/junit/TestedVersionsSource.kt

related to https://github.com/Kotlin/dokka/pull/3859#discussion_r1802881712
Note: Dokka itself is still compiled with 2.0.20
commit https://github.com/Kotlin/dokka/pull/3865/commits/282eb2b93bdc58152cea503de167579001243e3c makes project used in test compilable - previously there were redeclaration of the same symbols in `desktopMain` and `linuxMain`/`macosMain` source-sets

Run integration tests with Kotlin 2.1.0

---

dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/DokkaClassicPlugin.kt
dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/dokkaBootstrapFactory.kt
dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/tasks/AbstractDokkaTask.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaV1TaskDisabledTest.kt

Fix error when running `dokkaHtml` task when v2 migration helpers are enabled.
The problem:
- DGPv1 tasks contain automatic configuration for task inputs that cannot be disabled dynamically by V2.
- When v2 registered the migration helpers, it uses the same task types to prevent breaking changes in buildscripts.
- The task types automatically configured themselves using Configurations that v2 makes incompatible.
The solution:
- Update the v1 tasks to lazily configure the input values.
Fix [KT-72000](https://youtrack.jetbrains.com/issue/KT-72000)

Avoid configuration resolution error for v2 migration helper task

---

README.md

The url is wrong (the correct one https://hexagontk.com/stable/api/) and redirects to a scammy-like slots site. Corection: Hexagon still uses Dokka in its Api docs
Note that clicking on [Hexagon Old Url](https://hexagonkt.com/api/index.html) redirects to below image website

Replace Potentially Scam Url from Readme projects using dokka [Needs Priority]

---

dokka-subprojects/analysis-java-psi/api/analysis-java-psi.api
dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/JavaAnalysisPlugin.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/SymbolsAnalysisPlugin.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt
gradle/libs.versions.toml

Update Analysis API to 2.2.0-dev-326

---

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/DokkaPsiParser.kt
dokka-subprojects/plugin-base/src/test/kotlin/model/JavaTest.kt

The processing of supertypes for java source would convert `PsiClassType`s to `PsiClass`es while creating `AncestryNode`s. This meant that the type parameters used for the supertypes were from the `PsiClass` definition instead of the `PsiClassType` usage like they should be.
For example, in the following java code:
```
class Bar<T> {}
public class Foo extends Bar<String> {}
```
The super class type of `Foo` should be `Bar<String>`. When processing the supertypes of `Foo`, the `PsiClassType` representing `Bar<String>` was converted to a `PsiClass`. The `PsiClass` reflects the definition of `Bar`, so `Bar<T>` became the super class type instead of `Bar<String>`.
Fixes: #3996

Update java supertype processing

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/resolvers/shared/PackageList.kt

Found and tested on https://github.com/rjaros/kilua (results are reproducible even after several runs).
Reduces allocations inside [DefaultExternalLocationProvider.resolve](https://github.com/Kotlin/dokka/blob/d4d457d357627fd8100e4f0d47868020485996ec/dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/resolvers/external/DefaultExternalLocationProvider.kt#L22) from 11 GB to 1 GB. Previously `packages` were recreated for each `resolve`.
The changes don't really affect kotlinx.io and kotlinx.coroutines.
For future: probably it might make sense to also cache results of `DefaultExternalLocationProvider.resolve`?
In this specific project there are a lot of references to `@Composable` annotation passing through this function call.

Cache `packages` field, which is used by `DefaultExternalLocationProvider.resolve`

---

dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/translators/documentables/DefaultPageCreator.kt
dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt

The main idea of this fix is that pages with implicit expect/actual declarations and a single declaration should have the same name since they are merged by `PageMerger` based on the page name. Before the fix, pages with the same DRI/path were unmerged, which caused an exception.

Fix merging of implicit expect/actual with a single declaration

---

dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/InternalConfiguration.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/plugin/KotlinAnalysis.kt
dokka-subprojects/plugin-base/src/test/kotlin/transformers/ObviousAndInheritedFunctionsDocumentableFilterTest.kt
dokka-subprojects/plugin-base/src/test/kotlin/utils/systemProperties.kt

StdLib should copy some source and sample files to avoid [#3701](https://github.com/Kotlin/dokka/issues/3701).
Also, generating documentation works well with the fix for https://youtrack.jetbrains.com/issue/KT-74740. However, to have the fix, Dokka needs to update AA - #3951, which is currently blocked.

[K2] Support generating documentation for stdlib

---

dokka-subprojects/plugin-base-frontend/package-lock.json
dokka-subprojects/plugin-base-frontend/package.json
dokka-subprojects/plugin-base-frontend/webpack.config-ui-kit.js
dokka-subprojects/plugin-base-frontend/webpack.config.js

1. Fixed problems with constant reloads of the devserver when running `npm run start:ui-kit`
2. Instead of running `npm run build:ui-kit` && `dokkabuild` && `npm run start:ui-kit` we now can run `dokkabuild` && `npm start`
3. Improved watcher will also watch the react module of UI with the search component

chore: frontend dev server to watch both ui kit and search

---

dokka-subprojects/analysis-kotlin-descriptors-ide/src/main/kotlin/org/jetbrains/kotlin/idea/kdoc/findKDoc.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt
dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KdocMarkdownParser.kt
gradle/libs.versions.toml

The AA 2.2.0-dev-8822  contains the fix of https://youtrack.jetbrains.com/issue/KT-74555
Presumably, the BCV plugin fails because `kotlinx-metadata-jvm` is unable to read Kotlin 2.2 metadata (e.g. see https://github.com/jetbrains/kotlin/commit/1a45888d50e0e8599d3763a5c21a888f34ff213f ). To avoid this, inline functions were copied.

Update Analysis API to 2.2.0-dev-8822

---

build-logic/src/main/kotlin/dokkabuild/utils/downloadKotlinStdlibJvmSources.kt

The current approach doesn't work after changes in https://youtrack.jetbrains.com/issue/KT-73968
Dokka build is failing with the latest Kotlin dev build (2.2.0-dev-11137) that includes (https://github.com/JetBrains/kotlin/commit/431201fb526782706bd943a06813ef310dbdf3f0) 
The change also will be included in KGP `2.1.21`
```
* What went wrong:
Could not determine the dependencies of task ':dokka-subprojects:plugin-base:downloadKotlinStdlibSources'.
> Could not resolve all dependencies for configuration ':dokka-subprojects:plugin-base:kotlinStdlibJvmSourcesResolver'.
> Could not find org.jetbrains.kotlin:kotlin-stdlib:.
Required by:
project :dokka-subprojects:plugin-base
* Try:
> Run with --debug option to get more log output.
> Get more help at https://help.gradle.org/
* Exception is: …
```

Specify the kotlin-stdlib version for resolution

---

README.md
docs/topics/dokka-migration.md

This PR contains updates for the DGP V2 Migration guide. 
The additions to the Migration guide are:
- Add context for cases when people are not using convention plugins in their multi-module build.
- Clarify a bit earlier that the formats you obtain now require adding more dependencies (if you want javadoc)
- `externalDocumentationLinks` has changed API and it's missing in migration guide
- Document `Output` directory for additional files
- Document how to configure Dokka Plugins
- Document how to configure custom Dokka Plugins
- Document `sourceLink`
- Highlight what are migration helpers in migration guide
- Document the change of directory in DGPv2
Additionally, there are some fixes in the code format and indentation. Plus, the content within "Adjust configuration options" is now …

update: DGPV2 migration guide

---

dokka-integration-tests/gradle/src/testTemplateProjectTasksExecutionStress/kotlin/SequentialTasksExecutionStressTest.kt

Looks like after the last updates of AA in #4058 and/or #4052 AA requires a bit more meatspace memory and so our stress-test fails with K2 ([one](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_Dokka_DokkaIntegrationTestsK2/5059250), [two](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_Dokka_DokkaIntegrationTestsK2/5058216))
I've checked this test memory usage locally with K2, and I don't see any real problem with metaspace leaks.
Below are the graphs of non-heap memory usage of the test:
Before #4052 (https://github.com/Kotlin/dokka/commit/29849df76b4d7115ed509edeef6e0273d85c4be6):
Before #4058 (https://github.com/Kotlin/dokka/commit/908a4459110b6888dbd31025f7af939b9196bca7):
master (https://github.com/Kotlin/dokka/commit/3b20e70c6fce888bddf057cab290dd6e068e46 …

Increase stress test metaspace size because of the increased AA requirements

---

README.md

Reflects the new artifact `org.jetbrains.dokka:dokka-gradle-plugin`.

Update the Maven Central badge

---

dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/VersioningConfiguration.kt

Filter non-directory and hidden files from version directories

---

gradle/libs.versions.toml

It could be useful to investigate issues like this: https://github.com/Kotlin/dokka/actions/runs/10776209450/job/29882419601
Changelog: https://plugins.gradle.org/plugin/com.gradle.develocity
Note: it says "Compatible with scans.gradle.com and Develocity 2024.2 or later." - not sure which version is used on our Develocity server and how it will work if the version is lower so let's wait for https://github.com/Kotlin/dokka/pull/3790 merged

Update Develocity plugin to support "Resource usage observability in Build Scan"

---

dokka-subprojects/plugin-base-frontend/README.md

Update formatting of `dokka-subprojects/plugin-base-frontend/README.md` so it's a bit prettier, and avoid formatting warnings in IJ.

Format frontend plugin README

---

dokka-runners/dokka-gradle-plugin/api/dokka-gradle-plugin.api
dokka-runners/dokka-gradle-plugin/build.gradle.kts
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/DokkaModuleDescriptionKxs.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/engine/parameters/builders/DokkaParametersBuilder.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/DokkaGenerateModuleTask.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/engine/parameters/DokkaModuleDescriptionKxsTest.kt

Extracted from https://github.com/Kotlin/dokka/pull/3898, required to be able to update to KGP 2.1.0

Drop kotlinx.serialization compiler plugin as it's unnecessary

---

build-logic/src/main/kotlin/dokkabuild.gradle-plugin.gradle.kts
build-logic/src/main/kotlin/dokkabuild.kotlin-jvm.gradle.kts
build-logic/src/main/kotlin/dokkabuild/DokkaBuildProperties.kt
build-logic/src/main/kotlin/dokkabuild/utils/gradleKotlinCompatibility.kt
dokka-integration-tests/gradle.properties
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/maven/build.gradle.kts
dokka-runners/dokka-gradle-plugin/build.gradle.kts
dokka-runners/dokka-gradle-plugin/gradle.properties
dokka-runners/runner-cli/gradle.properties
dokka-runners/runner-maven-plugin/gradle.properties
gradle.properties
gradle/libs.versions.toml

~~NOTE: depends on #3899~~
Fixes https://github.com/Kotlin/dokka/issues/3855
For now the version of the Kotlin compiler and Kotlin Gradle plugin are the same, but it will change when we migrate to KGP 2.1.0

Use fixated Kotlin compiler 2.0.20 for compiling Dokka

---

dokka-subprojects/plugin-javadoc/src/main/resources/views/class.korte
dokka-subprojects/plugin-javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocConstructorsTest.kt

When generating Javadoc, the **Constructor Detail** section displays only the brief constructor description (i.e., the first sentence) instead of the full description. See line 252 in `class.korte`:
https://github.com/Kotlin/dokka/blob/540fe084aadac0edb333350210ee22ee9901a3de/dokka-subprojects/plugin-javadoc/src/main/resources/views/class.korte#L245-L264
[A similar issue for method details](https://github.com/Kotlin/dokka/issues/1407) was fixed [long time ago](https://github.com/Kotlin/dokka/commit/aeb2014eee704be377c06205d16f60562d2a8cf1#diff-bff61c124f11db527d3aaa3f9bd879c40b8a57bffec72087e1ecec7414d5bdddR273)  in version `1.4.0`.
This PR fixes the issue by replacing `constructor.brief` with `constructor.description`.

Fix constructor details to show description instead of brief in Javadoc

---

build-logic/src/main/kotlin/dokkabuild/utils/gradleKotlinCompatibility.kt
dokka-integration-tests/cli/build.gradle.kts
dokka-integration-tests/gradle/build.gradle.kts
dokka-integration-tests/maven/build.gradle.kts
dokka-integration-tests/utilities/build.gradle.kts
dokka-runners/dokka-gradle-plugin/build.gradle.kts
dokka-runners/runner-cli/build.gradle.kts
dokka-subprojects/analysis-kotlin-api/build.gradle.kts
dokka-subprojects/analysis-kotlin-descriptors-compiler/build.gradle.kts
dokka-subprojects/core-content-matcher-test-utils/build.gradle.kts
dokka-subprojects/core-test-api/build.gradle.kts
dokka-subprojects/core/build.gradle.kts
dokka-subprojects/plugin-all-modules-page/build.gradle.kts
dokka-subprojects/plugin-android-documentation/build.gradle.kts
dokka-subprojects/plugin-base-test-utils/build.gradle.kts
dokka-subprojects/plugin-base/build.gradle.kts
dokka-subprojects/plugin-gfm-template-processing/build.gradle.kts
dokka-subprojects/plugin-gfm/build.gradle.kts
dokka-subprojects/plugin-javadoc/build.gradle.kts
dokka-subprojects/plugin-jekyll-template-processing/build.gradle.kts
dokka-subprojects/plugin-jekyll/build.gradle.kts
dokka-subprojects/plugin-kotlin-as-java/build.gradle.kts
dokka-subprojects/plugin-mathjax/build.gradle.kts
dokka-subprojects/plugin-templating/build.gradle.kts
dokka-subprojects/plugin-versioning/build.gradle.kts
gradle/libs.versions.toml

The PR is based on https://github.com/Kotlin/dokka/pull/4014

Migrate BTA versions and all `kotlin("...")` dependencies to version catalog for consistency

---

dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/util/PsiCommentsUtils.kt
dokka-subprojects/plugin-base/src/test/kotlin/translators/JavadocParserTest.kt

In K1, we register IDE's service `JavadocManager`, we could do the same in K2:
`registerProjectService(JavadocManager::class.java, JavadocManagerImpl(project))`
However, it seems unnecessary, since the link is unresolved in K1 as well.

Fix some Javadoc links with generic parameters

---

dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/DokkaGenerateTask.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/GradleTestKitUtils.kt
dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/stringUtils.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DumpDokkaConfigurationTest.kt

Dumping the Dokka config files is useful for debugging, but can interfere with task outputs.
Here we add a flag that disables the dumping the config file by default, but we enable it for our own tests.
Fix #3958

Remove Dokka debug config file from task outputs

---

dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/TestedVersions.kt
gradle/libs.versions.toml

Fixes #4162 
Fixes #3194
Fixes #2572
Fixes #3657
Jackson 2.15.3 doesn't have known vulnerabilities (at the time this PR was created) and works fine for projects with Gradle 7.6.3+. Transitively from `jackson-dataformat-xml`, we now also have the `woodstox-core` dependency of version 6.5.1, which doesn't have vulnerabilities as well.
**So, strictly speaking, this PR drops support for Gradle 6.x.**
According to [Kotlin Gradle Plugin compatibility matrix](https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin), Gradle 7.6.3 is supported by KGP 2.1.0+ (earlier KGP versions support Gradle 6.x)
At the same time, DGPv2 will be enabled by default in Dokka 2.1.0, and according to [migration guide](https://kotlinlang.org/docs/dokka-migration.html#verify-supported-versions), it …

Update jackson to 2.15.3 which doesn't have known vulnerabilities

---

build-logic/settings.gradle.kts
build-settings-logic/settings.gradle.kts
dokka-integration-tests/maven/src/main/kotlin/settingsXml.kt
dokka-integration-tests/settings.gradle.kts
dokka-runners/dokka-gradle-plugin/settings.gradle.kts
dokka-runners/runner-cli/settings.gradle.kts
dokka-runners/runner-maven-plugin/settings.gradle.kts
dokka-runners/runner-maven-plugin/settings.xml
settings.gradle.kts

Additionally, align cache redirector usages to be similar to kotlin.git usages

Migrate to `redirector.kotlinlang.org`

---

dokka-subprojects/analysis-markdown-jb/src/main/kotlin/org/jetbrains/dokka/analysis/markdown/jb/MarkdownParser.kt
dokka-subprojects/plugin-base/src/test/kotlin/markdown/ParserTest.kt

Fixes #3775
Additionally, it could improve the performance (and memory pressure) of Markdown parsing a bit, as we don't create three `Regex`s anymore on each text processing
-----
Initially, I tested that code block and thought that the problem was inside `prism.js`, so we couldn't do anything.
But after additional checks, I was wrong, and the problem was inside our smart markdown parser, which had wrong regex replacements.
Specifically, `Regex(" >+ +")` was meant to replace only block quotes, like this one:
```
> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.
```
But in reality, it was replacing all `>` signs :)

Fix parsing of `>` in code blocks

---

build-logic/src/main/kotlin/dokkabuild.publish-base.gradle.kts

The old ones (`maven.pkg.jetbrains.space`) are deprecated and will be removed in the future.
Dokka dev/test versions are available via redirector, and soon will also be migrated to redirect to the new maven repositories:
- https://redirector.kotlinlang.org/maven/dokka-dev - for dev builds
- https://redirector.kotlinlang.org/maven/dokka-test - for test builds

Migrate publication to new dev/test maven repositories

---

dokka-subprojects/plugin-base/src/test/kotlin/markdown/LinkTest.kt
gradle/libs.versions.toml

Fixes partially https://youtrack.jetbrains.com/issue/KT-76607: #3555
Also, 
- https://youtrack.jetbrains.com/issue/KT-80178/Incorrect-modality-for-an-abstract-interface-function-with-a-redundant-open-modifier
- https://youtrack.jetbrains.com/issue/KT-80234/Incorrect-value-of-isActual-for-the-implicitly-actual-constructor-of-annotation-class

Update Analysis API to 2.3.0-dev-5493

---

dokka-subprojects/plugin-base/src/test/kotlin/content/signatures/ConstructorsSignaturesTest.kt

Test for #4055
The issues is caused by a bug in AA. It is fixed in AA version `2.3.0-dev-5493`, this PR adds a test to check the fix.

Add tests that check rendering of the implicitly actual constructors for annotation classes

---

dokka-runners/dokka-gradle-plugin/src/classicMain/kotlin/dokkaBootstrapFactory.kt
dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/dokkaBootstrapFactory.kt
dokka-runners/dokka-gradle-plugin/src/test/kotlin/internal/DokkaBootstrapProxyTest.kt
dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/DokkaGeneratorFailureTest.kt

Handle `InvocationTargetException` exception explicitly in `DokkaBootstrap` to show better error messages in DGPv2, as Gradle will not show the cause of `InvocationTargetException` without `--stacktrace` flag
Fixes #4235

Handle `InvocationTargetException` exception explicitly in `DokkaBootstrap`

---

dokka-subprojects/analysis-kotlin-api/src/testFixtures/kotlin/org/jetbrains/dokka/analysis/test/api/util/FileUtils.kt
dokka-subprojects/core-test-api/src/main/kotlin/org/jetbrains/dokka/testApi/testRunner/TestRunner.kt

KUP start failing once `createTempDir` was deprecated with error (https://github.com/JetBrains/kotlin/commit/852ea9f86e76dc1442cdab05a222a2e945e7ea21).

Replace createTempDir with createTempDirectory
